### ISSUE TITLE
Remove pants-pissing

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#1]
Need to remove urination mechanic from highest level suppression. Potentially replace pants-pissing tale with something more tasteful. Might be viable to replace with pawn entering catatonic state (mental break?).

**Comment by RenaudF** [comment]
Same comment as #5 . I'd rather leave that and perhaps change the wording. I think it's hilarious

**Comment by NoImageAvailable** [comment]
While I don't mind adult content I do like to keep things classy. Replaced the new JobDriver_HunkerDown with the old one, preliminary testing shows no problems but should watch for odd behavior just in case. If people really want this feature back its a simple job to re-enable it.
