### ISSUE TITLE
Add reload weapons job

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#100]
Colonist should reload all weapons in their inventory when they have time, to minimize micromanagement.

**Comment by NoImageAvailable** [comment]
Should limit this somehow. I've had people in the past request the ability to unload ammo from their inventories (hence the "unload" command in the reload menu) and it would defeat the purpose if pawns just immediately loaded that same ammo back in.

**Comment by Thorbane** [comment]
Hm, what about adding a timer to it, similar to keeping food in inventory for animal work?

**Comment by ProfoundDarkness** [comment]
Unloading weapons the pawn has equipped/in inventory isn't a big deal to me but unloading weapons on the ground would be nice.  That way we can reclaim some of the ammo from raids when times are tough.

**Comment by Valerate** [comment]
Is there and "End combat" event you could use to cause a reload? Or with hunting a "job well done" thing?

**Comment by NoImageAvailable** [comment]
Shouldn't this be fixed as part of https://github.com/NoImageAvailable/CombatExtended/issues/114?

**Comment by ProfoundDarkness** [comment]
With PR #140 merged that should be it for this issue.
