### ISSUE TITLE
Loadouts don't consider loaded ammo

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#104]
Loadouts don't account for ammo loaded in equipped guns, e.g. if your loadout includes beanbag rounds for a shotgun and you load them, the pawn will immediately run off to get more and drop the regular rounds you just unloaded.

Should make it so loadouts check all carried guns for loaded ammo and add that to their count when determining what to pick up.

**Comment by ProfoundDarkness** [comment]
Loadouts include ammo loaded in weapons both equipped and in inventory when considering pickup/drop from commit #105.
