### ISSUE TITLE
Rework fire mechanics

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#118]
Incendiary weapons are somewhat weak right now. They lose out against explosives in terms of killing power and the fires they spawn aren't very threatening. Some ideas to improve them:

- [x] Add "prometheum-soaked" hediff, increasing flammability of a pawn. Should be applied on direct hits with incendiary weapons. This way Molotovs become a viable option for defeating power armor/Centipedes, WWII-style.

- [x] Rework auto-rain mechanics. Implement proper flammability mechanics to handle map-wide inferno. Might use a mapcomp to track days since last rain to scale plant flammability and randomized wind direction to influence fire spread direction. Might be better off implementing this one as a separate mod/addon.

- [x] Decrease effectiveness of firefighting. Hitting a raider siege camp with incendiary mortars just causes them to immediately box the fire to death. Might scale down effectiveness of boxing, possibly add a chance to catch on fire?

- [x] Increase fire spread rate to make incendiary launchers more of a threat to nearby pawns?

**Comment by ProfoundDarkness** [comment]
btw: There is already a mechanic that has a chance of a pawn to catch on fire (if you've ever tried to micromanage fire fighting outside of a home zone).  Generally a pawn near a heavy fire will start to catch, if there isn't another pawn nearby and that other pawn isn't busy then that other pawn will put it out.

Once it gets to a certain strength on the pawn then the pawn will drop other duties and start running around (potentially into a blaze) with periodic stops trying to beat the fire out on themselves.  If the fire gets over a certain point they will get downed from it (shock?).  If they aren't too damaged after the fire is out they tend to get up pretty quick.

**Comment by dvalroth** [comment]
Pawns catch fire when a fire mote lands on them. They're pretty easy to spot and just move the pawn away from if you're manually fighting the fire, which you should be. With large numbers of pawns fighting the fire it'll just get beaten down and isn't really an issue.

**Comment by NoImageAvailable** [comment]
Implemented in 1.6
