### ISSUE TITLE
Fix hunting

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#12]
Pawns currently hunt from max weapons range. Need to detour their positioning method and change to use a max range of 10-15 cells or so.

**Comment by RenaudF** [comment]
Could the range depend on the size of the target?
Bigger targets are easier to hit and more dangerous if enraged, also they take more bullets to go down. Having a few more tiles in between seems like a good thing in that case.

**Comment by RenaudF** [comment]
Following up on previous point could we make hunting small game (rats, rabbits, squirels ... ) possible with melee weapons? Would be a boon for food gathering early game and keeping pests off the crops.
Logic could apply for target that fall under a certain dps threshold perhaps.
Also trying to shoot small targets is a massive waste of ammo.

**Comment by NoImageAvailable** [comment]
Both good suggestions. Scaling range to body size is easy enough, just need a good formula. I'd still limit maximum range to 20 cells though since that Thrumbo could be in the middle of a dense forest, with trees blocking all your shots.

Should be easy to make a cutoff for target size/DPS and switch to melee weapon if available. Would need to account for pawn natural melee though (i.e. stuff like power claws) to determine whether to use fists if no proper melee weapon is in inventory.

**Comment by Alicecomma** [comment]
Some more issues on the SK version of CombatRealism: 

> retep998 commented on 29 Dec 2016
> Right now when hunting pawns will happily put a tree directly between them and the target, making them burn through ammo destroying the tree before they can actually shoot the animal itself. It would be really awesome if pawns could position themselves to get a clear shot.

> adalah217 commented on 5 Jan • edited
> One more (possible) bug here:
> 
> if a pawn runs out of ammo while hunting, they will stand over them trying to fire while the "out of
> ammo" flashes up over and over.
> 
> Edit: They eventually give up though.

> MGuffin commented 26 days ago
> Another issue while hunting is that pawn are quite unable to finish animals (not just big ones like rhino, almost all of them).
> They are also unable to kill sleeping animal (due to the protection bonus for low target I believe)
> So, they can fire for hours, using all their ammo for nothing.
> It's kind of awkward

**Comment by NoImageAvailable** [comment]
Hunting range fixed as part of https://github.com/NoImageAvailable/CombatExtended/commit/9994af9f7af011cf7fc3b6175bb2db1fb19a2999

Tracking the animal execution bug as a separate issue https://github.com/NoImageAvailable/CombatExtended/issues/32
