### ISSUE TITLE
"Make Loadout" button placement

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#126]
Testing on Beta 1.0.
I'm sure this is one you already know, but in interest of doing what someone testing a beta version should and reporting issues, this button placement is less than ideal:
![screenshot 2017-04-19 23 56 29](https://cloud.githubusercontent.com/assets/206142/25213059/2d86f744-255c-11e7-8876-1a2a6c959e88.png)

**Comment by NoImageAvailable** [comment]
In addition to being misaligned it looks like the button is missing an IsColonist-type check, since its showing up on non-colonist pawns.

**Comment by NoImageAvailable** [comment]
Should be fixed with #136

**Comment by ProfoundDarkness** [comment]
This appears fixed.  Button is back where it should be and not seeing it on non-colonist pawns.
