### ISSUE TITLE
Mis-titled Learning Helper screen

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#127]
Tested on beta 1.0.

![screenshot 2017-04-20 06 41 23](https://cloud.githubusercontent.com/assets/206142/25227549/edaca28c-2596-11e7-9431-f3a51965820f.png)

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/bec0d2dadfa31bc7cf7a33d298618552b82d97cb Should be fixed now
