### ISSUE TITLE
Fragmentation balance.

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#14]
Skyarkangel significantly reduced the amount of fragments generated in explosions and slightly upped their damage.  This results in fragmentation being much less dangerous, may want to revert these changes.

Also smaller fragments have a higher armor penetration rating, this seems off.

**Comment by NoImageAvailable** [comment]
There are performance problems with higher fragment counts. Increasing the amount of fragments means increasing the CPU load and a lot of people already experience FPS drops during mortar barrages.

Armor penetration in real life scales inversely with size (smaller fragments are smaller) and speed (smaller fragments have less mass, so are faster).
