### ISSUE TITLE
How pawns react to catching on fire should be improved

### ISSUE THREAD

**Issue by 213LBC** [NoImageAvailable/CombatExtended#144]
If this mod is all about realism, I'd like it if pawns acted a little more realistically to fire. If the fire isn't that big, they should be able to try and pat it out themselves. 
-This could be balanced by forcing pawns that are on fire to either put their guns into their inventory or drop their weapon, preventing them from fighting/moving for a while. 

-This also would prevent weapons from deteriorating due to fire, which doesn't make sense, because it is your clothing that is on fire, not your weapon
-
To make it fair though, there could be a chance of failure which could result in the normal panicked running around. 

-Also, if molotovs and inferno launchers could drench people in fuel, making them burn profusely that would make them a lot more useful! I think they are pretty useless against anything but bugs as of now, they could use a buff

While it may not be directly combat,  fire is involved with combat quite often, due to raiders lighting many items on fire, or using molotovs and inferno launchers, so I think it should be something made more realistic in this mod.

**Comment by NoImageAvailable** [comment]
1. This mod is not "all about realism" its about adding depth to the combat. There's a reason its no longer called Combat Realism.
2. Pawns already put themselves out as part of vanilla behavior.
3. Your other suggestions overlap with the stuff already listed in #118. Please check the open issues before flooding the tracker with duplicates.
