### ISSUE TITLE
Cannot pick up ammo because "cannot determine armor penetration"

### ISSUE THREAD

**Issue by 213LBC** [NoImageAvailable/CombatExtended#145]
I couldn't pick up any ammo right off the bat, evrery time I tried, the debug screen popped up and saud this over 'n over again. And now it won't stop popping up, unplayable :(

**Comment by NoImageAvailable** [comment]
I have no idea what your issue is from your description but judging from your comments in the forum thread I'm assuming you have an incorrect setup causing your issues. Just because this is a public repo doesn't mean you should download unstable builds meant only for internal testing.
