### ISSUE TITLE
Question regarding compatibility to weapon mods

### ISSUE THREAD

**Issue by Mythos** [NoImageAvailable/CombatExtended#146]
Hey there,

I'm silently following your progress and I always wonder if the existing weapon mods (like RT's Weapon Pack + CR compatibility patch) work or will work with CE?

If not, how easy is it to find out, how the object structure changed or maybe if it needs to be rewritten from scratch?

Unfortunately I don't see a way to contact you for such discussions/questions, as there's no forum thread IIRC.

Best Regards,
Mythos

**Comment by NoImageAvailable** [comment]
There is a forum thread in the Unfinished mods section. This is not the place to ask these things.

**Comment by Mythos** [comment]
I just saw it, would be cool if you could add a README with a link to this thread or something. ;-)
