### ISSUE TITLE
Loadouts persist between games (quit current game -> new game)

### ISSUE THREAD

**Issue by ProfoundDarkness** [NoImageAvailable/CombatExtended#149]
If a player exits a currently running game and starts a new game (not via load but via new game) Loadouts from the previous game will persist.  This seems to be due to how Loadouts get around the whole mapcomponent issue now that there are multiple maps.  There is a single instance which contains all Loadouts which all maps look to when performing activities related to Loadouts.

There are a couple of ways I can see to get around this.  1 - Detect when a game session ends or a new game session starts and blank the instance variables.  2 - Make the instance variable somehow dependent on the planet, ie RimWorld.Planet.World object.

The way that loading a save works this is not an issue there.

I can probably attempt either of these but really just need to know which path to pursue or if there is another desirable path.

**Comment by NoImageAvailable** [comment]
This seems like a very low priority thing since it doesn't really affect things. In fact, I'm thinking it might even be beneficial to save loadouts between save sessions since you'll typically recreate the same loadouts for every game. I'll put the question in the Discord and see what feedback I get.

**Comment by ProfoundDarkness** [comment]
Hmm... I'm barely here atm (very tired, long day) but now that I think about it making loadouts dependent on world is probably a bad idea should we have the ability to have more than one colony per world again (like it was before A16 where you could re-use an old world for a new colony, not where the colonists create secondary colonies).

Might be best if when this is fixed an implementation of persistent loadouts saved outside of the game save... might be neat but I gather from EdB's work (where one could save startup conditions) that can be quite the headache to implement well.

I'm thinking in the meantime since there are those that do like it and it's not really hurting anything that this is a won't fix bug for now.

**Comment by NoImageAvailable** [comment]
Reopening, as A17 offers an easy solution with new WorldComponent class.

**Comment by NoImageAvailable** [comment]
Should be fixed with #206
