### ISSUE TITLE
Re-enable Melee hunting (Feature request)

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#152]
With A16 Melee hunting was disabled, I'd love to be able to hunt with melee again

**Comment by NoImageAvailable** [comment]
It's an easy enough change to make, however should be kept as an option in the mod menu. People complained in the past about leaving their shooters with knives after a raid then having them try to hunt with those.

**Comment by frenchiveruti** [comment]
Also, if a shooter runs out of ammo because my base run out of resources for it, the moron will probably go fist fighting a muffalo.

**Comment by NoImageAvailable** [comment]
We could just add a check for having any weapon equipped (although certain low quality weapons would actually end up worse than fists).

**Comment by frenchiveruti** [comment]
Leaving it optional and with a melee weapon superior to a normal quality steel gladius should be enough to please everyone.
Maybe a check for DPS with a melee weapon? Or is a lot of trouble? Because you can have a melee wep but your pawn is high as f. and his DPS would be very low.

**Comment by NoImageAvailable** [comment]
Feature has been implemented as part of the ongoing A17 port. Mod menu now has an option to allow pawns to hunt with melee weapons equipped. No DPS checks or anything so if you give your hunters shoddy wooden shivs expect them to get their asses handed.
