### ISSUE TITLE
Add ballistic shields

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#17]
People have been asking me to add ballistic shields. Should be able to adopt skully's shield mod easy enough but would need to be integrated with the armor system (i.e. bullets have a chance to penetrate shield and hit pawn with reduced damage).

**Comment by RenaudF** [comment]
various shields implementation I've come across:

- https://github.com/Skullywag/MedievalShields
- https://github.com/Skullywag/PersonalShieldMKII
- https://ludeon.com/forums/index.php?topic=30070.0
- https://ludeon.com/forums/index.php?topic=16864.0

non personal shields but perhaps still relevant:

 - https://github.com/Skullywag/DefenceShield
 - https://ludeon.com/forums/index.php?topic=14711.msg153943#msg153943
 -

**Comment by Skullywag** [comment]
All those shields are based on mine it seems, so i win!

Will need a sprite but im using one of mine for now while i work on this.

**Comment by NoImageAvailable** [comment]
One of the latest commits already has a ballistic shield sprite provided by 3DGrunge, you can use that.

**Comment by NoImageAvailable** [comment]
As of https://github.com/NoImageAvailable/CombatExtended/commit/bec0d2dadfa31bc7cf7a33d298618552b82d97cb ballistic shields are fully implemented armor-wise. Ballistic shield apparel is fully implemented.

TODO: 
- [ ] Implement pre-industrial shield made at smithing bench from leather/wood/steel/plasteel
- [ ] Implement proper formula for calculating melee block chance, currently uses flat 50% chance as placeholder

**Comment by NoImageAvailable** [comment]
Done as part of the melee overhaul https://github.com/NoImageAvailable/CombatExtended/commit/f1d6f2d40658020d8782db8248ebb1f9620f5065
