### ISSUE TITLE
Port to A17

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#172]
With A17 around the corner and HugsLib having released an update for A17 its time to start thinking about porting CE to the new release. Referring to this [thread](https://ludeon.com/forums/index.php?topic=32181.0) we'll need to:

- [x] Refactor all Scribe references, as well as any other code changes such as ThingContainer becoming ThingOwner.
- [x] Convert AmmoInjector class to use the new Mod class. Clean up legacy CCL special injector code.
- [x] Potentially convert HugsLib mod settings to also use new Mod class. Need to look into how exactly the vanilla implementation differs from HugsLib and decide which one to use (I'd rather not have an unneeded dependency but if vanilla is too bare-bones/difficult to implement we might just keep it). Low priority on this one.
- [x] Check if the new World/GameComponent classes provide a potential fix for #149.
- [x] Convert all detours to Harmony patches. Some notes:
  - FloatMenuMakerMap can potentially be done as a patch (can't do it as a prefix because it modifies certain vanilla options like wear apparel)
  - Hediff detours need to be checked against the new medical balance (might have become obsolete)
  - ~~MassUtility detour makes reference to CarryWeight which can probably be refactored away (since vanilla now has its own stat for pawns' weight capacity)~~
  - Inventory related detours (ThingContainer, Apparel/EquipmentTracker) might be candidates for postfix, since many of them just trigger CompInventory cache refresh on picking up/dropping stuff.
  - VerbsTick can be done as PostFix but would need to iterate a list twice. Might be better to do as patch/detour.
- [x] Current Harmony patches need to be checked against new code to make sure they're up to date (TendUtility patch is already known obsolete)
- [x] Current def extension classes can be replaced with ModDefExtension
- [x] All current vanilla def edits should be changed to def patches.
- [x] Additional edits that were rejected for compatibility reasons (such as adding bullet damage resistance to work benches or the changes proposed in #54) can now be implemented as patches.
- [x] Implement the new smoke mechanics into the aiming system.
- [x] Convert Assign tab UI to new format

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/a8a0811421fcae612154ab28b809917bc71029e6 Knocked out all the low-hanging fruit in terms of refactor. Looks like loadout UI will need to be looked into to make it compatible with the new system of def-defined windows.

Turret_GunCE needs a good looking at as well. Glancing over it seems there have been some relatively sizable changes to the way vanilla turrets work and those need to be implemented. Should consider the possibility of consolidating the classes to cut down on copy-pasta maintenance like that in the future.

**Comment by ProfoundDarkness** [comment]
Will probably tackle #149 and #173 when porting the loadout system to use the new component mechanic.

**Comment by NoImageAvailable** [comment]
Updated the task list with a point about converting the Assign UI so we don't forget. Currently we have a basically functional port but its stretching the boundary of the window. Need to modify the column workers for outfits and drug policies to take up less space.

We're also missing the old weight/bulk bars completely, need new column workers for those too (need to take those into account when determining new width for aforementioned workers)

**Comment by NoImageAvailable** [comment]
Implemented smoke in https://github.com/NoImageAvailable/CombatExtended/commit/fe6c85d6f3f23274d7184ccd99baf8777db5b0a6

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/0ed4377c25e194ffee80cc19b507cf9167191257 Fully implements the assign tab
