### ISSUE TITLE
Loadouts saving with null pawns

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#173]
Currently the game will sometimes save loadouts with null pawn. According to sky these can in rare cases lead to save game corruption.

**Comment by ProfoundDarkness** [comment]
Huh... the code that loads the loadout<->pawn connections has a check for if the pawn is null (validation or something) and if so drops that dictionary entry from ever finishing the load.

**Comment by NoImageAvailable** [comment]
Should be fixed as part of #206
