### ISSUE TITLE
Unable to reload turret If you somehow get ammo ontop of it

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#174]
http://imgur.com/a/yhzRa

I assume this happens since during the reload animation they put the ammo ontop of the turret, and "insert" it, but if something is on-top, block it, it fails. The reload bar fills, but once the job is complete the turret is still out of ammo.

Another hing thing to note is that if you only shoot a few bullet, say you have 87 left, the pawn that goes to reload will only bring 13. When he starts to reload he takes out the 87 remaining to make a stack of 100 on-top of the turret. If anything block the job and the reload fails the turret now has 0 ammo. 

I had a turret with 87 remaining ammo, and he came to reload. I interrupted him mid job, and told him to reload again (making sure the "closest" stack of ammo wasn't the one on the turret.

He brought another 100 to reload and put that ontop of the turret aswell, making it a stack of 200. Which I assume the turret wont accept since it magazine is only 100 so the reload job failed. The only way to fix it now is the have a pawn manually remove the excess ammo ontop of the turret.

**Comment by ProfoundDarkness** [comment]
FYI The take ammo out of weapon on reload is correct behavior, this step is normally hidden from you when it works since the actual unload and reload all happen in the same moment/tick.  So that part isn't strange.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/daf23da7aef66cbe6a9f507da418dce1e34f0d29 implements some changes to the way the reload jobdriver works. Instead of dumping the ammo onto the turret it now keeps it carried by the pawn.
