### ISSUE TITLE
Exception when crafting ammo

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#175]
Testing on v0.3.1-beta.

When one of my colonists went to craft ammo, it produced this exception, cancelled the crafting:
```
JobDriver threw exception in initAction. Pawn=Hill, Job=DoBill A=Thing_AmmoBench224739 B=Thing_Steel380966 C=(78, 0, 197), Exception: System.InvalidCastException: Cannot cast from source type to destination type.
  at Verse.AI.Toils_Recipe+<MakeUnfinishedThingIfNeeded>c__AnonStorey416.<>m__66D () [0x00000] in <filename unknown>:0 
at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x00000] in <filename unknown>:0 
```

Full log: https://gist.github.com/HugsLibRecordKeeper/23974343b008b921a0395532d65ff056

**Comment by NoImageAvailable** [comment]
Did you start the save under 0.3.0 before upgrading, with the bill having been set up before the upgrade?

**Comment by Maeyanie** [comment]
Not certain, but that's definitely possible. I'll re-make the job next time I play and let you know if it happens again.

**Comment by NoImageAvailable** [comment]
If it is the bug I'm thinking of it should be fixable by deleting the bill and assigning a new one.

**Comment by Maeyanie** [comment]
Yes, that did seem to work. Closing this.
