### ISSUE TITLE
Decaying animal corpses have null innerPawns?

### ISSUE THREAD

**Issue by dvalroth** [NoImageAvailable/CombatExtended#182]
Nothing bad actually seems to be happening, but when an animal corpse decays away the log records for instance
`Alphabeaver_Corpse252672 has null innerPawn. Destroying.
Verse.Log:Error(String)
Verse.Corpse:TickRare()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`

followed by
`Tried to destroy already-destroyed thing Alphabeaver_Corpse252672
Verse.Log:Error(String)
Verse.Thing:Destroy(DestroyMode)
Verse.ThingWithComps:Destroy(DestroyMode)
Verse.Corpse:Destroy(DestroyMode)
Verse.Corpse:TickRare()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`

**Comment by NoImageAvailable** [comment]
Is this on A17?

**Comment by dvalroth** [comment]
It was A16. I'll see if it still happens in the new version.

**Comment by dvalroth** [comment]
This issue no longer seems to exist.

**Comment by NoImageAvailable** [comment]
>This issue no longer seems to exist.

Closing this until further notice then.
