### ISSUE TITLE
No XP gain from shooting and melee

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#188]
Firing weapons seems to have no effect on shooting skill.

Edit: Apparently melee doesn't provide skill growth either.

**Comment by ProfoundDarkness** [comment]
Observation: While looking at something else (and forgot to remove a breakpoint) noticed that this.isAiming was always coming back false with every tick in VerbTickCE.

**Comment by ProfoundDarkness** [comment]
I misunderstood how the mechanic works, the variable in question only gets set if the pawn is in careful aim mode which none were in during my tests.

Did a couple more tests and found that the xp variable is being set to something non-0 but very small, ie a pistol only yields 1 xp per shot in snapshot mode.  Tried setting that to something insane (10000) and still saw no experience gain.  It's *additional* XP that is accumulated while isAiming is true.

**Comment by AndrewZo** [comment]
Melee XP works fine..

**Comment by AndrewZo** [comment]
So, all works fine, but little problem in [Verb_LaunchProjectileCE.cs](https://github.com/NoImageAvailable/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs)

ShooterPawn doesen't return anythig? wut?)

**Comment by ProfoundDarkness** [comment]
Verified what AndrewZo pointed out and fixed the problem.  Evaluating if now is the time to implement a small XP boost similar to how A17 works.

**Comment by ProfoundDarkness** [comment]
Regarding XP and Melee, In RimWorld Core xp is only rewarded for hitting a mobile target so no xp for downed targets and punching walls.  Also it looks like no xp for missing the target.  That might explain some of the reports of no xp from melee.

**Comment by NoImageAvailable** [comment]
> Also it looks like no xp for missing the target

Might make sense to rebalance melee XP then to match the reduced hit rates from dodge/parry. Also would make sense to award XP for successfully dodging/parrying attacks. Will track this as part of #160. Since it sounds like ranged and melee XP is working now I'm closing this.
