### ISSUE TITLE
Stacking weapons inventory bug

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#19]
If a colonist has any sort of weapon that stacks (like frag grenades) equipped and also has another one in their inventory, then attempting to equip a different weapon will cause an error (below) and destroy the weapon you tried to equip.

Basically the inventory system can't handle unequipping a weapon into an existing stack in the inventory.

Pawn Teddy, Pimp got primaryInt equipment Weapon_GrenadeEMP85297 while already having primaryInt equipment Weapon_GrenadeFrag85296
Verse.Log:Error(String)
CombatExtended.Detours.Detours_Pawn_EquipmentTracker:AddEquipment(Pawn_EquipmentTracker, ThingWithComps)
CombatExtended.CompInventory:TrySwitchToWeapon(ThingWithComps)
CombatExtended.<>c__DisplayClass18_1:<DrawThingRow>b__2()
Verse.FloatMenuOption:Chosen(Boolean)
Verse.FloatMenuOption:DoGUI(Rect, Boolean)
Verse.FloatMenu:DoWindowContents(Rect)
HugsLib.GuiInject.<>c__DisplayClass1:<_WindowOnGUI>b__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by NoImageAvailable** [comment]
Should be fixed now https://github.com/NoImageAvailable/CombatExtended/commit/4fac0b372ef62eed61bba4055d9919e49e0f8eee
