### ISSUE TITLE
"Inspect string of MinifiedTurret contains empty lines."

### ISSUE THREAD

**Issue by ProfoundDarkness** [NoImageAvailable/CombatExtended#195]
Replication:
-Start a new game.
-Create a turret via debug place thing near. (manned turret in one case, M240B)
-Click on the M240B minified turret and observe the error pop up.

Pretty sure it's a ErrorOnce type of error so won't pop up further.

**Comment by NoImageAvailable** [comment]
I suspect this is related to a bug mrofa mentioned a few days ago in the Discord, where base.GetInspectString returns null for some reason, but only the first time it is called.

**Comment by notfood** [comment]
It's definitively the \n at the end. Remove it. I had the exact same issue with StringBuilder and AppendLine in another mod.

add `stringBuilder.Length--;` before this line and it'll fix that warning.

https://github.com/NoImageAvailable/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs#L298

**Comment by NoImageAvailable** [comment]
Thanks for pointing this out. After looking at the line in vanilla it looks like it now has a new extension method TrimEndNewlines(). Applying it to the return string fixes the error, I'll have it in my next commit.

**Comment by notfood** [comment]
With StringBuilder the most efficient choice is to cut the lenght before calling toString.

https://stackoverflow.com/a/17215160

**Comment by NoImageAvailable** [comment]
The vanilla method seems to have some additional checks in place to only trim new lines. I mean using Length-- seems like the best way here but if vanilla is doing it this way I'm assuming there is some reason for it.

https://github.com/NoImageAvailable/CombatExtended/commit/45c9082d365e28157fc09dd663788ef922608d9b contains the TrimEndNewlines() fix, so closing this down (but if you know the reason why vanilla does it this way feel free to post it and I'll switch it to Length--)
