### ISSUE TITLE
Interrupting the reload of an out of ammo manned turret requires manual reload command.

### ISSUE THREAD

**Issue by ProfoundDarkness** [NoImageAvailable/CombatExtended#196]
If you have a manned turret that runs out of ammo and the pawn starts the reload process (turret states that it's "Reloading") and then you interrupt the pawn before they finish the turret requires a manual reload command (gizmo/button next to the ammo bar) to get it reloaded.

The issue is that the turret has the isReloading flag set once the bar appears under the turret while the pawn is reloading the turret.  When the pawn goes off to do something else that isReloading flag remains on the turret and all code paths which might attempt to automatically reload the turret check that flag and will not automatically attempt reload automatically.

**Comment by ProfoundDarkness** [comment]
NOTE: This is with the ammo system disabled.  It looks like there *might* be a bail out to allow auto-reload with ammo system on.

One possible solution would be for if the isReloading flag is present but there are no pawns reloading the turret to clear the flag.

Between the ammo system being off and the isReloading flag being on there doesn't appear to be an automatic reload path in the code if the pawn was interrupted.  There *may* be an auto-reload path with ammo system on but I didn't fish along that route very far.

**Comment by ProfoundDarkness** [comment]
Had another thought... Along with the reloading flag we store the pawn that is doing the job onto the turret.  When checking the reloading flag we should be able to cheaply check if the pawn is still doing the reload job (alive/not null, that kind of stuff) on that turret still (only do the check when it matters, ie not when we want to display the reloading inspect string).  If the pawn isn't doing the reload job anymore then we clear the flag, after that the other automatic routines should step in.

**Comment by NoImageAvailable** [comment]
Should be fixed with #222. Reload flag is now cleared as a finish action on the wait toil, so if the job is interrupted it will still get cleared.
