### ISSUE TITLE
[BUG][A17]Mortar shooting by itself

### ISSUE THREAD

**Issue by Giperman** [NoImageAvailable/CombatExtended#198]
I built a vanilla mortar. When enemy is shown on map, it's targets him by itself withoun an operator, and shoots by not using any shells

**Comment by NoImageAvailable** [comment]
Mortar def was bugged, already fixed it as part of https://github.com/NoImageAvailable/CombatExtended/commit/bd7abe9f28b688435b5c39a40297a9dd396025d5
