### ISSUE TITLE
Melee: Downed characters can parry

### ISSUE THREAD

**Issue by ProfoundDarkness** [NoImageAvailable/CombatExtended#199]
ShortChangeHero (on discord):

> Also, while finishing off a downed raider, he parried an attack. Probably not really something we want. :joy: A level 2 melee attacking a downed level 8.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/45c9082d365e28157fc09dd663788ef922608d9b Fixed
