### ISSUE TITLE
Fix ammo armor penetration

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#2]
Armor penetration algorithm gets projectile from firing weapon's def, meaning armor calculation doesn't take into account actual projectile fired. Need to change dinfo back to passing projectile to armor calculation.

**Comment by NoImageAvailable** [comment]
Latest dev branch fixes all these issues and adds support for pawn natural melee to define armor penetration values within the verbs. Known limitation: if multiple verbs are assigned the same linkedBodyPartGroup only the first in the list will be used for penetration.

**Comment by RenaudF** [comment]
please link commits to issues. see dcb746a551c0eb4b9270f180c6cbf8c16c58a383
