### ISSUE TITLE
No FSX from Boomrats

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#204]
Testing on  v0.17.0.4.1-beta.

Tamed boomrats don't seem to produce FSX to "shear" any more. I haven't yet seem a boomalope to check if they do.

**Comment by NoImageAvailable** [comment]
Boomrat patch was missing CompShearable, fix will be in my next commit.

**Comment by NoImageAvailable** [comment]
Should be fixed with https://github.com/NoImageAvailable/CombatExtended/commit/43883d5c67e1bd43b0010d787d6a6a6e8bc08257
