### ISSUE TITLE
Convert DamageWorker_CE to Harmony

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#209]
With recent refactors to fix #177 it is no longer necessary to maintain this as a separate class. The following changes were made from vanilla and can be rolled into Harmony patches:

- ApplyDamageToPart(): replaced a call to vanilla armor utility with to our own, as well as a check if deflection modified the hit body part. Appended a loop to apply secondary damage at the end (postfix-able).

- CalculateOldInjuryDamageThreshold(): replaced vanilla with custom formula.

- CheckPropagateDamageToInnerSolidParts: removed a call to vanilla armor utility

- CheckDuplicateDamageToOuterParts: removed a call to vanilla armor utility

Once this is done we can remove DamageWorker_FlameCE as well, since its only there for inheritance from AddInjuryCE.

**Comment by JonnyNova** [comment]
I'm working on this one

**Comment by JonnyNova** [comment]
I'm not working on this anymore

**Comment by NoImageAvailable** [comment]
ApplyDamageToPart() patch implemented in https://github.com/NoImageAvailable/CombatExtended/commit/acd949868b63286a4b0ff4636ec1d0d10e40ee8f

The Check... methods no longer exist/reference ArmorUtility and don't need patching anymore. CalculateOldInjuryDamageThreshold still needs to be patched, assuming we care enough about a relatively insignificant feature.

**Comment by Alicecomma** [comment]
CalculateOldInjuryDamageThreshold doesn't seem to exist anymore in 1.0. Maybe its functionality has been moved?
