### ISSUE TITLE
tribal raiders drop pilum

### ISSUE THREAD

**Issue by AndrewZo** [NoImageAvailable/CombatExtended#214]
hi. Sometimes when happens tribal raid they drop just 1 pilum. Also it not forbidden, so your colonists will try to get it.

log error:

> Verse.Pawn_EquipmentTracker container tried to drop  null which it didn't contain.
> Verse.Log:Error(String)
> Verse.ThingOwner:TryDrop(Thing, IntVec3, Map, ThingPlaceMode, Thing&, Action`2)
> Verse.ThingOwner`1:TryDrop(Thing, IntVec3, Map, ThingPlaceMode, ThingWithComps&, Action`2)
> Verse.Pawn_EquipmentTracker:TryDropEquipment_Patch1(Object, ThingWithComps, ThingWithComps&, IntVec3, Boolean)
> RimWorld.<MakeNewToils>c__Iterator52:<>m__10C()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:DriverTick()
> Verse.AI.Pawn_JobTracker:JobTrackerTick()
> Verse.Pawn:Tick()
> Verse.TickList:Tick()
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()
>

**Comment by NoImageAvailable** [comment]
Probably another one for the pile of issues that could probably be fixed by implementing #154

**Comment by NoImageAvailable** [comment]
Can no longer reproduce this after implementing #154, going to assume fixed until evidence to the contrary.
