### ISSUE TITLE
Pawns go for new ammo immediately after reloading when hunting

### ISSUE THREAD

**Issue by loony383** [NoImageAvailable/CombatExtended#229]
Something I've notice since I started following this, it seems that having the loadout specified amount of ammo is their number 1 priority. Often stopping hunting as soon as they reload because they no longer hold enough ammo to match the loadout within their inventory.

Instead, it seems that it should be slightly less aggressive about restocking their inventory. If they still have ammo on them, I'd expect them to keep trying to hunt the animal they are targeting until they either run out of ammo completely or they succeed and have hauled the hunted animal back, and then going to restock.

As for version - I have been doing a fresh pull on the Development branch each time before playing

**Comment by ProfoundDarkness** [comment]
Hmm... now that's an interesting one...  IIRC the loadout and reload weapons (when idle) CE jobs are priority based... some ways around this could be to change the priority of the hunting job (Harmony, messes with Core balance), change the priorities of the CE jobs that are interfering (reload job is supposed to come after loadout job), or add a check in one or both of the CE jobs to not override hunting...

**Comment by NoImageAvailable** [comment]
For the record, the current functionality is to only pick up ammo within close proximity unless it is below 50% of the loadout value. I'm guessing this is either because loadout ammo is set too low or hunting within close proximity of a stockpile.

**Comment by loony383** [comment]
When playing last night, I did notice that this wasn't happening all the time like I previously thought, only most of the time.

What is the proximity for fetching ammo? In almost all cases my pawns were 50-75+ tiles away from the ammo stockpile when this occurred, and would be fetching ammo when they reloaded for the first time with a load out ammo set to 30 (so restocking before dropping below 50% of what they are set to carry). Specifically in most of the times I've seen it happen, it's using the Bolt action rifle with HP rounds

**Comment by NoImageAvailable** [comment]
After looking into it some more I think you might just be running into hunting timeout. Pawns will re-evaluate their work priorities if they've been hunting for a while at which point they'll usually run off and do something else. Older builds have had several bugs decreasing hunting accuracy so pawns likely spent more time hunting then they should have.

**Comment by loony383** [comment]
This could be the case, as I am playing on a 300x300 map where I typically have to travel further to hunt, Perhaps this timeout needs to be adjusted for larger map sizes as it's really inefficient for a colonist to go out hunting, and then give up after only one 1 magazine. I can only imagine it'd get worse the larger the map

**Comment by NoImageAvailable** [comment]
Haven't heard anything back from OP, so going to assume issue is resolved.
