### ISSUE TITLE
Pick from stack menu bug

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#23]
When manually picking items from a stack (typically ammo) there are 3 choices (numbers given as example)
1. pick items
2. pick items (half 75)
3. pick items (full 150) 

In fact 1 and 3 are the same thing. It would make more sense if 1 was pick only one from the stack.

I might be wrong but I think it used to be that way, might be worth checking history in the file.

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/4fac0b372ef62eed61bba4055d9919e49e0f8eee
