### ISSUE TITLE
pawn shot himself

### ISSUE THREAD

**Issue by AndrewZo** [NoImageAvailable/CombatExtended#234]
Hi. There is a bug, pawns can shot himself.

To reproduce this just move directly to another pawn (at one point) and try to shot him.

![default](https://user-images.githubusercontent.com/10649514/26972396-3f07d1e2-4d1a-11e7-8584-b50faccebcee.png)

**Comment by NoImageAvailable** [comment]
Appears to only happen with especially small targets, such as iguanas.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/257d4f7654ab9aab85ae123a589bb278c6ca0c1c Should fix this

**Comment by NoImageAvailable** [comment]
Reopening due to reports of this happening with 0.17.1.1

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/835001affc6a52cd688caef22a5d958516e150b2 Hopefully fixed for good now
