### ISSUE TITLE
Equip new weapon after one-time use one

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#237]
Colonists should re-equip a grenade from inventory after throwing one (assuming they have one available). Same thing for rocket launchers and sidearms.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/d9ec9f9910b2956b71911eb549de344f1cd59aa3 implemented weapon switch after using one-time use weapons. Will prefer weapons of same type, followed by regular weapon switch selection priority (i.e. ranged weapon -> melee weapon -> fists).

**Comment by frenchiveruti** [comment]
Does it follow a "rifle-->pistol-->melee" order?

**Comment by NoImageAvailable** [comment]
It doesn't differentiate between ranged weapon types, no.

**Comment by frenchiveruti** [comment]
Is it possible or too much work? I mean I want to suggest it but don't want to suggest something that just too much work for the little difference it makes.

**Comment by NoImageAvailable** [comment]
In principle its pretty easy to implement. The problem is mostly in getting a scoring method that is robust enough to not do stupid things try to bludgeon someone with a smoke grenade instead of equipping a perfectly good pistol.

The main reason this was never implemented is because as of right now raiders don't spawn with anything more than one ranged and melee sidearm anyways so it never really mattered.

**Comment by frenchiveruti** [comment]
Ah I see, this is intended for AI controlled Pawns and not the player controlled pawns, I asked because I play with all pawns equipped with a light secondary pistol just in case things go bad like loosing an arm haha.
