### ISSUE TITLE
Add execution cut to hunting

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#238]
Currently hunters will down an animal, walk up, shoot it a bunch, reload, waste some more ammo, reload again, then time out on the hunting job and run off to grab a smoke while the animal dies of blood loss and its corpse becomes forbidden.

To avoid this we should simply add an execution toil to JobDriver_HunterHuntCE. Should act same as slaughtering animals so it won't set off boomalopes and such.

**Comment by Maeyanie** [comment]
I also noticed they have a rather low chance of hitting when trying to finish it off, compared to shooting the same animal, moving, at range.

**Comment by NoImageAvailable** [comment]
This has been added in https://github.com/NoImageAvailable/CombatExtended/commit/0e348c43a0305ddd2b70a7a96ffb731d811c2c4b. Additionally, hunters will now maintain optimal range if the target is moving away from them.
