### ISSUE TITLE
Make pawns auto collecting ammo optional or configurable

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#24]
I don't like it when pawns handle stuff by themselves, it always leads to bad situations, for example:

2 rifles, 150 bullets. Pawn A grabs 1 rifle and 150 bullets, pawn B grabs 1 rifle and 0 bullets.

I agree that editing loadouts is tedious and not necessarily clear for new players but it works.
Perhaps the loadout can have an `automatic` mode where pawns would just find any ammo for the equipped weapon.

That still leaves the questions of how many of which ammo to take? I don't know how the AI handles it at the moment but that's probably good enough for most players who aren't control freaks like me. Pawns could also be smart and share ammo but that's prolly very complicated to implement?

**Comment by NoImageAvailable** [comment]
This is part of https://github.com/NoImageAvailable/CombatExtended/issues/10

**Comment by RenaudF** [comment]
I suggest make the ammo optional at the loadout level instead of a global mod option

**Comment by NoImageAvailable** [comment]
Automatic ammo pickup only happens when there is no loadout

**Comment by RenaudF** [comment]
You might still want to use a loadout for your ranged + melee or main + sidearm combo with auto ammo enabled.

**Comment by RenaudF** [comment]
ok moved that comment to #34
