### ISSUE TITLE
Issues With XML-Patching Compatibility

### ISSUE THREAD

**Issue by XeoNovaDan** [NoImageAvailable/CombatExtended#241]
I tried making one of the weapons from my weapon mod (which I promptly isolated as a separate standalone mod for the exact experimentation purposes) compatible with CE using the XML-patch method as shown on the guide to making weapon mods compatible with this mod, following the example as a baseline - but my log gets flooded with red error messages.

From what I've gathered, the actual Patch Operation classes mentioned in the CE XML-patching section don't even exist.

Load order is as follows:
 - Core
 - Combat Extended
 - Repeater Rifle (the gun mod)
 - Repeater Rifle CE (CE patch)

I've attached a ZIP file containing the output log, the standalone weapon, and the CE patch.

It may also be noteworthy that I did add an ammo type too.

[CE XML-Patching Problem Kit.zip](https://github.com/NoImageAvailable/CombatExtended/files/1066162/CE.XML-Patching.Problem.Kit.zip)

**Comment by NoImageAvailable** [comment]
As mentioned in the thread, this was due to a mixup with the documentation being available before release.
