### ISSUE TITLE
"BodyType Undefined" on non-Core animals

### ISSUE THREAD

**Issue by Fregrant** [NoImageAvailable/CombatExtended#245]
Then I click an equipped weapon icon to make a shoot order, and hover the pointer over a non-vanilla animal, I getting a red error in console.

CE returning BodyType Undefined for pawn Devillo45796
Verse.Log:Error(String)
Verse.Log:ErrorOnce(String, Int32)
CombatExtended.CE_Utility:GetCollisionBodyFactors(Pawn)
CombatExtended.CollisionVertical:CalculateHeightRange(Thing, FloatRange&, Single&)
CombatExtended.CollisionVertical:.ctor(Thing)
CombatExtended.Verb_LaunchProjectileCE:CanHitCellFromCellIgnoringRange(IntVec3, IntVec3, Thing, Boolean)
CombatExtended.Verb_LaunchProjectileCE:CanHitFromCellIgnoringRange(IntVec3, LocalTargetInfo, IntVec3&)
CombatExtended.Verb_LaunchProjectileCE:TryFindCEShootLineFromTo(IntVec3, LocalTargetInfo, ShootLine&)
CombatExtended.Verb_LaunchProjectileCE:CanHitTargetFrom(IntVec3, LocalTargetInfo, String&)
CombatExtended.Verb_LaunchProjectileCE:CanHitTarget(LocalTargetInfo, String&)
CombatExtended.Harmony.Harmony_TooltipUtility_ShotCalculationTipString_Patch:Postfix(String&, Thing)
Verse.TooltipUtility:ShotCalculationTipString_Patch1(Thing)
Verse.TooltipGiverList:DispenseAllThingTooltips()
RimWorld.MapInterface:MapInterfaceOnGUI_BeforeMainTabs()
RimWorld.UIRoot_Play:UIRootOnGUI_Patch1(Object)
Verse.Root:OnGUI()

**Comment by NoImageAvailable** [comment]
Mod-added animals need to have their body type specified, otherwise they'll use (likely inappropriate) default values. The error informs you that you have an incompatible animal, it's working as designed.

**Comment by Fregrant** [comment]
Not found any info, patch example please?

**Comment by Fregrant** [comment]
Nvm, looks like I figured it out.

**Comment by NoImageAvailable** [comment]
Added information on this to the wiki
