### ISSUE TITLE
Improve pawns cover search when suppressed

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#25]
In some cases pawns will go run for cover that's way too far, making them easy targets. When suppressed a pawn should look at available cover options and make a random choice weighted by:
1. distance
2. cover quality
3. strategic value (running backward -> not good)

Pawns should also consider lying down where they are and firing back immediately.

**Comment by Thorbane** [comment]
Strategic value would probably need a check on their weapon range.  If they can still hit targets from a spot behind them, why not run there.

**Comment by NoImageAvailable** [comment]
Cover selection is part of https://github.com/NoImageAvailable/CombatExtended/issues/22

Not going to implement hunkered pawns firing back, would require extensive coding changes and runs contrary to the purpose of suppression (it is designed as a crowd control tool, that is a way to *prevent* pawns from shooting.
