### ISSUE TITLE
Colonist Shot Himself

### ISSUE THREAD

**Issue by Duck2101** [NoImageAvailable/CombatExtended#250]
An emu was inside one of my buildings, so I sent a hunt order. My colonist walked up to the emu, point blank, and takes a shot with his pistol, but what happens is the colonist takes the bullet. I am assuming this is a bug that happened due to the fact that bullets now work with hit boxes. The bullet spawned in too close to the colonist hit box, and it caused him to shoot himself.

**Comment by NoImageAvailable** [comment]
Already fixed in current dev build
