### ISSUE TITLE
Strange visual issue.

### ISSUE THREAD

**Issue by Thinereapist** [NoImageAvailable/CombatExtended#251]
When hunter is firing and Visibility of roofs is enabled the visibility flashes off until projectile ends flight.

**Comment by NoImageAvailable** [comment]
Can't reproduce this. What are the exact circumstances this occurs in?

**Comment by Thinereapist** [comment]
I'm working on finding exactly what's causing this issue. Likely not CE.

**Comment by NoImageAvailable** [comment]
Since OP hasn't replied I'm assuming this is fixed, closing
