### ISSUE TITLE
not able to change the ammo type, aim or fire mode in auto turret

### ISSUE THREAD

**Issue by Galvenox** [NoImageAvailable/CombatExtended#252]
I am however still able to hold fire, and when they're loaded, turrets still shoot no problem. here's the log of an error I got when I tried to right-click on Reload button to change the ammo type of a turret. no other reaction whatsoever. turrets that have to be manned to shoot seem to work fine

System.ArgumentException: Value does not fall within the expected range.
  at CombatExtended.Command_Reload.MakeAmmoMenu () [0x00000] in <filename unknown>:0 
  at CombatExtended.Command_Reload.ProcessInput (UnityEngine.Event ev) [0x00000] in <filename unknown>:0 
  at Verse.GizmoGridDrawer.DrawGizmoGrid (IEnumerable`1 gizmos, Single startX, Verse.Gizmo& mouseoverGizmo) [0x00000] in <filename unknown>:0 
  at RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor (IEnumerable`1 selectedObjects) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Log:ErrorOnce(String, Int32)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

**Comment by NoImageAvailable** [comment]
This is a known issue and already resolved in 1.2

**Comment by Galvenox** [comment]
oh, fair enough. I'm using the Steam Workshop version which says it's version 1.1. that explains it. any idea when you'll be able to update the Steam Workshop version?

**Comment by NoImageAvailable** [comment]
1.2 only just now entered internal testing, its not out yet

**Comment by Galvenox** [comment]
found it under Development branch, it's all good. playing it right this moment, I'll let you know if I find any bugs or something, if you're looking for feedback. and thank you for that great mod
