### ISSUE TITLE
Remove ammo requirements from turrets when ammo is turned of in mod settings.

### ISSUE THREAD

**Issue by SneakyGunz** [NoImageAvailable/CombatExtended#255]
I find that I need to deconstruct and rebuild turrets once they are out of ammo (0/200). It would make since to remove the ammo requirement here, as you have with the hand held ranged weapons. Thanks for you time and this wonderful mod.

**Comment by NoImageAvailable** [comment]
Auto-turrets are reloaded by haulers, even with the ammo system disabled.
