### ISSUE TITLE
81 mm shells spawning as vanilla mortar shells

### ISSUE THREAD

**Issue by thatguy1111** [NoImageAvailable/CombatExtended#256]
when i start up the game there are no reported conflicts with mods but whenever i manufacture 81 mm shells they spawn as vanilla shells which i cannot load.

**Comment by NoImageAvailable** [comment]
Just because no errors are thrown doesn't mean its compatible. This is most likely a conflict with some other mod overriding mortar shells, I'd need you to confirm this happens with only CE loaded.

**Comment by NoImageAvailable** [comment]
No reply in over a week, closing
