### ISSUE TITLE
Loading bench problem and opinion.

### ISSUE THREAD

**Issue by JeyukBokKeum** [NoImageAvailable/CombatExtended#258]
problem: I can't make new 8x35mmCharged bullet without CEgun mod. 
I am making gun mods CE compatible, I use some new updated 8x35mm, and i find out that 8x35mm recipe only works with CE gun mod. can you fix this?

I have opinion about loading bench and machining table.
1. Making 90mm flak turret and lmg without advanced firearm research doesn't make sense.  is it bug? or intended?
2. I can't understand how I can make charged shot weapon's bullet without research charge weapon on loading table.

**Comment by NoImageAvailable** [comment]
I have no idea what your problem is, you'll need to be more clear.
