### ISSUE TITLE
Randomise pawn targeting

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#26]
At the moment pawns seem to target the closest target, which often leads to focused fire on a single enemy and micro managing who is firing at who is tedious at best.

Instead pawns should consider all available targets and make a random choice weighted by:
1. distance (fair enough)
2. dangerousness (rocket launcher anyone?) - ok this one is subjective and will be hard to balance.
3. weapon accuracy relative to range

I don't know if pawns already do it but if not they might reconsider target between salvos/shots if it doesn't impact performance too much.

**Comment by NoImageAvailable** [comment]
Targeting will be changed as part of AI overhaul https://github.com/NoImageAvailable/CombatExtended/issues/73
