### ISSUE TITLE
SightsEfficiency of Charge rifle is too low on Dev.ver

### ISSUE THREAD

**Issue by JeyukBokKeum** [NoImageAvailable/CombatExtended#261]
I know Sights Efficiency of guns are changed to 1.0 for iron-sight. But I find charge rifle still have 0.6 efficiency that same as the last release version. 

!-- ========== Charge rifle ========== --

  Operation Class="CombatExtended.PatchOperationMakeGunCECompatible"
    defName>Gun_ChargeRifle</defName
    statBases
      Mass>3.0</Mass
      RangedWeapon_Cooldown>0.36</RangedWeapon_Cooldown
      SightsEfficiency>0.60</SightsEfficiency
      ShotSpread>0.08</ShotSpread
      SwayFactor>1.20</SwayFactor
      Bulk>9.00</Bulk

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/0c692c9061e59e3a230512a77aee143199a3a484 Should fix this. Good catch too, since I was just about to release.
