### ISSUE TITLE
Loading ammo takes priority over emergencies

### ISSUE THREAD

**Issue by Mehni** [NoImageAvailable/CombatExtended#265]
Pawns will reload guns before fighting fires or give emergency treatment.

Reloading guns should probably be a bit lower in the priority Thinktree.

**Comment by NoImageAvailable** [comment]
This is something I've noticed too. Pretty much the first thing that happens upon undrafting is everyone reloads their gun.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/832fa6be0d46c5d9bc06f9fdcf4bc5d925195dde Reloading is now lower in priority than emergency work
