### ISSUE TITLE
i can't make ammo

### ISSUE THREAD

**Issue by slashen1** [NoImageAvailable/CombatExtended#267]
i've tried researching and looking through the god mode, and found nothing and i still can't create ammo.

**Comment by NoImageAvailable** [comment]
Probably a mod conflict, is this reproducable with only CE in your load order?

**Comment by slashen1** [comment]
i don't, know let me check. sorry for the late reply.

**Comment by slashen1** [comment]
it works with ce and core only.

**Comment by slashen1** [comment]
i figured out what mod it was, it's medieval times.
