### ISSUE TITLE
Spread out pawns in raids

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#27]
All pawns currently take the same path and they usually end up sharing all the suppression fire leading to disastrous results. A simple improvement could be made by changing the cost function of the A* algorithm in raid mode to apply negative values to tiles that are near other pawns. This should naturally give pawns an incentive to spread out a bit more, kinda flocking.

**Comment by RenaudF** [comment]
could be of interest
https://ludeon.com/forums/index.php?topic=29194.0

**Comment by NoImageAvailable** [comment]
Should be done as part of https://github.com/NoImageAvailable/CombatExtended/issues/73

Removing this from Release 1.0 milestone since AI overhaul is being pushed into post-1.0 as well.
