### ISSUE TITLE
Hand-Loaded Weapons Should Reload one-by-one [idea]

### ISSUE THREAD

**Issue by XeoNovaDan** [NoImageAvailable/CombatExtended#270]
Title.

**Comment by Alicecomma** [comment]
You'd have warmup -> cooldown -> reload -> repeat OR warmup -> cooldown -> repeat (x8) -> reload -> repeat, and depending on the situation one or the other is better so you'd need to code it such that one or the other is used.

This could be achieved by always loading one-at-a-time, checking for enemies once after a shell is loaded (same tick) then continuing with the reload. E.g a "FailOn" for having visible enemies/hostiles, turning the job into an attack job if some shells are already loaded (nr shells > 1).

**Comment by Alicecomma** [comment]
Feature is currently implemented as bool CompProperties_AmmoUser.reloadOneAtATime. If set to true, the reload adds rounds one at a time. There's some bugs with it (#659) but otherwise the feature's there.
