### ISSUE TITLE
Patched weapons running out of ammo

### ISSUE THREAD

**Issue by Sp0nge** [NoImageAvailable/CombatExtended#272]
Whenever a patched weapon runs out of ammo and no more are in inventory, the weapon vanishes. I just did this over and over with and without Simple Sidearms, since that have been reported to be the issue.

This error can be replicated both with, and without said mod, leaving me to belive this mod is the issue for the cause.

**Comment by NoImageAvailable** [comment]
Are you just running into the out-of-ammo action where colonists put away empty weapons into inventory?

**Comment by Sp0nge** [comment]
No, the weapon completely dissapears, no errorlog either. As far as my testing goes, this happends to patched weapons, ill pastebin what i had added when testing this: https://pastebin.com/n1xm9QmJ

This also happends when a pawn tries to fire a weapon and dont have ammo in inventory. Vanilla weapons goes to inventory as expected, pathed dont.

**Comment by Sp0nge** [comment]
Im a dumb nutsack! Im really sorry for this, ive never done coding before and the error is in my patching! Ive seen people refering to this issue in the past aswell, and its basicly usage of the wrong verbs, making it a one use weapon only ... ofc it wont go into inventory then!
