### ISSUE TITLE
is madeFromStuff but stuff=null

### ISSUE THREAD

**Issue by notfood** [NoImageAvailable/CombatExtended#273]
https://github.com/NoImageAvailable/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs#L176

![image](https://user-images.githubusercontent.com/5370107/27998053-a628f654-64ca-11e7-920c-ed3f865c1176.png)
Whenever a weapon is throwable and it's made of stuff. CE fails to give the thingStuff.

This is a possible fix:
```csharp
var ammoThing = thingToAdd.MadeFromStuff ? ThingMaker.MakeThing (thingToAdd, gun.Stuff) : ThingMaker.MakeThing (thingToAdd);
```

Maybe it's required to check if weapon is throwable as well.

I can't compile CE due to the C#6 features (Linux user), otherwise I would do a PR.

**Comment by NoImageAvailable** [comment]
Added the fix to my local build, should be in the next release (whenever I iron out all the bugs with this new leaning LoS algorithm).

**Comment by NoImageAvailable** [comment]
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/b8b36fd31d954e33cd4c116e0c366007e061c819
