### ISSUE TITLE
[suggestion] Radiers and Tribals need better tactics

### ISSUE THREAD

**Issue by ddnguyen** [NoImageAvailable/CombatExtended#276]
Now with the long range weapons, heavy weapons and explosive weapons they don't have the tactics to overcome a well defended base anymore. It's just a slaughter as they rush into the multiple heavy turrets and grenade launchers. 

I suggest giving them the ability to deploy heavy smoke nades / belts which block all projectile targeting weapons and if possible hides them as well. Also I suggest giving them more one shot RPG or other long range explosive weapons.  Also it would be cool if the pirates raid came as mix some jump pods into the base + sappers from multiple directions.

**Comment by NoImageAvailable** [comment]
This stuff falls under #73
