### ISSUE TITLE
Shooting quick weapons (Pistol) on snapshot doesn't give any experience

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#28]
Since the amount of ticks each warmup takes multiplied by the experience factor is lower than 0.5 it is rounded down and no experience is gained. A quick fix would be to round up all experience gains, however a more permanent solution could consist of giving Mathf.Max(minXpPerShot, xpFromTickMethod), with a new minXpPerShot statDef on each weapon (such that legendary weapons could yield more xp per shot).

**Comment by NoImageAvailable** [comment]
Set minimum shot XP to 1 https://github.com/NoImageAvailable/CombatExtended/commit/82540017bccb7143ed38abc3da6da093e364bdd1
