### ISSUE TITLE
Caravans, Set-Up camp, and Settle not working

### ISSUE THREAD

**Issue by fobillay** [NoImageAvailable/CombatExtended#280]
Im ready to start a new base to the north but unfortunately the caravans are frozen in time and nothing happens with them and they can only be moved around with Developer commands, this freeze also occurs with their rest and nutrition which are not moving at all with them. I get a strange bit of text any time I try to set-up camp that has what looks like english and greek letters thrown together saying: "commandsettlefailotherworldobjectshere" everytime i try the set-up camp command(i have a screenshot but dunno how to post on github). On the de-bug log im seeing a lot of bugs relating to "NulReferenceisnotSetToAnInstanceOfAnObject". So far with my current mod set it has been working inside of the loaded instances of my colony as well when attacking colonies without a hitch, but the caravans are completely bugged.

here are the shared logs before i fire up the save game: https://gist.github.com/977c4c01619e95641d594ee823b92fc2

here are the shared logs after i fire up the save game: https://gist.github.com/HugsLibRecordKeeper/e95d57ea8313a370d93d5a395cefcead

Anyways thanks for your time, i CANNOT go back to vanilla combat after playing this amazing mod, its simply too good.

**Comment by NoImageAvailable** [comment]
From the log it looks like you're using a heavily outdated version.

**Comment by fobillay** [comment]
I took out anything that was out of date, im still getting the same issues

**Comment by NoImageAvailable** [comment]
If you're getting loadout generators you're on CE 1.1, not much more to it

**Comment by fobillay** [comment]
Wasnt sure what you meant until your previous comment, but that fixed it for the most part, still cant setup camp but caravans work again, but its most likely got something to do with their end of the mod, thanks for the help
