### ISSUE TITLE
Stop attacking downed enemies

### ISSUE THREAD

**Issue by Killface1980** [NoImageAvailable/CombatExtended#288]
Pawns keep attacking downed enemies.

**Comment by NoImageAvailable** [comment]
I haven't seen this happen at all, do you happen to have Zombieland installed?

**Comment by jetpack-maniac** [comment]
I have seen this happen only when using a forced attack on manned turrets.  The pawn will continue to shoot at the target until they are dead.

**Comment by Alicecomma** [comment]
I've seen this happen when a group of pawns was shooting a seemingly-downed pawn from nearby. At some point the pawn did become truly downed (with the !-symbol and all) and they stopped shooting.

I suspect it has something to do with downed/hunkering pawns looking like downed ones to the player while not truly being downed for the game.
