### ISSUE TITLE
Reloads should be performed before warm up

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#29]
Most reloading is performed after a warmup is attempted at the moment, which for long warmup weapons means a wasted few seconds. Maybe the JobDrivers could take into account reloading or attempting to start warmup could check for reloading as well.

**Comment by frenchiveruti** [comment]
What about a trigger that sets on after the last round is used?

**Comment by ProfoundDarkness** [comment]
For a minute there I thought this was fixed... pawns will reload before trying to shoot again when they are drafted.  It's on hunting that they don't reload before finishing the aim warmup...

**Comment by ProfoundDarkness** [comment]
Happened on some additional testing opportunities outside of the PR #109 and this seems to be fixed.
