### ISSUE TITLE
Loadout bugs Animal Training/ Taming

### ISSUE THREAD

**Issue by dudeli** [NoImageAvailable/CombatExtended#290]
The loadout settings are bugging aninal training/taming with this nasty "10 jobs in 10 ticks" message.
When you assign a handler a loadout without e.g. only a "any meal" and a knife setup and only got raw meat/veggi food for taming your handler will pickup the food and instantly drops it cuz the loadout prevents holding it, resulting in a loop. 
As this does not happen when the loadout is set to "nothing" im pretty sure thats the reason

e.g. Calderon trying to train my  husky:

Calderon started 10 jobs in 10 ticks. List: (TakeInventory A=Thing_Deer_Meat37952) (WaitMaintainPosture) , (TakeInventory A=Thing_Deer_Meat37952) (WaitMaintainPosture) , (TakeInventory A=Thing_Deer_Meat37952) (WaitMaintainPosture) , (TakeInventory A=Thing_Deer_Meat37952) (WaitMaintainPosture) , and (TakeInventory A=Thing_Deer_Meat37952) (WaitMaintainPosture)  lastJobGiver=, curJob.def=WaitMaintainPosture, curDriver=Verse.AI.JobDriver_WaitMaintainPosture
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by NoImageAvailable** [comment]
Pretty sure you're on the outdated 1.1 release

**Comment by dudeli** [comment]
well latest one steam provided me

**Comment by NoImageAvailable** [comment]
That would explain it then, people have reported conflicts with that mod in the past
