### ISSUE TITLE
Meat has disproportionately high bulk

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#292]
Meat has a bulk of 1.00, despite weighing only 30 grams, and the creation of the meat thingdef is handled by the ThingDefGenerator_Meat class, there is no XML patch.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/66b9c6c17dab650dca49c8765f4af8148a9cb238 Reduced meat bulk to 0.2, same as other raw food
