### ISSUE TITLE
¨Picking up¨ loop

### ISSUE THREAD

**Issue by Fonyat** [NoImageAvailable/CombatExtended#299]
Maybe a CE loadout bug, since it says ¨picking up¨?! 
Refactored Work Priorities is currently disabled and I don´t any other mod messing around with work orders or hauling. 

The bug: one of my pawns is stuck on a loop, shifting rice from one spot to another on the same stockpile, when unassigned for hauling he just stands there doing nothing...

Anyone else experiencing the same?

**Comment by Fonyat** [comment]
Well... some more investigation and, apparently, it´s related to animal handling.

**Comment by Fonyat** [comment]
The problem is between CE and Smarter Food Selection while taming/training animals... disabling SFS fixed it.

**Comment by Mythos** [comment]
Unfortunately I can confirm that, also having CE and SFS installed.

**Comment by jetpack-maniac** [comment]
What food profile are the pawns set to?  I use SFS and haven't noticed this in the newest CE version yet.

**Comment by Mythos** [comment]
Mine had the default profiles, didn't change anything after installation of SFS.
Having VG installed, here they were picking up and immediately dropping Eggplants all the time.

**Comment by jetpack-maniac** [comment]
I don't think it's a SFS conflict, I've had this happen with CE alone before.  It's a loadout issue, animal handlers needs to be set to no loadout or else they will attempt to pick up food and drop it.

For now, set your handler to no loadout and he or she will go about training and taming as per normal.

**Comment by Fonyat** [comment]
Actually both cases will cause issues.
With SFS, even if eating raw food is allowed, rice in my case, the pawn will drop it and try to grab a preferred meal when available. As soon as he drops the rice, the taming/training job kicks in and he grabs it again.
The same happens with CE, unless you have the specific raw food the pawn is trying to use for training in the loadout.
I'm using CE v14c, tried with Any Meal and specific meals... SFS is set to default by now.

**Comment by Fonyat** [comment]
Things are starting to make sense, i'll do some more testing...

**Comment by jetpack-maniac** [comment]
A work around you could use for now is to set the trainer to a loadout and then to anything after he gets the specified loadout.  That at least says micromanaging him or her picking up the loadout in the first place.

**Comment by NoImageAvailable** [comment]
>I don't think it's a SFS conflict, I've had this happen with CE alone before.
Is this on the latest release? There was a bug where sometimes pawns would pick up food in an endless loop but it was fixed several versions ago.

**Comment by Skullywag** [comment]
i have SFS and can confirm having this issue with animal handling and kibble in my case.
