### ISSUE TITLE
Loadout menu invisible

### ISSUE THREAD

**Issue by Crowbarr** [NoImageAvailable/CombatExtended#300]
https://gist.github.com/HugsLibRecordKeeper/0e55c3ae76ad00ac4c7abd1c7b20f7ac

Loadout menu won't seem to work. Cannot create new loadouts, or alter current ones.

First post here, apologises if this is an incorrect way to post.

**Comment by Crowbarr** [comment]
Fixed error. Had to hit spacebar 3 times in the search bar area of the loadout, all loadouts correctly displayed.

**Comment by NoImageAvailable** [comment]
Your log indicates some issue with the Core mod, did you do anything to modify it?

**Comment by NoImageAvailable** [comment]
No reply in over a week, closing
