### ISSUE TITLE
CombatExtended has serious problem on non english user!! plz see this

### ISSUE THREAD

**Issue by totobrother** [NoImageAvailable/CombatExtended#302]
Combat Extended affect on language things.
It make trouble when language mode isn't English.
Like non english mode such as Chinese or Korean or when using "Input free" mod-plz check this mod.
If i use it on Korean mode, It makes so big problem.
First, I can't change any name on plan such as wearing, load and medicine.
And making so serious lag issue when clicking right click or some specific behavior.
I test it 20 times for proving this.
Surely, It not other mod matter, It is matter of combatExtended mod.
plz fix it!....
plz solve non English writing problem and make compatible with "input free" mod

**Comment by NoImageAvailable** [comment]
There currently seems to be some issue with the way the game engine handles XML patches, its not a CE bug per se. I'll see if I can talk to Zorba about it.

**Comment by NoImageAvailable** [comment]
At this point it's pretty clear this isn't gonna get fixed in vanilla and it's out of scope for CE, closing
