### ISSUE TITLE
Make Loadout button and Loadout window bugs

### ISSUE THREAD

**Issue by shakee2** [NoImageAvailable/CombatExtended#304]
First I recommend to make the button visible at all time since it makes it easier to do the loadouts. Currently you need to delete the loadout which is auto-generated by the button to make it visible again on the tab of the selected pawn (behavior may be a bug too...).
1st bug: Loadouts work only for the one which is generated by the button. The Pawn will not heed any other loadout made in the window. So any Copy and so on has no useful function currently or making new loadouts. Selecting a specific loadout and waiting some time, changes nothing, the pawn will not pickup anything. It is different for the auto-generated loadout from the button. Would it be possible to add a button like "Assign Loadout" to selected pawn, which you then may choose from a list? The selected loadout might even be vissible in the Gear tab.
This has been tested with only Hugs and Combat Extended in latest version.

2nd bug: Sometimes, when I have used the "make loadout" button it is impossible for the pawn to keep forced weapons, it always droppes them instantly. But I cannot reliably reproduce this behavior, since I could not check the loadout with that save again...

**Comment by NoImageAvailable** [comment]
I cannot reproduce 1), did you maybe just forget to assign the loadout through the assign tab after making it? The problem with forced weapons is that equipping them will sometimes bypass the hold tracker, it is a known issue.
