### ISSUE TITLE
Your ammos more fireproof then plasteal

### ISSUE THREAD

**Issue by Danielhuren** [NoImageAvailable/CombatExtended#309]
the fire resistance for the ammo is sorta insane this room hit a 1000 degrees and ammo did not catch fire before the plasteal started to get burning i dont know how to code or else i would put inthe pull request but im shure someone else can figure it out

![20170830150939_1](https://user-images.githubusercontent.com/25909932/29893050-65da3ce4-8d96-11e7-833f-a15581eeca4a.jpg)

**Comment by Alicecomma** [comment]
**My view on the issue:**

In RimWorld, things don't spontaneously catch fire from increased temperatures. In fact, Flammability of any ammo is 1 (as the BaseAmmo has Flammability 1 and all other ammo derives from it) so ammo is not fireproof in the sense that fire won't attach to it (which subsequently causes cook-off). I assume that the firefoam popper's filth has to do with your ammo not exploding -- It has filth.allowsFire == false so presumably it will prevent ANY spark from reaching the ammo which to my mind is exactly the purpose of a firefoam popper in a bunker.

Summary: Firefoam popper works as intended in preventing ammo cookoff

**Comment by NoImageAvailable** [comment]
I didn't actually see the firefoam when I first looked at this. As Alicecomma said, firefoam completely prevents things from catching fire and I don't see a problem with this.
