### ISSUE TITLE
Mortar shell recipes

### ISSUE THREAD

**Issue by thomas15v** [NoImageAvailable/CombatExtended#311]
I know this mod is to add another challenge. But I wonder why the mortar shells require 2 components for 5 shells? Not that it isn't maintainable or so. But it is rather painful to manage if you have other mods installed that also require a lot of components (also cassandra smells it when you are out of components and makes so many stuff break that with every trader you lose 4 components just to fix stuff). 

For example I like to stockpile of at least 100 mortar shells (4 stockpiles of 25 shells). What means you need 40 components to create such stockpile. Also if you take in account that if you want to use EMP shells, you can add another 10 components to the list. What makes it 50 components to create the initial stockpile. During a raid I fire 4 mortars (or 5 when dealing with mechanoids) to shred them to pieces. What means I usually fire about 5 a 7 volleys for each mortar. What brings the usage to an average 25 each raid. What is again 10 components. 

I have no idea what other recipe could be used to balance it more, but I think the current recipe is a bit too expensive if you ask me. I rather have 1 component or/and a bit more steel use.

**Comment by NoImageAvailable** [comment]
Mortar shells being expensive is intentional. They're very powerful so the cost is to discourage people from spamming them excessively.
