### ISSUE TITLE
Mortar gunner fires at mechanoids in ancient ruins while unrevealed

### ISSUE THREAD

**Issue by Paragonid** [NoImageAvailable/CombatExtended#317]
Reproducing:
1. Build a mortar on map with ancient ruins and mechanoids inside
2. Man mortar

Result:
Mortar gunner is firing at unrevealed mechanoids immediately.

Expected:
Mortar gunner doesn't know about mechanoids and doesn't auto fire at them

I have bunch of other mods and it could be something else... so it's unconfirmed

**Comment by NoImageAvailable** [comment]
This is caused by the same vanilla bug that prevents the colony naming event. Nothing we can do until the game gets fixed.
