### ISSUE TITLE
Wrong ammo definition for Ruger 10/22, Rimfire Patch

### ISSUE THREAD

**Issue by junkdeck** [NoImageAvailable/CombatExtended#318]
The Rimfire patch erroneously defines the ammo type for the Ruger 10/22 as .45 ACP, when it should be .22LR.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/1636f93827390d5c28351123f2e4cb10fd24b2ea Corrected it
