### ISSUE TITLE
Downed pawns can't be shot

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#32]
There seems to be some issue regarding shooting laying pawns (downed or sleeping). Pawns will shoot straight over them. Especially noticeable when executing downed animals while hunting. Probably an issue with aiming or minimum collision distance.

**Comment by Alicecomma** [comment]
The latest commit "No ammo hunting fail and projectile height/impact overhaul" should have fixed this issue. Please report whether this has fixed the issue in the above scenarios.

**Comment by NoImageAvailable** [comment]
A quick test shows its working properly now. Closing this unless someone can reproduce the issue.
