### ISSUE TITLE
Apparello compatibility?

### ISSUE THREAD

**Issue by GemAye** [NoImageAvailable/CombatExtended#324]
After installing CE  I get this debug message when starting the game.

> XML error: Could not find parent node named "ShieldBase" for node "ThingDef". Full node: <ThingDef ParentName="ShieldBase"><defName>Apparello_Tribalshield</defName><description>Shield made of planks and padding. Used by native tribes in hopes to deflect bullets and to summon the courage of the great 'Shiled-Sheild Téh Gaurdian' A Godly protector of the tribes.</description><label>tribal shield</label><graphicData><texPath>Apparel/Display/MogoShield</texPath><graphicClass>Graphic_Single</graphicClass></graphicData><tradeability>Sellable</tradeability><costStuffCount>15</costStuffCount><stuffCategories><li>Leathery</li><li>Fabric</li></stuffCategories><recipeMaker><workSpeedStat>TailoringSpeed</workSpeedStat><workSkill>Crafting</workSkill><effectWorking>Tailor</effectWorking><soundWorking>Recipe_Tailor</soundWorking><researchPrerequisite>ApparelloTribalwearDesign</researchPrerequisite><recipeUsers><li>ElectricTailoringBench</li><li>HandTailoringBench</li><li>CraftingSpot</li></recipeUsers></recipeMaker><thingCategories><li>Apparel</li></thingCategories><statBases><Mass>0.40</Mass><ArmorRating_Blunt>0.25</ArmorRating_Blunt><ArmorRating_Sharp>0.1</ArmorRating_Sharp><Bulk>8</Bulk><WornBulk>5</WornBulk></statBases><apparel><tags><li>TribalShield</li></tags></apparel><colorGenerator Class="ColorGenerator_StandardApparel" /><equippedStatOffsets><ReloadSpeed>-0.05</ReloadSpeed><MeleeHitChance>-0.05</MeleeHitChance><ShootingAccuracy>-0.05</ShootingAccuracy><AimingAccuracy>-0.05</AimingAccuracy><Suppressability>-0.25</Suppressability><MeleeCritChance>-0.05</MeleeCritChance><MeleeParryChance>1.0</MeleeParryChance></equippedStatOffsets><modExtensions><li Class="CombatExtended.ShieldDefExtension"><shieldCoverage><li>Hands</li><li>Arms</li><li>Shoulders</li><li>Torso</li><li>Neck</li></shieldCoverage></li></modExtensions></ThingDef>
> Verse.Log:Error(String)
> Verse.XmlInheritance:GetBestParentFor(XmlInheritanceNode, String)
> Verse.XmlInheritance:ResolveParentsAndChildNodesLinks()
> Verse.XmlInheritance:Resolve()
> Verse.ModContentPack:LoadDefs(IEnumerable`1)
> Verse.LoadedModManager:LoadAllActiveMods()
> Verse.PlayDataLoader:DoPlayLoad()
> Verse.PlayDataLoader:LoadAllPlayData(Boolean)
> Verse.Root:<Start>m__84E()
> Verse.LongEventHandler:RunEventFromAnotherThread(Action)
> Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__84C()

I had CE loaded at the bottom of the mod list when this bug appeared.

After dropping Apparello 2 to the bottom there's no debug screen showing up but I wonder if Apparello 2 will be working correctly with CE now that I'm loading it last.

**Comment by NoImageAvailable** [comment]
CE should always be loaded before any patched mods, else the patches might not work correctly.
