### ISSUE TITLE
90mm flak gun doesn't reload and shoot again after first round unless manning pawn is drafted and shell in inventory

### ISSUE THREAD

**Issue by Paragonid** [NoImageAvailable/CombatExtended#325]
Pawn mans 90mm flak with empty inventory (no shells). It auto fires on the target which brings flak ammo to 0. Further pawn doesn't reload flak, even if I reman it with him, draft and man, etc unless I have him drafted and having ammo in the inventory in the same time. 

Is this intended? it's too much micromanagement to manually reload like this.

**Comment by NoImageAvailable** [comment]
I can't reproduce this. Are you getting any log errors? Any mods enabled that might interfere with turrets/weapons/pawn AI somehow? Also, a screenshot of your exact setup would be helpful.

**Comment by Paragonid** [comment]
No logs errors as far as I can tell.

Mods which I think can be messing (all loaded before CombatExtended):
Better Pawn Control
Refactored Work Priorities
Defensive positions

[Video recording](https://youtu.be/6RjdQunZeSw)

![Setup screenshot](https://user-images.githubusercontent.com/881361/30885401-ce9cb7e4-a31b-11e7-8671-af389d5a1b7e.png)

**Comment by Paragonid** [comment]
I will retry with them disabled..

**Comment by Paragonid** [comment]
I was playing more and drafted the pawn before manning the flak. It makes pawn reload normally. So it solves my issue, maybe disable manning for undrafted?
