### ISSUE TITLE
Question about supression

### ISSUE THREAD

**Issue by frenchiveruti** [NoImageAvailable/CombatExtended#330]
Hi, I like the suppression mechanic, but I have a question.
Does it take into account pawn level and traits?

1. Lets say a psychotic pawn is shooting, he's a psycho, would he panic when he reaches a threshold?
3. Also, if a pawn is very well covered, and he reaches the point of "running for cover", will he move away from his position anyways? Even if he's behind a granite wall with a hole for shooting?
5. And finally, does it take into account the level of shooting of the pawn? I mean, a lvl 20 shooter should be less prone to panic and get paralized for suppression right?

Thanks!

**Comment by NoImageAvailable** [comment]
The issue tracker is intended for bugs and features, not general questions about the mod. If you want to contact a dev use the forum thread or CE Discord.
