### ISSUE TITLE
Remove the damage stat on gun info screens or make it representative of its current caliber

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#333]
This to prevent bug reports and general confusion of people comparing it to the actual damage dealt by a gun.

```
if (this.<verb>__14.defaultProjectile != null)
{
	this.<projDamage>__15 = this.<verb>__14.defaultProjectile.projectile.damageAmountBase;
	this.$current = new StatDrawEntry(StatCategoryDefOf.Basics, "Damage".Translate(), this.<projDamage>__15.ToString(), 0, string.Empty);
	if (!this.$disposing)
	{
		this.$PC = 15;
	}
	flag = true;
	return true;
}
```
(part of a decompiled IEnumerator<StatDrawEntry> ThingDef.SpecialDisplayStats, showing that "Damage" is added when defaultProjectile != null)
B18:
- Verse.DataAnalysisTableMaker.DoTable_WeaponsRanged() uses defaultProjectile to list "Damage". It is not a use case very important to the average player.
- Verse.PlayLogEntryUtility.RulesForOptionalWeapon(string prefix, ThingDef weaponDef, ThingDef projectileDef) uses defaultProjectile as a fallback method if no projectileDef is given. Not sure when the fallback is called if ever.
- Verse.VerbProperties.AdjustedExpectedMeleeDamage(Verb ownerVerb, Pawn attacker, Thing equipment) is some selection weight for which melee/ranged is better to use as melee. Ranged weapons are awful at melee so it's likely it doesn't matter whether they're picked less than usual.

A17:
- Add a StatWorkerDef and see if it does anything
- Setting defaultProjectile = null in any way
- - ~~Building_TurretGun(CE and vanilla).IsValidTarget, .TryFindNewTarget, .TryStartShootSomething~~ (Fixed in Projectile Arc PR), BuildingProperties.IsMortar and VerbProperties.NeedsLineOfSight check projectileDef.projectile.flyOverhead, meaning turrets are considered a mortar based on their projectileDef which actually isn't used (ideally), and guns need line of sight checks based on whether projectileDef (and not their current ammo) is flyOverhead
- - Verb_LaunchProjectileCE.ProjectileDef returns projectileDef if compAmmo isn't found
- - ~~Verb_LaunchProjectileCE.ShotSpeed sets the shotSpeed to that of projectileDef.projectile.speed, not to the shotSpeed of the current projectile!~~ (Fixed in Projectile Arc PR)
- - ~~AttackTargetFinder.BestAttackTarget aims for machines if projectileDef has DamageDefOf.EMP. It doesn't base this aiming behaviour on the ammo currently loaded~~ (Changed in B18)
- Add dummy projectileDefs to each weapon and set damageAmountBase to match the damage in Caliber (seems like a lot of work)
- Remove this part of the IEnumerable by IL-/harmony magic

**Comment by NoImageAvailable** [comment]
Done https://github.com/NoImageAvailable/CombatExtended/commit/5c4772b6e3c80c583bb0bb655dbe1da20e2e412d
