### ISSUE TITLE
Reusable projectiles

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#342]
After a suggestion on the forums, primitive projectiles (arrows, javelins, etc.) could respawn as ammo after impacting something, allowing recovery of fired projectiles.

**Comment by Alicecomma** [comment]
Suggested way of adding this:

- For the projectile, set ThingDef.projectile.preExplosionSpawnChance some value and ThingDef.projectile.preExplosionSpawnThingDef the ammo of the projectile
- Let CombatExtended.BulletCE.Impact() spawn things pre-explosion if the projectile isn't explosive

Should be added for:

- CombatExtended\Defs\Ammo\Neolithic\Arrows, GreatArrows, Javelins, and SlingBullet.xml
- CombatExtended\Defs\Ammo\Medieval\CrossbowBolts.xml

**Comment by Alicecomma** [comment]
10 stone arrows cost 1 log
10 steel arrows cost 1 log, 1 steel
10 plasteel arrows cost 1 log, 1 plasteel

10 stone sling bullets cost 1 StoneBlock
10 steel sling bullets cost 1 steel
10 plasteel sling bullets cost 1 plasteel

- I'd suggest increasing recovery chance from stone->steel->plasteel. Alternative chance progression could be _the other way around_ such that expensive, damaging ammo is a poor choice for resource investment over time.

- Maybe increase ammo yield per steel (currently 10:1) if neolithic colonies have it this hard (e.g 5.56NATO = 42:1, 9x19Para = 56:1, 12g = 12:1)?

- Lifetime ammo yield per steel is 10 * [1+ x + x^2 + x^3 + .. = 1 / (1 - x) by infinite geometric series (for x < 1, x = preExplosionSpawnChance)]. E.g for x = 0.5 (half chance to recover), lifetime ammo yield per steel is 20. If we have a large chance to recover, say x = 0.9, this is 100. For a low chance, x reaches 10.

**Comment by Alicecomma** [comment]
With the changes introduced in the Projectile Arcs PR (#329), arrows could be spawned a tile before the wall they hit.

As it is, arrows will be spawned as you would expect of the ones spawned in with Dev Mode (on the tile if possible, otherwise 1 tile West/North/East/South -> 1.4 tile North-West/North-East/South-East/South-West -> etc.

**Comment by Alicecomma** [comment]
Complete. PR: #347

**Comment by NoImageAvailable** [comment]
Changing the pila into a javelin would work (why do tribals have pila anyways?). Not a fan of that whole mulching idea though, sounds like micromanagement/crafting hell. 

Adding arrows directly into inventory would have the problem that you'd get situations where you shoot a bow-wielding enemy, add the arrow into his inventory and then he pulls it out and shoots it back at you. Pretty metal but not very realistic.

**Comment by Alicecomma** [comment]
I agree the ideas would add a lot of micro management. Based on the discussion I'd say close the issue upon merging of #351
