### ISSUE TITLE
Lower the cook-off projectile damaging effects

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#344]
Cook-off in real life is a much less lethal event than it is in the game. Minimal armour should completely mitigate cook-off fragment damage.

- Change cookOffProjectile to a much less lethal version (either a low-damage version of the normal projectile or a "Cook-off fragment"). Decrease velocities, decrease damage.
- Filth could be added around the cook-off to drive home that it is more of an inconvenience, not a lethal event.

This change DOES NOT alter the cook-off of mortar shells/grenades! By all means, let their cook-off be extremely damaging.

The change is meant to lower player punishment for keeping ammo stockpiles near the defences.

----

Additionally, cook-off should not start until the projectiles auto-ignite. This means that cook-off should check for environment temperature and attached fire size rather than straight-up damage amount. Furthermore, temperature and fire size should speed up cook-off so a room at 2000 C will have faster cook-off than one at 400 C due to lower activation energy of gunpowder ignition.

**Comment by NoImageAvailable** [comment]
Realism aside, considering the amount of positive feedback the current cook-off mechanic received I don't think nerfing it would go over well with the player base.

**Comment by Alicecomma** [comment]
I agree it might not go over well with some of the player base. Since the changes are rather minor in terms of XML/C#, it could easily be a toggleable option (make all cookoff projectiles one with low speed and minor damage), or, reading the following it could be the default:

Watching streamers/youtubers play CE, they get curious what would happen if their ammo stockpile was set ablaze. The graphical effects of this are quite beautiful and there's lots of destruction of course, which I think plays a huge part in the positive feedback.

On the flip side, there's the same streamers/youtubers reloading their savefile because an explosive landed one wall away from a local ammo storage and the blast radius caused cook-off. There's those who have one of their machinegun pawns killed and their hundreds of projectiles cook off in some way.

I think it's important to ask the player base, because I'm not for nerfing a massive fire destroying the full ammo stockpile and all the mess that comes with it. I'd like to have a stray grenade in a fire fight not cause your machinegunner to die, have their ammo cook off and down/kill most of the drafted pawns nearby.

**Comment by NoImageAvailable** [comment]
So after a random shower thought I figure we can probably implement it this way:
- Add a toggle in the options menu for realistic cook-off
- Put the projectile spawn code of cook-off into an if-block checking this option. 

This way we still get the ammo decrease and visual/sound effects without projectiles spawning at minimum effort. Will look into it today.

**Comment by NoImageAvailable** [comment]
Implemented in https://github.com/NoImageAvailable/CombatExtended/commit/1c2d6ce09718a0aaf83ccba8ef9228e48421054e
