### ISSUE TITLE
Optimize fragmentation code

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#35]
Fragmentation currently causes huge lag spikes as the game struggles to create hundreds of projectiles at once. Need to optimize and/or somehow spread out fragment generation over several ticks to mitigate FPS drop from mortar shells and the like.

**Comment by NoImageAvailable** [comment]
Proposed solutions:

1. Spread fragment spawn over several ticks. Spawning a dummy object that spreads fragments over 5-10 ticks or so would spread the CPU load of the initial impact while being virtually unnoticeable.

2. Change fragmentation to fire singular fragments at pawns in explosion radius with chance based on proximity to explosion center. Throw motes to create fake fragments. Potentially damage trees inside the frag radius by random amount to simulate fragmentation damage.

**Comment by Alicecomma** [comment]
The recent commit https://github.com/NoImageAvailable/CombatExtended/commit/74cdc8a4cad2e6ff9a16529a20a60960dea09329 seems to have reasonable explosion framerates. Please report findings, and if they are still abhorrent we should implement the proposed solution.

**Comment by NoImageAvailable** [comment]
Tested with heavy mortar barrage, FPS drop still present but _significantly_ less than before. Enough that I'll consider this issue closed.
