### ISSUE TITLE
[Github | Suggestion] version number with rimworld version attached.

### ISSUE THREAD

**Issue by frenchiveruti** [NoImageAvailable/CombatExtended#359]
Hi, I've seen that you follow a rather simple versioning like v#.# 
It would be nice if you guys follow a more extensive approach like other modders who add also the Rimworld version to the versioning.
So, now that you are going to release for B18 it would be something like v.B18.1.8  
Thanks, great mod.

**Comment by jaxxa** [comment]
If you do something like this I would advise using the technical Rimworld version number "0.18" instead of B18 so it can stay nice and sequential after Rimworld V 1.0

**Comment by frenchiveruti** [comment]
Yeah that seems a more sensible suggestion.
v 0.18.1.8 and so on.

**Comment by dvalroth** [comment]
The version numbers have been that way for months. Look at the actual file name, not the title of the release.

**Comment by NoImageAvailable** [comment]
> The version numbers have been that way for months. Look at the actual file name, not the title of the release.

 What he said
