### ISSUE TITLE
Rework suppression indicators

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#36]
Current text mote system is very bare-bones and causes screen clutter, especially when combined with combat taunts. Need to make some kind of new indicator for suppressed and hunkering pawns. 

Was thinking maybe something like the exclamation mark on downed pawns but then the problem is how to let new players know what that means? Could add a gizmo similar to ammo indicator showing current suppression buildup but pawn gizmos are already getting cluttered with all the firearms stuff.

**Comment by RenaudF** [comment]
something like a down arrow would be ok for suppression I guess

**Comment by frenchiveruti** [comment]
A red arrow pointing down on the feet of the pawn? Also if possible, maybe make the pawns "shake" a lot, like if they were shivering.

**Comment by Alicecomma** [comment]
In https://github.com/NoImageAvailable/CombatExtended/commit/ba50eade89a2f19e71fdbe0c7f2e9a583eb7f32a a few suppression indicators were added, very WIP. I think that they clutter combat even more, with all the taunts going on, "suppressed" showing up and all pawn names being visible from any distance.

**Comment by NoImageAvailable** [comment]
The idea was for the suppression indicator to replace "suppressed"

**Comment by NoImageAvailable** [comment]
Disabled the "suppressed" text mote and finished up the new motes in https://github.com/NoImageAvailable/CombatExtended/commit/69cff5a85c037a2d03d42dc6f315a9fc2773c5a1
