### ISSUE TITLE
Beta 18 Port

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#361]
Current state of affairs:

- [x] Melee system needs to be adapted to tool format. Armor penetration value needs to be added to tool defs (partially done) ~~and VerbTracker.InitVerbs() needs to be Harmony-patched to initialize CE verbs with the appropriate amount of melee armor penetration as taken from the tool def.~~
- [x] Melee weapon penetration stat needs to be refactored into a multiplier.
- [x] Armor system must be adapted to above two changes. Currently differentiates between melee weapons and natural melee verbs, now only the later is needed.
- [x] Verb_MeleeAttackCE might need refactors to bring it in line with vanilla verb.
- [x] Combat log triggers need to be integrated into CE verbs.
- [x] Harmony_FloatMenuMakerMap.Modify_ForceWear() is currently broken and needs fixing (branchLabel is null)
- [x] Work on issue #209 needs to be finished up.
- [x] Several melee-related stats need to be refactored as pacifists now have disabled combat stats.
- [x] Custom CE stats for armor penetration need adapting to tool format.
- [x] Crafting materials patch appears dysfunctional, nonsensical weapon/armor stuffs are possible again (e.g. golden helmet)

**Comment by ShazamKnight** [comment]
Any estimate on when this will be finished?

**Comment by oleduc** [comment]
@NoImageAvailable So fixing Harmony_FloatMenuMakerMap.Modify_ForceWear is the only thing still holding up a realease?

Is anyone currently working on this? If not, it would be really helpful if someone could give me a bit of context on Harmony patches and this specific function.

**Comment by NoImageAvailable** [comment]
All tasks finished as of https://github.com/NoImageAvailable/CombatExtended/commit/f8152445468925fb67f8b349040946d30b83b0fb
