### ISSUE TITLE
CE weapons do not register as ranged weapons for hunters

### ISSUE THREAD

**Issue by Harambe001** [NoImageAvailable/CombatExtended#364]
Makes it impossible for pawns to hunt. They do register as ranged weapons for brawlers though.

The problem seems to be with the HasHuntingWeapon function. It checks whether the pawn's primary equipment is a weapon with a range greater than 0 AND whether the weapon does damage. The damage part is probably what's causing the bug.

I've tried to make it so the function always returns true, for testing purposes, but failed. Don't really know how to use harmony properly.

This is on the newest b18 branch.

**Comment by Lunax-x** [comment]
I confirm, happens except one weapon: revolver which is vanilla for some reason and doesnt use ammo.

**Comment by NoImageAvailable** [comment]
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/8754d24eb9d9aecf89242bcdb492bb9f6c1d5f31
