### ISSUE TITLE
Crop functions in Def_Extensions use incorrect pixel indexing

### ISSUE THREAD

**Issue by FluffierThanThou** [NoImageAvailable/CombatExtended#365]
I was looking around for inspiration on your Cropping functions (considering you actually got it to work), when I realised you have a mistake.

From https://docs.unity3d.com/ScriptReference/Texture2D.GetPixels.html;

> The returned array is a flattened 2D array, where pixels are laid out left to right, **bottom to top** (i.e. row after row). 

Your cropping functions are assuming that pixels are laid out left to right, *top to bottom*.

**Comment by NoImageAvailable** [comment]
Alistaire assures me this bug doesn't actually affect anything in-game and I ~~am too lazy to double check~~ have the fullest confidence in his word, so assigning this as low priority.

**Comment by Karel-Kroeze** [comment]
Fair enough. I seem to recall you're using it to compute cover height when it's not explicitly set. As long as you're assuming the item starts at ground level and using this logic to calculate height, it shouldn't make any difference. If you're using this to get a distance to the upper edge, you're getting the distance to the lower edge instead, which may screw up cover height calculations.

**Comment by Alicecomma** [comment]
Implemented methods which use the output from the cropping stuff just look at the difference in pixel Y position. Crop() isn't used. In my testing I could see that something was screwed up with the cropping, so it must have been this issue.

**Comment by Alicecomma** [comment]
Fix consists of doing the following to CropVertical:

- ```heightRange.min++;``` => ```heightRange.max--;```
- ```heightRange.max--;``` => ```heightRange.min++;```
