### ISSUE TITLE
A18: Pawns not using melee weapons in combat

### ISSUE THREAD

**Issue by rshackleton** [NoImageAvailable/CombatExtended#369]
Currently pawns aren't using equipped melee weapons in combat.

Ref #361

**Comment by rshackleton** [comment]
Appears the melee weapons have the correct verbs to allow them to be used in combat.

![image](https://user-images.githubusercontent.com/13448395/33910504-df5733e6-df86-11e7-909d-23c5eb24dcf9.png)

**Comment by rshackleton** [comment]
The likely culprit here:

![image](https://user-images.githubusercontent.com/13448395/33910532-f3f240a2-df86-11e7-8f70-c5f0e4a5aba5.png)

The numbers after the verbs are the "cachedSelectionWeight" values, the melee weapons have a value of 0 and therefore won't be selected.

Need to look into why these values are set to 0.

**Comment by rshackleton** [comment]
This issue is due to the pawn reporting zero efficiency with the weapon.

![image](https://user-images.githubusercontent.com/13448395/33912668-b1db62fe-df8e-11e7-82ee-637e2e7c3019.png)

The weapon tools reference BodyPartGroup defs (`linkedBodyPartsGroup`):

```xml
<Operation Class="PatchOperationReplace">
	<xpath>*/ThingDef[defName="MeleeWeapon_Knife"]/tools</xpath>
	<value>
		<tools>
			<li Class="CombatExtended.ToolCE">
				<label>handle</label>
				<capacities>
					<li>Blunt</li>
				</capacities>
				<power>6</power>
				<cooldownTime>0.83</cooldownTime>
				<armorPenetration>0.087</armorPenetration>
				<linkedBodyPartsGroup>Handle</linkedBodyPartsGroup>
			</li>
			<li Class="CombatExtended.ToolCE">
				<label>blade</label>
				<capacities>
					<li>Cut</li>
				</capacities>
				<power>9</power>
				<cooldownTime>0.83</cooldownTime>
				<armorPenetration>0.107</armorPenetration>
				<linkedBodyPartsGroup>Blade</linkedBodyPartsGroup>
			</li>
			<li Class="CombatExtended.ToolCE">
				<label>point</label>
				<capacities>
					<li>Stab</li>
				</capacities>
				<power>12</power>
				<cooldownTime>0.83</cooldownTime>
				<commonality>1.5</commonality>
				<armorPenetration>0.241</armorPenetration>
				<linkedBodyPartsGroup>Point</linkedBodyPartsGroup>
			</li>
		</tools>
	</value>
</Operation>
```

The pawn doesn't have any body parts in that group and so the part count is 0, this results in the part efficiency returning 0.

Not sure what the correct fix is for this as I don't know what the `linkedBodyPartsGroup` values are used for.

**Comment by rshackleton** [comment]
Validated by commenting out the `<linkedBodyPartsGroup />` elements and starting melee combat:

![image](https://user-images.githubusercontent.com/13448395/33912996-ed9c04fa-df8f-11e7-8f3e-a9c49a8b2818.png)

**Comment by rshackleton** [comment]
The code with the logging is here: https://github.com/rshackleton/CombatExtended/tree/melee-bug

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/75fa9ee1f772f0a9660bb502ef024336fc33f36d
