### ISSUE TITLE
Change starting ammo to revolver ammo, not autopistol ammo

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#373]
Discord: [4:57 AM] Tekuki: u guys need to chance the starting ammo to the ammo needed for the revolver and not the auto pistol

**Comment by NoImageAvailable** [comment]
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/2e0d67e67230b39a639338ba8432fe58cd3fcca6
