### ISSUE TITLE
Strange error thrown at seemingly regular basis

### ISSUE THREAD

**Issue by Lurmey** [NoImageAvailable/CombatExtended#378]
It seems to have something to do with equipping weaponry. None of my colonists should be attempting to equip anything and they don't have any loadouts yet. Haven't seen this particular error reported so I thought I'd just leave this here. I do have RT's Weapons and a rushed and untested CERT patch so it could be an error related to that. Not sure, maybe someone here can confirm.

StatRequest for null def.
Verse.Log:Error(String)
RimWorld.StatRequest:For(BuildableDef, ThingDef, QualityCategory)
RimWorld.StatWorker:GetValueAbstract(BuildableDef, ThingDef)
RimWorld.StatExtension:GetStatValueAbstract(BuildableDef, StatDef, ThingDef)
CombatExtended.JobGiver_TakeAndEquip:GetPriorityWork(Pawn)
CombatExtended.JobGiver_TakeAndEquip:TryGiveJob(Pawn)
Verse.AI.ThinkNode_JobGiver:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextConstantThinkTreeJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
TickMultiThread.SpecialInjector_TickMultiThreadDetour3:_DoSingleTick(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Here's the full log, please ignore the errors in there to do with RFoW and Architect Icons: https://gist.github.com/939bc490018e784a49ed0e676004e2e3

**Comment by Alicecomma** [comment]
Cause:

```float currentAmmoBulk = primaryammouser.CurrentAmmo.GetStatValueAbstract(CE_StatDefOf.Bulk);```

CurrentAmmo returns null if HasAmmo is false or if currentAmmoInt is null. GetStatValueAbstract expects CurrentAmmo to be non-null.

Solution:

```float weightProjectileRatio = Mathf.RoundToInt(((compammo.capacityBulk - compammo.currentBulk) / 1.5f) / currentAmmoBulk);```

Give weightProjectileRatio a different value if CurrentAmmo is null - I don't understand this part of the code very well, but with that change the error should at least disappear.

**Comment by NoImageAvailable** [comment]
Should be fixed now
