### ISSUE TITLE
Minigun burstShotCount=300, centipedes instagib

### ISSUE THREAD

**Issue by rwtesting** [NoImageAvailable/CombatExtended#379]
Is the patch for the core minigun correct?  burstShotCount is set to 300.

I spawned a centipede to test something, and it instagibbed anything that it shot (accompanied by associated combat tab spam).  The ammo count in its inventory also didn't appear to decrease after shooting.

**Comment by NoImageAvailable** [comment]
Working as designed. Ammo decreases on reload, which happens every other burst.

CE Centipedes are designed as light combat vehicles, they pack way more armor and firepower than any foot soldier and require players to adapt their tactics.
