### ISSUE TITLE
My screen flashes when I am using this mod.

### ISSUE THREAD

**Issue by ChristianO0214** [NoImageAvailable/CombatExtended#380]
When I am using this mod my screen occasional flashes between a black screen and the game, it does not make the game impossible to use, but it's kinda bothersome, I assume it has something to do with the pixels, but a Pleb such as myself wouldn't be sure.

**Comment by NoImageAvailable** [comment]
Can't really make anything from that description and never heard of anything similar to this. That and I really doubt CE could be causing any graphical glitches of that type. I'm assuming its something with your setup/system rather than CE.

**Comment by Alicecomma** [comment]
The bug may occur whenever LongEventHandler is called during gameplay.

**Comment by ChristianO0214** [comment]
@Alicecomma How would I fix that, is that a setting or another mod?
