### ISSUE TITLE
A18 : Pawn destination reservation manager failed to clean up properly

### ISSUE THREAD

**Issue by biorcsman** [NoImageAvailable/CombatExtended#383]
> Pawn destination reservation manager failed to clean up properly; Loreen/RunForCover (Job_1145) A=(218, 0, 186)/RunForCover still reserving (218, 0, 186)
Verse.Log:Error(String)
Verse.Log:ErrorOnce(String, Int32)
Verse.Pawn:VerifyReservations()
Verse.AI.Pawn_JobTracker:CleanupCurrentJob(JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.JobDriver:EndJobWith(JobCondition)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:TryEnterNextPathCell()
Verse.AI.Pawn_PathFollower:PatherTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

This log pops up everytime when a pawn gets suppressed.

**Comment by Alicecomma** [comment]
Should be fixed in #397
