### ISSUE TITLE
Overhaul medical system

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#39]
Overhaul chance for scarring and infections. Should account for wound severity, layer (i.e. internal wounds have higher chance for infection/scarring), treatment quality, medicine used and time until treated. Ideally getting your arm almost shot off should be almost guaranteed to scar with no/poor treatment and while being much more limited with high quality treatment.

In addition to the above, allow for Glitterworld meds to be used to surgically reduce/remove scarring. Add painkillers as a low-tech solution to pain induced by scars.

RNG on raider incapacitate should be removed. Increase bleed rates to compensate. 

Consider adding some kind of first aid mechanics for wounded colonists to be treated in the field, e.g. if drafted pawn has doctoring enabled add float menu option "Perform field surgery" using medicine from inventory.

**Comment by frenchiveruti** [comment]
On the same way of reducing RNG, something against the plain stupid chance of a doctor amputating a head when he's operating a leg, I get it if he is just level 0 on medicine, but unbearable if it's a level 11 doctor where the tip of the skill reads "master".

**Comment by NoImageAvailable** [comment]
I wouldn't worry about the surgery balance right now. Its an issue that's been addressed by multiple other mods as well as A17 so its not worth the time to fix it unless A17 comes out and turns out to still be broken.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/69cff5a85c037a2d03d42dc6f315a9fc2773c5a1 disables the RNG on death.

**Comment by NoImageAvailable** [comment]
Rebalanced bleed, scarring and infection rates as part of https://github.com/NoImageAvailable/CombatExtended/commit/32fb2cd1b3692fcddfbeef5c21d0086b7436db7f

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/f6eb582018f7524594c366111e543e49c4a68249 adds the option to surgically reduce scars using Glitterworld medicine.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/0d37468ea8dff349678d842ee41eb43fffaf5b90 introduces the option to stabilize bleeding wounds with medicine

https://github.com/NoImageAvailable/CombatExtended/commit/a3b49885e3abfb90b4cef24a8636fdeab6befbaf adds two different painkillers with a flat pain offset to remove scar mood debuffs.

With that everything on the feature list has been implemented and is ready for balance testing.
