### ISSUE TITLE
Reloading weapon interrupts hunting

### ISSUE THREAD

**Issue by Lurmey** [NoImageAvailable/CombatExtended#399]
Whenever my hunter kills an animal they promptly reload their rifle but then go on to just do another job instead of hauling back their kill like they normally would do. Beta 18 now allows pawns to have a queue of jobs, this should be used to allow a pawn to reload and have the hunting job continue afterwards, via the queue.

Probably unrelated: I also have a mod called "While You're Up" which makes pawns do "opportunistic hauling"; when they finish a job, they search around for nearby hauling jobs that need to go near to the destination of their next job. For some reason, this doesn't work when hunting, though that may just be because my hunter's next job was too far away from the butchery to be eligible for opportunistic hauling. Not sure if it's in any way conflicting with CE's reloading, probably not, but may be worth looking into.

**Comment by NoImageAvailable** [comment]
Job queues have been a thing since long before B18 and CE is already using them. Unless they kill the animal on literally their last shot they're stopping hunting to reload, they're reloading because they stopped hunting. Most likely someone half the map away reserved the corpse for a haul job before the hunter, canceling the hunting job.

**Comment by NoImageAvailable** [comment]
Apparently the fix for #244 was causing this. Reverting to the previous code as the other bug is much more minor compared to this one.

**Comment by Lurmey** [comment]
I wasn't aware that job queues were around before B18 as it's the first version that I've seen and used the ability to hold shift to queue up multiple jobs for a colonist. Though, if the hunter had been queuing the hauling job after reloading then it would say in their text box in the bottom left when selecting them, which it didn't, and that would also prevent other colonists from hauling the corpse as it'd be reserved already. Perhaps there's an old queueing feature that CE is using? Only you would know, I can only guess. Thank you for fixing this, you're doing a mighty fine job updating CE!
