### ISSUE TITLE
Weapons from other mods ineffective.

### ISSUE THREAD

**Issue by Rufert** [NoImageAvailable/CombatExtended#425]
Specifically Medieval times, I've disabled ammo in combat extended since it doesn't work with it that mod anyway, to just retain the melee aspect. However any ranged weapon from that mod will fire normally, the projectile will stop the pawn it hits(resetting it back to previous square as if attacked) but it will do no damage.

**Comment by NoImageAvailable** [comment]
This is the result from running incompatible weapon mods, refer to the forum post's section on compatibility.

**Comment by Alicecomma** [comment]
Just want to say this error is actually due to the following:

- def.weaponTags.Contains("TurretGun") was called before checking whether def.weaponTags exists.
