### ISSUE TITLE
Two Muffalos from a trade caravan stuck around after the rest left...

### ISSUE THREAD

**Issue by Lurmey** [NoImageAvailable/CombatExtended#430]
They were completely frozen, tiredness and food didn't seem to be going down, and they had loot on them. Logically, I used dev mode to down them to investigate. Expecting them to spill all their goods out onto the floor, they kept most of it in their inventories and some errors came up each time I downed one of them. Stripping them gives errors and sometimes they give the item out. One of them dropped 400 .50 BMG (AP-I) cartridges when it was downed and the other, after stripping it, dropped 1500 silver.

https://gist.github.com/546c7a681c73683681b47a703d3bb193

The muffalos
![Muffalos](https://user-images.githubusercontent.com/27971893/34660058-28d515a0-f437-11e7-8ba7-93cd738b09a7.PNG)
Before stripping...
![Before](https://user-images.githubusercontent.com/27971893/34660070-4df22fbc-f437-11e7-9258-b09935e4970f.png)
After stripping...
![After](https://user-images.githubusercontent.com/27971893/34660080-74140b16-f437-11e7-80ed-9f5ca0c2066e.png)

Though sometimes, they didn't drop anything...

**Comment by Lurmey** [comment]
They're also not bleeding out...

**Comment by NoImageAvailable** [comment]
Death Rattle has a known bug where pawns fail to die properly. Beyond that, the majority of errors in that log are from other mods.

**Comment by Lurmey** [comment]
There are some Null Ref Exceptions in there to do with CE that I saw, which prompted me to send it here. Any idea what else could be causing this?

**Comment by Lurmey** [comment]
Update: Removed Death Rattle, made no difference. Some errors appeared due to Death Rattle having been removed but the muffalos didn't change. Killed them using dev mode, tons of errors spammed the console while one was dead and the other was still downed until I killed the other and they stopped. Both spilled out all the items that had disappeared when stripping them. 
![Two dead muffalo](https://user-images.githubusercontent.com/27971893/34694769-34d2e25e-f4c0-11e7-94e7-103b07a20090.png)

https://gist.github.com/09adab60d4867d6b3558c011ace81bf3

While this whole thing may not have much to do with CE, there are certainly some errors in there that reference this mod and I may aswell provide some closure.

From what I can see, there are certainly some issues with drawing the KPV and Flak turret that one of the muffalos was holding. Are those part of CE or RT's Weapons? I forget. This issue may be caused by the botched version of CERT I'm using that was a rushed and untested.

**Comment by NoImageAvailable** [comment]
Simply removing the mod and reloading after the muffalo are already in the bad state wouldn't fix it. You'd need to be able to consistently reproduce the bug, then test it with or without Death Rattle to 100% confirm it. Unfortunately any errors or strange behavior after that is not very meaningful because these things tend to cascade out and are likely just resulting from reaching the bad state in the first place.

**Comment by Lurmey** [comment]
I'm almost certain Death Rattle has little to do with it now. Using dev mode to destroy those two items stopped the NullReferenceExceptions related to them as the game no longer needed to try and render them. I believe those errors specifically are caused by the quick and dirty CERT patch that I'm using.

I may run a quick test on a new save to see if, without CERT or RT's Weapons, the KPV and Flak turret will work as they should.

I apologise for wasting your time with this, NoImageAvailable, because I'm pretty certain now that it's simply caused by the CERT patch I'm using as it was rushed and untested due to the author not wanting to continue support. If this is indeed the case, there's nothing you can do to help, unfortunately, so I apologise.

**Comment by rwpsychology** [comment]
Death Rattle doesn't have any known bugs. It's essentially a single-method Harmony postfix. Your problems with people not dying are coming from somewhere else.

**Comment by Lurmey** [comment]
I wonder what in my mod list could have caused this, though?
