### ISSUE TITLE
Explosion.CE error

### ISSUE THREAD

**Issue by sauerkrau5** [NoImageAvailable/CombatExtended#434]
Could not find a type named CombatExtended.ExplosinCE

That's the red text in my error log.

**Comment by NoImageAvailable** [comment]
Gonna need more details than that. Can you upload your mod list and full output_log.txt?

**Comment by thalur-ksp** [comment]
I'm seeing the same issue on startup using a fresh install and CE as the only mod.
[output_log.txt](https://github.com/NoImageAvailable/CombatExtended/files/1690394/output_log.txt)

**Comment by NoImageAvailable** [comment]
There are no errors in that log though?

**Comment by thalur-ksp** [comment]
Well, there is definitely an error when I start the game:
![ce startup error](https://user-images.githubusercontent.com/20213923/35750306-72e806c4-084c-11e8-92f0-4f137b181c0c.png)

**Comment by thalur-ksp** [comment]
Ah, I think I may know what the problem is: I haven't rebuilt the dll.
