### ISSUE TITLE
Shotgun spread ludicrously wide.

### ISSUE THREAD

**Issue by perkinslr** [NoImageAvailable/CombatExtended#439]
The current spread value (`spreadMult`) for shotguns is wrong, by about a factor of 10.  General rule of thumb is buckshot spreads about 1" per yard (in practice, it's often less with modern firearms and modern ammunition).  That is 1" per 36", or 1 tile wide, at 36 tiles out.  Given that the shotgun range is limited to 15 tiles, it should not be over 1 tile wide at max range.  

Birdshot spreads more, and varies more based on the particulars of the firearm, but still no where near what CE has it spread.  Ballpark figure puts number 6 shot at about double the spread of #00 buck, or 1 tile wide at 18 tiles out.  Cutting the `spreadMult` figure by 10 in `12Gauge.xml` for buckshot _looks_ about right, and double that for birdshot (1.78 and 2.56), but someone who knows how the numbers work internally should probably figure out what the 'right' numbers would be.  As is, shotguns are more dangerous to your allies than grenades or rockets.

**Comment by NoImageAvailable** [comment]
CE assumes a scale of 1 cell = 5 meters for range

**Comment by perkinslr** [comment]
So, knowing the scale is 1 cell is 5 meters, I did some digging to figure out how the mechanics work, and some math.  

A 'normal quality' shotgun has a base spread of 0.14°, which is then multiplied by the `spreadMult` for the ammunition used.  In the case of buckshot, the multiplier is 17.8, giving a final spread value of 2.492°.  Since that is the angle off the centre line, for any given shot, the actual spread rate (left most vs right most pellet) is twice that, or 4.984°.  At 80 meters, this turns into a 7 meter spread, or 1.4 cells.  Shooting a wall at max range, that's roughly what is seen, most pellets impact one wall segment, and a few impact the next one over.  

At 1" per yard, 80 meters should spread to 87", or 2.22 meters.  That would be 0.44 cells, at max range.  Working backwards, the actual spread should be 1.592°.  The spread off the centre is half that, or 0.796°, for a `spreadMult` of 5.68.
In practice, the buckshot probably doesn't matter too much, since the difference between half a cell and 1.4 cells isn't too huge, you'll hit the target and maybe a cell next to the target either way.

The birdshot is where things are way off.  The `spreadMult` is 71.4.  This gives a final spread of 9.996°, and an actual spread of 19.992°.  This turns into a cloud 27 meters across at 80 meters out, or 5.47 cells wide.  Even if we assume the spread is 4 times that of buckshot, which is a high estimate, the total spread at 80 meters is 8.88, or 1.7 cells.  This gives an actual spread of 6.38°, a spread rate of 3.19°, and a `spreadMult` of 22.7.  And again, 4x the spread is a high estimate, a better value would be in the 11-17 range.  

The limiting factor on birdshot range will be air resistance slowing the pellets down, but this affects all the pellets essentially uniformly.  Even lateral wind will affect the whole cloud, not substantially increasing the spread.

**Comment by Alicecomma** [comment]
So the suggested fix is to set spreadMult of birdshot to 11-17?
