### ISSUE TITLE
Revolver and pistol range is short.

### ISSUE THREAD

**Issue by perkinslr** [NoImageAvailable/CombatExtended#440]
The autopistol and revolver both have a range of 12.  This is much shorter than seems reasonable.  For comparison, grenades have a range of 10, and short bows have a range of 28.  The machine pistol has a range of 20.  At first, I was going to suggest just bumping the range on the revolver to 24, and on the autopistol to 22, but seeing that the short bow range is 28...  I'm not sure what to suggest to bring them properly in line with each other.  The LMG and sniper rifle have a range of 75, and are generally considered effective to somewhere around 300 yards.  This gives a rough figure of 25 squares per 100 yards.  Of course, they are capable of shooting much farther than that, but the groupings go from 3" to considerably larger, and on the other end, we can't really shorten the grenade distance much.  

A standard 6" barrel .44 magnum has an effective range in the neighbourhood of 100 yards, a .45 ACP somewhere in the 50-100 yard range.  Bows vary a lot, based on the bow, the arrows, and the shooter, but for a short bow, 50 yards is pushing it.  

If the bows range were reduced to 12, 18, and 20 for the shortbow, recurve, and great bow; the autopistol increased to 18, and the revolver increased to 22, I think it would bring them more or less in line with the rifles, and each other.

**Comment by NoImageAvailable** [comment]
Pistols are using an effective range of about 50m with a scale of (roughly) 1 cell = 5m. Ingame they end up being able to shoot at room distance which is also where they would be effective IRL. I find your claim of 100yrd effective range rather dubious.

**Comment by perkinslr** [comment]
Okay, 1 cell = 5m changes the numbers a bit, but doesn't resolve the underlying issue.  The autopistol range is 12, or 60 meters, fair enough.  The grenade range is 10, or 50 meters.  The US military generally considers the maximum range of a grenade throw 35 meters, or 7 cells.  Meanwhile, the shortbow has a range of 28 cells, or 140m.  For reference, the Olympic archery competition (with recurve bows) is 70m, or 14 cells.  How much less range shortbows should have is not completely clear, but it certainly shouldn't be over 14 cells.  

Since the blast radius on the grenade is about 3 cells (1 cell deadly, shrapnel to about 3), that means a grenadier can usually hit a pistolero with a grenade before the gunman can even start shooting.  

Now, for the range on pistols...  The autopistol shoots .45 ACP, which is a fairly slow round (800-900 fps).  If it's sighted in at 50yards, it will have a drop around 10" at 100 yards.  The machine pistol shoots 9x19 Para, which has a drop of about 6" at 100 yards.  The revolver shoots .44 magnum, which has a drop less than 4" at 100 yards.  The .44 also has a slightly higher velocity, and due to the higher mass of the bullet, maintains that velocity lead for at least 500 yards.  Based on ballistics, the .44 magnum has an effective range at least equal to the machine pistol.  If they're sighted in at 100 yards, the .44 is 2" high at 60 yards.  

Assuming the lethal area on the target is 4" in diameter, this means 0-110yards (0-100m) is point blank range with a .44.  The machine pistol, sighted in to 100yards, is point blank from 0-30, and then again from 80-110.  From 30-80, lining the sight on the centre of the lethal area will result in hits too high.  

So, nothing in the weapon ballistics to make shooting at 100 meters with the revolver impractical.  If the effective range is shorter than that, it is a limitation of the shooter, or of the particular firearm.  But the weapon range in CE has nothing to do with the weapon itself.  Instead, it is a limit on how far away a pawn is willing to pull the trigger.  At shooting skill 1, a pawn with a revolver will hit the target at range 20 about 1/6 times, with the spread +/- 3 cells.  At skill 10, this improves to about 3/6, +/- 2 cells, and at skill 15, 4/6, +/- 1 cell.  This seems more than good enough to justify spending the ammunition, and remember, the goal may not be to actually hit the enemy pawn.  If he has friends, you'd generally be happy hitting any of them, and even if he doesn't, making them duck their heads is still good enough to make your friends' advance a little safer.

Obviously, if you set it too high, the AI will stop advancing far outside of the point where the weapon is actually effective, and get massacred by longer ranged weapons.  If you set it too low, you create the perverse scenario, where a character with a worse shooting skill is more likely to suppress the enemy, since they can shoot at the ground halfway out and will miss high more often than the skilled shooter.  

I think the proper solution would be to scale the weapon AI range with shooting skill, and probably with firing mode, since that would let the AI keep advancing until that particular shooter has a decent chance of landing hits, without artificially limiting the range drastically for skilled shooters.

**Comment by Alicecomma** [comment]
Related to #55
