### ISSUE TITLE
Bugged Mechanoids

### ISSUE THREAD

**Issue by SStirling93** [NoImageAvailable/CombatExtended#442]
![20180204152421_1](https://user-images.githubusercontent.com/4412765/35774623-bd61506e-09c0-11e8-8635-82607b313a86.jpg)
![20180204152423_1](https://user-images.githubusercontent.com/4412765/35774624-bd967370-09c0-11e8-8428-dddbb86e3664.jpg)
![20180204152441_1](https://user-images.githubusercontent.com/4412765/35774625-bdc97a40-09c0-11e8-80e9-ba8d10d59557.jpg)

Not sure if you're aware or not but the Mechanoids are not start combat unless the player attacks first and even when they do start to fight, they do not use their weapons.

These errors are shown in the pics.

**Comment by NoImageAvailable** [comment]
Already fixed in current dev build
