### ISSUE TITLE
Allow equipping cloth disregarding Mass

### ISSUE THREAD

**Issue by Paragonid** [NoImageAvailable/CombatExtended#443]
My pawn is dying from cold, he forgot to wear a jacket. He would be able in typical conditions, but not he is hurt and his max mass decreased, so he refuses to pick up the jacket to stop dying from cold. There's no way to equip it with another pawn, so I believe it should be allowed.

![image](https://user-images.githubusercontent.com/881361/35775412-251def0a-0999-11e8-967f-a2b04e114c52.png)

**Comment by NoImageAvailable** [comment]
Couldn't you just unequip the composite vest?

**Comment by Paragonid** [comment]
Possibly, I didn't try, I have presumed if I can not unequip one, I won't be any. I'll test
