### ISSUE TITLE
Targeted internal attacks ignore Armour Rating

### ISSUE THREAD

**Issue by XeoNovaDan** [NoImageAvailable/CombatExtended#446]
Enter naked guy with wooden shiv, and guy suited up in a full set of legendary power armour. Wooden shiv shouldn't stand a chance against armour since armour has a sharp armour rating of 1.04 and wooden shiv has an armour penetration value of 0.06 on its stab attack.

However, wooden shiv can still deal the full amount of damage to the power armour user when targeting internals such as the pelvis. Power armour doesn't take any damage either, further implying that it's being completely factored out.

Edit: This seems to only be an issue with melee combat; ranged works as normal from some testing.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/7ce759585b1f6dbbb654b1481f7900affd811a7e Fixed
