### ISSUE TITLE
Loading bench doesn't update on changing ammo system

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#45]
Loading bench recipes are dynamically enabled/disabled on game load. Right now you can change the enable ammo setting ingame but the loading bench won't update until next game start. Need to make it update every time the setting is changed.

**Comment by Alicecomma** [comment]
In Rimfire this is handled by the following method:
```
public static void ApplyCraftability(bool shouldBeCraftable)
{
	IEnumerable<ThingDef> list = FuzzyGunList.cacheParentList.Where(x => x.recipeMaker != null && !x.recipeMaker.recipeUsers.NullOrEmpty());
	
		//hashSet of recipeUsers
	var hashSet = new HashSet<ThingDef>();
	
	foreach (ThingDef def in list)
	{
		DefPreviousProperties previous = DefPropertyCaching.GetNamed(def.defName);
		
		RecipeDef recipeDef = DefDatabase<RecipeDef>.GetNamed("Make_" + def.defName, false);
		if (recipeDef != null)
		{
			if (shouldBeCraftable
			    && !gunList.Value.Disallows(def, list)
			    && !previous.recipeUsers.NullOrEmpty())
			{
				recipeDef.recipeUsers = previous.recipeUsers.ListFullCopyOrNull<ThingDef>();
				previous.recipeUsers.ForEach(x => hashSet.Add(x));
			}
			else if (!previous.recipeUsers.NullOrEmpty())
			{
				recipeDef.recipeUsers.Clear();
				previous.recipeUsers.ForEach(x => hashSet.Add(x));
			}
		}
	}
	foreach (ThingDef recipeUser in hashSet)
	{
		recipeUser.RecacheRecipes(true);
	}
}
```
Please note:

1.  the creation of a HashSet of recipeUsers,
2.  saving a deep copy of the list of recipeUsers for each recipeDef
3.  clearing the recipeUsers if the recipe should be disabled, and
4.  the use of recipeUser.RecacheRecipes(true) for each recipeUser in hashSet.

**Comment by Alicecomma** [comment]
Resolved in https://github.com/NoImageAvailable/CombatExtended/commit/1274021d198af473dcd714aad200f124e2b73017.
