### ISSUE TITLE
Improve performance of HE and similar explosions

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#453]
A stack of explosives cooking off stalls rendering for about 10 seconds per tile of explosives (estimate). We can do better than that, maybe combine damaging effects so only one explosion needs calculations or put upper limits on the amount of cook-off on a stack of things such that it can't send more than X fragments out at once.

**Comment by NoImageAvailable** [comment]
Vast majority of performance drain comes from spawning fragments (as in the actual step of spawning them into the world). Best solution would probably be to stagger the stack explosion so they explode one at a time with a random delay between them. Would also make for a nicer effect.

**Comment by Alicecomma** [comment]
The TryDetonate call inside PreApplyDamage may cause part of the huge lag spikes, as TryDetonate doesn't actually destroy the stack it just causes an explosion with random chance.

**Comment by NoImageAvailable** [comment]
If you're referring to the staggered explosions, that's actually there to prevent lag spikes by distributing the explosions over multiple ticks.

**Comment by NoImageAvailable** [comment]
Frag spawning moved to a co-routine in https://github.com/NoImageAvailable/CombatExtended/commit/b587e7e7d96c9e2b1faa0068e35884c3be6a765f
