### ISSUE TITLE
Taming Animals

### ISSUE THREAD

**Issue by flyguy07** [NoImageAvailable/CombatExtended#454]
When a colonist is assigned to taming animals, they stall after they pick up the food. I have experienced them just standing in the same spot, or they will constantly pick up and drop the same item of food. When they do pick up food, it usually exceeds their bulk capacity.

I can manually have them prioritize training, and they will do it, but I have to do this each time they pick up food. 

I have confirmed this is associated with CE.

**Comment by NoImageAvailable** [comment]
Do you have Smarter Food Selection?

**Comment by flyguy07** [comment]
I do.

I was actually messing around with it some more, and it seems to be only my original colonists that seem to be having this issue. I recruited two other people, and I'm not experiencing the same problem.

**Comment by NoImageAvailable** [comment]
Known conflict with SFS
