### ISSUE TITLE
Mechanoids don't take internal damage from most weapons

### ISSUE THREAD

**Issue by IKapun** [NoImageAvailable/CombatExtended#455]
I noticed that centipedes don't take damage to their internal systems like artificial brain and other "organs". This happens even for high piercing weapons like PTRS-41 with FMJ ammo. Only the rings take 25 damage per hit. To my mind, mechanoids should mostly go down because of "internal organs" damage, much like humans do. Right now centipedes are usually incapacitated because they become incapable of moving because of ring damage and that is kind of boring.

**Comment by NoImageAvailable** [comment]
Are you sure the ammo isn't just being deflected?

**Comment by IKapun** [comment]
This could be the case but i tried most weapons and the only 1 i found capable of dealing internal damage is RPG with HEAT ammo and even then 1 direct hit was never enough to take it down. Maybe it would be better to remove damage on deflection for mechanoids? What does it represent? A huge dent? Because it is pretty boring having to hit a centipede 10 times with PTRS-41. In my opinion 1-2 hits with a decent weapon should be enough to down it.

**Comment by NoImageAvailable** [comment]
And most weapons won't be able to penetrate Centipede armor. This sounds like it's working as designed.
