### ISSUE TITLE
Turrets on hostile maps spawn without ammmo

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#459]
https://ludeon.com/forums/index.php?topic=33461.msg401479#msg401479

> After a few more tests I can say that turrets I build on my colony map have full ammo while hostile turrets on enemy maps are empty so they never shoot.
> I think this is the opposite of how it is supposed to be.

**Comment by NoImageAvailable** [comment]
Already fixed in current dev build
