### ISSUE TITLE
Implement pawns taking ammo and loadout items from pack animals.

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#46]
Would help pawns sent on caravans get their loadouts back after they place everything in their inventory on pack animals, and I would love to see raiders using pack animals in the future.

**Comment by NoImageAvailable** [comment]
I haven't played around with the world travel system yet but it seems to me with the CR inventory system it would make more sense for pawns to keep their inventories while travelling.

The issue itself should be fixable relatively easily by adding a check for items in pack animal inventories to the loadout job.

**Comment by RenaudF** [comment]
When pawns come back from travelling they will empty their inventory.
