### ISSUE TITLE
Disappearing loadout button?

### ISSUE THREAD

**Issue by Squidvad3r** [NoImageAvailable/CombatExtended#463]
I've just started a brand new game on tribal and have made some arrows for the bows I've started with. After happily making a loadout for 50 arrows for pawns with bows, I found that I wanted to edit the loadout but found that the button just disappeared... Please help, it's very, very frustrating to deal with.

**Comment by NoImageAvailable** [comment]
Are you running with multiple mods (especially anything that adds it's own UI elements)? Can you reproduce this with just CE loaded?

**Comment by Squidvad3r** [comment]
A have lots of mods installed, I don't think any of them add UI things though. I'll try just with CE.

**Comment by Squidvad3r** [comment]
OK, The only mod I have installed in this screenshot is CE. Yet the same problem occurs.

![20180331202653_1](https://user-images.githubusercontent.com/37916039/38161871-732178c0-3522-11e8-84e3-86cfb707180e.jpg)

**Comment by NoImageAvailable** [comment]
If you're talking about the "create loadout" button, that only appears when a pawn has no loadout assigned to them. This is working as designed.
