### ISSUE TITLE
allow backbag to be hit like a shield

### ISSUE THREAD

**Issue by jinlan** [NoImageAvailable/CombatExtended#467]
[suggest new feature]
#So that if backbag is hit and is not able to totally deflect the damage, a randomly selected item should take the damage ( just like your cloth lose HP when you are hit) .

This will make HP and material of the backbag actually matter.

**Comment by jinlan** [comment]
Or like an organ.

**Comment by NoImageAvailable** [comment]
Currently no decent way of implementing directional damage
