### ISSUE TITLE
Animal backbag

### ISSUE THREAD

**Issue by jinlan** [NoImageAvailable/CombatExtended#468]
[suggest new feature]
Wear it to a pack animal, allow it to be able to pick items despite whether it's in a caravan team, just like you can give item to pack animal any time  when in a "caravan generated map".

**Comment by NoImageAvailable** [comment]
Would need to add apparel to animals, too much effort for virtually no reward.

**Comment by jinlan** [comment]
Pack animal already have a backbag texture.
