### ISSUE TITLE
Bone should be considered when calculating armor

### ISSUE THREAD

**Issue by jinlan** [NoImageAvailable/CombatExtended#482]
Bone is at least be much more harder then a war mask, which is 0.1 sharp armor. If a bullet want to penetrate a skull, it should encounter a significant armor protecting the brain in it.
I suggest to add all bone part to some group and give that group at least 0.1 armor. So that a bone will have 0.1 + ( 0.05 * healthScale) armor, which is almost  the same with a bone short bow arrow. Then a short bow arrow will have a almost 50% damage reduction after penetrating a bone.

Btw, I can do it, if you like.

**Comment by NoImageAvailable** [comment]
Body parts already provide armor
