### ISSUE TITLE
Suppression check should be based on what is hit.

### ISSUE THREAD

**Issue by jinlan** [NoImageAvailable/CombatExtended#488]
In ProjectileCE.CheckCellForCollision(), this method check all pawns for ProjectileCE.TryCollideWith() fist, then if no one is hit, call ProjectileCE.ApplySuppression() to all pawns. That means if any pawn is hit, no suppression is applied. 
We should check whether the hit thing is something that can provide protection. If it's a wall or any other thing that can provide "safe feeling", no suppression. If it's a pawn, then suppression should be applied. 
Maybe check for fillage, pawn don't have fillage.

**Comment by NoImageAvailable** [comment]
This would make suppressing enemies in cover nearly impossible and deliberately not implemented this way.
