### ISSUE TITLE
MinifiedTurrets

### ISSUE THREAD

**Issue by cmdprompt** [NoImageAvailable/CombatExtended#495]
In the `WeaponsTurrets` category:
* `MinifiedTurret_AGSThirty`
* `MinifiedTurret_Blaster`
* `MinifiedTurret_Flak`
* `MinifiedTurret_Heavy`
* `MinifiedTurret_KPV`
* `MinifiedTurret_M240B`
* `MinifiedTurretGun`

These defs return `false` for the `Minifiable` property on `ThingDef` and so are not filtered out of items that should not be stacked, for stack mods.

**Comment by Alicecomma** [comment]
Already minifiable in the current version

![image](https://user-images.githubusercontent.com/4662406/64076074-572f1000-ccc0-11e9-938d-feed0befa972.png)

![image](https://user-images.githubusercontent.com/4662406/64076069-4bdbe480-ccc0-11e9-9885-ac65e226df40.png)
