### ISSUE TITLE
Review taunt motes

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#5]
Review the text for combat taunts. Cull inappropriate content (no more arrow to the knee).

**Comment by RenaudF** [comment]
I like mildly offensive, non PC stuff. Where are these defined?

**Comment by NoImageAvailable** [comment]
They're in /Languages/[Language]/Strings/NameBanks

**Comment by RenaudF** [comment]
Well I guess they could get old fast if overdone but that definitely adds to the combat athmosphere. Can that be influenced by a pawn traits or backstory I wonder?

**Comment by NoImageAvailable** [comment]
Technically, it can be influenced by anything you want. Pawn traits, health status, mood, etc. Its definitely possible but would fall to another coder because I'm not getting around to this any time soon.

**Comment by NoImageAvailable** [comment]
Done https://github.com/NoImageAvailable/CombatExtended/commit/74337b817b2c181b785a466b3c7d4544fe72718c
