### ISSUE TITLE
Minified items are automatically dropped after being picked up when added to loadout

### ISSUE THREAD

**Issue by vulkans22** [NoImageAvailable/CombatExtended#500]
Hopefully not a duplicate, searched and couldn't find anything... Creating a loadout with a minified item (Say, a telescope), causes the pawn to go pickup the item and immediately drop it after. This seems to completely remove the pickup job as any additional items to pickup with lower priority to the minified item in the loadout are ignored, with the pawn either going off to do something else or retry the pickup job.

I haven't looked at the source but a quick observation is that force picked up minified items show up as "furniture x Y" in the forced holding popup rather than their specific labels.

To be specific, I'm trying to get my pawns to automatically pickup minified bedrolls so they have something to sleep on when they're away from home.

**Comment by NoImageAvailable** [comment]
Should be fixed with #669
