### ISSUE TITLE
Pawns wearing shield belts cannot fire mounted weapons

### ISSUE THREAD

**Issue by kbsmilk** [NoImageAvailable/CombatExtended#502]
Tested on mortars, flak guns, m240b and KPV guns. When the operator is wearing a shield belt, the gun can't shoot. Trying to set forced target doesn't do anything, and the tile reticule that normally shows, doesn't. If the turrets are allowed to fire at will, they will aim at enemies, the aim-time circle will count down at the gun's barrel, but it won't fire, Instead, the aim-timer just resets and repeats.

Edit: I should note I think this is a bug because of this post from the A17 version: https://ludeon.com/forums/index.php?topic=33461.msg359008;topicseen#msg359008

They say that equipping a gun operator with a shield belt is a working tactic.

**Comment by NoImageAvailable** [comment]
Working as intended
