### ISSUE TITLE
Melee broken

### ISSUE THREAD

**Issue by maikilangiolo** [NoImageAvailable/CombatExtended#506]
when in melee, a error log always appears, which causes the game to pause every instant. is it cause by another mod (I only have compatible mods on)?

logs: 
`Could not resolve cross-reference: No RimWorld.StatDef named MeleeWeapon_DamageAmount found to give to RimWorld.StatModifier (null stat)
Verse.Log:Error(String)
Verse.WantedRefForObject:TryResolve(FailMode)
Verse.DirectXmlCrossRefLoader:ResolveAllWantedCrossReferences(FailMode)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
`
`Could not resolve cross-reference: No RimWorld.StatDef named MeleeWeapon_Cooldown found to give to RimWorld.StatModifier (null stat)
Verse.Log:Error(String)
Verse.WantedRefForObject:TryResolve(FailMode)
Verse.DirectXmlCrossRefLoader:ResolveAllWantedCrossReferences(FailMode)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
`

thanks

**Comment by NoImageAvailable** [comment]
Impossible to tell anything from the log and this isn't really the place to get tech support
