### ISSUE TITLE
B19 Compatibility

### ISSUE THREAD

**Issue by Kwask** [NoImageAvailable/CombatExtended#515]
Mod needs updating for the most recent B19 update

Load errors: https://pastebin.com/pds5inD5

**Comment by Kwask** [comment]
Is CE not going to be updated until the 1.0 release? I'm a little confused about what makes this issue invalid

**Comment by NoImageAvailable** [comment]
The fact that this is obvious and has been since before B19 released. Once work starts on updating I'll open an appropriate milestone.

**Comment by ShazamKnight** [comment]
Come on Kwask, let the man work. It was JUST updated, and he's not getting paid to do this work, let him take his time and thank him appropriately when he does release it. Lol

**Comment by DavidBittner** [comment]
I don't understand the hostility toward Kwask. As a developer it helps to have an issue to track progress. By no means creating one shows one pushing toward immediate results.

**Comment by ShazamKnight** [comment]
If I came across hostile, that wasn't intended. I just see too many people wanting free mods to games updated immediately like it's a paid product. NoImageAvailable is constantly working to update and debug this mod, so saying it needs updating to B19 immediately after the game is updated to B19 is just jumping the gun early. Have a great night guys!
