### ISSUE TITLE
Fix compiler errors

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#516]
Gotta catch 'em all

**Comment by Crutchmaster** [comment]
Glad to see you. Need any help?
My old xbuild (v12.0 mono v3.2.8.0) find 291 errors like:
``
        CombatExtended/Jobs/JobDriver_Reload.cs(29,55): error CS1525: Unexpected symbol `?'
        CombatExtended/Jobs/JobDriver_Reload.cs(29,67): error CS1525: Unexpected symbol `.'
        CombatExtended/Jobs/JobDriver_Reload.cs(30,58): error CS1525: Unexpected symbol `?'
        CombatExtended/Jobs/JobDriver_Reload.cs(30,70): error CS1525: Unexpected symbol `.'
        CombatExtended/Jobs/JobDriver_Reload.cs(73,44): error CS1525: Unexpected symbol `?'
        CombatExtended/Jobs/JobDriver_Reload.cs(74,7): error CS1525: Unexpected symbol `||'
``
It is ok? I think mono too old, but may be not.
