### ISSUE TITLE
Shooter hits downed pawn they're standing on

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#520]
"if a shooter is standing on a downed body this downed body will get hit first which is kinda absurd(again ALL bullets not a few)" https://ludeon.com/forums/index.php?topic=33461.msg433253#msg433253

While shooter height is increased for standing on top of a building/barricade, those are the only Things checked at shooter position to increase height. One could increase shooter height for standing on a downed pawn by the height of the downed pawn as well.

**Comment by NoImageAvailable** [comment]
Shooting own cover/pawns you're standing on/etc. should be fixed in 1.6
