### ISSUE TITLE
Sniper and Autocannon turrets should be CE patched

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#536]
For the 1.0 release or after it, these turrets could be made compatible. Currently two approaches exist: remove the turrets altogether (XeoNova's PR's) or use minimal patching without balancing whatsoever (current Development branch).

**Comment by Alicecomma** [comment]
So, remove both?

**Comment by NoImageAvailable** [comment]
Pretty much

**Comment by Alicecomma** [comment]
Removed in #540
