### ISSUE TITLE
Rebalance new apparel

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#557]
The way apparel armor stats work changed (multiplier/base switched with stuff), also new armor apparel added (flak stuff, maybe others). Needs balancing.

**Comment by NoImageAvailable** [comment]
New armor apparel:
- [x] Flak vest: formerly armor vest, roll back to B18 variant
- [ ] Flak jacket: new addition overlapping with CE flak jacket, override vanilla with CE version
- [ ] Flak pants: new addition, bring in line with CE flak jacket
- [ ] Plate armor: bring stats in line with something appropriate for medieval full plate

**Comment by NoImageAvailable** [comment]
Design notes for balance targeting points:
- Cloth version should act as IRL flak jacket (protection against shrapnel/frag), Devilstrand version as IIA kevlar vest (protection against non-AP handgun rounds)
- Frag has AP of 0.25, meaning 0.3 will stop 100% of fragmentation hits
- Common handgun AP variants have AP of 0.46, rifle FMJ 0.45 and up
- Armor of 0.4 will reliably defeat common handgun rounds + small rifle HP while being completely ineffective by AP pistol or FMJ/AP rifle ammo
- Armor of 0.45 will defeat pistol AP/small rifle FMJ ~50% of the time

B17 CE flak vest armor stats for (sharp/blunt):
- Cloth: 0.15/0.1
- Synthread: 0.297/0.1456
- Devilstrand: 0.36/0.195

One thing to take away from this is the B17 version falls short of the stated target as it provides no protection against fragmentation in the base version (armor has to be >0.2 to have a chance of stopping 0.25 AP frag). For 1.0, base values should be adjusted to meet 0.25 base, 0.4 with Devilstrand or close to that.

**Comment by XeoNovaDan** [comment]
From #598: [CEApparel.xlsx](https://github.com/NoImageAvailable/CombatExtended/files/2634917/CEApparel.xlsx)

**Comment by NoImageAvailable** [comment]
Partially implemented in #612

**Comment by NoImageAvailable** [comment]
Implemented as of #615
