### ISSUE TITLE
Remove charge lance

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#558]
Vanilla made it craftable, should remove since it's very much balanced as an NPC only weapon.

**Comment by N7Huntsman** [comment]
According to the Rim wiki, it can both be crafted or purchased from outlanders or orbital weapon suppliers. Are you alright with them being available through those means, or do you not want them available to the player at all?

**Comment by NoImageAvailable** [comment]
Shouldn't be obtainable at all. The role of charge sniper is already filled in CE Guns and overriding is not desirable because it would give Scythers a *significant* power boost.

**Comment by N7Huntsman** [comment]
Alright, shouldn't be too difficult. Patch to remove the <recipeUser> so it can't be crafted anywhere. Will have to check the weapon tag, but hopefully it's unique to the gun so I can just pull it from the merchants as well--if not, it'll require some juggling with tags.

**Comment by N7Huntsman** [comment]
I've completed a patch that disables the ability to craft the gun (it just deletes the gun's RecipeMaker) and that _should_  also prevent traders from showing up with it (deleted the SpaceGun weaponTag, leaving only the tag associated w/ mechanoids).
