### ISSUE TITLE
Re-add raider equipment

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#562]
B19 removed high tier equipment like charge weapons and power armor from raiders. Need to undo this change

**Comment by N7Huntsman** [comment]
Elite Mercenary Bosses (the only PawnKind marked as "Elite tier") can still spawn with Power Armor (so-called "marine armor"), but their apparelMoney is set at 3500 max, which is pretty low. At the moment, they can't spawn with Charge Rifles, but that can be fixed easily enough. For comparison, the bosses have weaponMoney of 500 - 1400, and apparelMoney of 2500 - 3500.

The next highest mid-tier merc, the mercenary heavy has Money of 200 - 350 and 1200 - 1200, respectively. The "highest" tier of pirate is also mid-tier, with money of 400 - 1000 and  250 - 345. Neither of these two have the tags to spawn with power armor or charge weapons.

The question is, who all do you _want_ to be able to spawn with those things?

**Comment by N7Huntsman** [comment]
Pull submitted.
