### ISSUE TITLE
Remove armor from starting scenario

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#574]
Rather trivializes the early game to start with a full set of armor.

**Comment by Zuthal** [comment]
Scenarios can be easily edited with the means the vanilla game gives you, so I don't think this is really a high priority to do on the side of the mod dev.

**Comment by lucyfareEM** [comment]
all of the armour

**Comment by Zuthal** [comment]
I presume he means changing the default scenario/change what gear the starting colonists can start with so that they cannot start with any body armour.

**Comment by N7Huntsman** [comment]
What Lucy said--do you want _all_ armor removed from _all_ scenarios, or just the flak vest + pants and advanced helmet from the Crashlanded scenario?

**Comment by NoImageAvailable** [comment]
There is no armor apparel in scenarios besides Crashlanded? But yeah, it's the flak pants, vest and helmet that should go. Would provide too much of a boost against early game raids and take most of the tactics out of it.

**Comment by N7Huntsman** [comment]
I've completed a patch that removes the armor. I'll add it to the Scenarios.xml patch in Patches > Core.
... Once I read up on GitHub enough to figure it out.

**Comment by lucyfareEM** [comment]
what about keeping the helmet and removing the pants and vest?

**Comment by NoImageAvailable** [comment]
Done https://github.com/NoImageAvailable/CombatExtended/commit/065f73deb350c710c399d6acb491ccd7d438213f
