### ISSUE TITLE
Add minimum time between taunts

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#58]
Right now taunts can fire with no limit, leading to lots of screen clutter at times. Should introduce a minimum amount of time between taunts.

**Comment by Alicecomma** [comment]
Taunts are cast randomly per projectileCE Tick() for each projectile of the Pawn shooter.

**Comment by NoImageAvailable** [comment]
https://github.com/NoImageAvailable/CombatExtended/commit/42c0e0c8ca21bed8ee5e463bee646d60e546a0ca Taunts are now done on warmup and have a hard timer with some randomization.
