### ISSUE TITLE
Cant Craft some ammo types

### ISSUE THREAD

**Issue by ChristianO0214** [NoImageAvailable/CombatExtended#584]
I am unable to craft the .303 ammo for the Bolt action rifle. I am also not able to craft arrows for short bow. I have technology all the way to gunsmithing, and I have both the machining table and the loading bench. No option to craft either of these ammos is in the loading bench or machining table. 

I have downloaded the most recent development build.

I used to play this mod no problem in beta 18. Is there something wrong with the mod right now, or am I too stupid to figure out how to make ammo.

**Comment by lucyfareEM** [comment]
the mod is still in development most of the bugs in the mod are being worked on do you have to wait

**Comment by ChristianO0214** [comment]
Ok thanks
