### ISSUE TITLE
Sway Lissajous "jumping"

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#59]
Lissajous appears broken. To see what I am talking about:

- Change Minigun def to 0 recoilAmount/shotSpread, 10 aim efficiency
- Console spawn Minigun
- Have pawn equip Minigun and force fire at a distant wall

The projectile stream will have a period where it stays relatively stationary before making a large jump on the horizontal.

**Comment by Alicecomma** [comment]
This was an issue due to integer division in the lissajous formula. This has been fixed in https://github.com/NoImageAvailable/CombatExtended/commit/74cdc8a4cad2e6ff9a16529a20a60960dea09329, please report whether the bug still occurs.

**Comment by NoImageAvailable** [comment]
Can no longer reproduce this issue, so can be considered fixed
