### ISSUE TITLE
Roof collapse should have ap (Or any DamageInfo.ap=0)

### ISSUE THREAD

**Issue by kpqi5858** [NoImageAvailable/CombatExtended#597]
Deals no (or low chances do) damage if pawn has anything equipped

**Comment by NoImageAvailable** [comment]
AP=0 would make it deal no damage ever. Should probably use a decently high value appropriate for a mass of material collapsing on someone but the principal point is fair.

**Comment by NoImageAvailable** [comment]
Damage without explicit source now has infinite AP https://github.com/NoImageAvailable/CombatExtended/commit/2847360e0435890f0c7edf79cb7aa4a9a1547caf
