### ISSUE TITLE
Remove vanilla stun chances for normal blunt attacks

### ISSUE THREAD

**Issue by XeoNovaDan** [NoImageAvailable/CombatExtended#600]
Since CE has critical hits for blunt attacks, normal blunt attacks shouldn't be able to stun like they currently do in Beta 19.

Should be doable simply by xpathing out ``bluntStunChancePerDamagePctOfCorePartToHeadCurve`` and ``bluntStunChancePerDamagePctOfCorePartToBodyCurve`` from Blunt DamageDef

**Comment by N7Huntsman** [comment]
Unfortunately, after a bit of testing, patching out those tags from the Blunt DamageDef doesn't seem to be sufficient to prevent attacks from Stunning pawns.

**Comment by NoImageAvailable** [comment]
Are you simply running into the CE crit effects here?

**Comment by N7Huntsman** [comment]
Not sure--I'm getting the big 'STUN' message printed across the pawn, and I was under the impression that was strictly a vanilla feature because CE handles crits differently.

**Comment by NoImageAvailable** [comment]
That sounds like you're just seeing the crit effect to me.

**Comment by N7Huntsman** [comment]
Then I guess I don't understand what exactly we're trying to remove here, if not that crit effect.

**Comment by NoImageAvailable** [comment]
We're removing vanilla blunt stun so it won't overlap with stun from crits. We're definitively not removing crits or anything crit-related.

**Comment by N7Huntsman** [comment]
Ah. Then I guess I have a patch that removes the vanilla chunk. I've made a PR.........

**Comment by NoImageAvailable** [comment]
Implemented #604
