### ISSUE TITLE
Excessively high shot angles

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#62]
Shots will sometimes angle at extremely high angles. Especially noticeable against tall enemies like Thrumbos. Likely introduced in https://github.com/NoImageAvailable/CombatExtended/commit/e6ab448243899f2173fbe8b6871394d66b689d71

**Comment by ProfoundDarkness** [comment]
Looks like a recent commit might have fixed this.

Sampling a bunch of bullet angles in the situation which caused things to be quite bad (with a Thrumbo) shows far saner bullet angles than from before.  Angles are around 0.13 on the typical high end, before the average was around 0.3 and I saw a few 0.8.

**Comment by Alicecomma** [comment]
Should be fixed in https://github.com/NoImageAvailable/CombatExtended/commit/74cdc8a4cad2e6ff9a16529a20a60960dea09329.
