### ISSUE TITLE
Conflict with Doors Expanded

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#621]
Testing with version b58109bfa4270fe330a40937e21a576a1f06834e

This is a really weird conflict, so it took me a while to figure out which mod was doing it, but when both Doors Expanded and Combat Extended are loaded, when a frag grenade explodes there's a several-second game freeze as it goes off.

Why the heck a mod which adds doors would mess up frag grenades, even when none of the doors have been built, I have absolutely no clue. Not sure which side is at fault either, but since this is beta and that isn't, reporting it here first... if you think it's their side, just say and I'll post it there.

I did test it with a minimal modset (Core, HugsLib, JecsTools, DE, CE) and a freshly-started game to make certain it was actually that, since it seemed so unlikely.

**Comment by NoImageAvailable** [comment]
This conflict has been known for a while.

My best guess is something about DE doesn't mesh well with having lots of projectiles in the area and/or CE collision detection. For example a common method for multi-cell/custom doors is placing invisible doors on top of an unrelated sprite. This could mess with CE's sprite-based hitboxes as well as the hit detection checks for a door being open.

**Comment by Maeyanie** [comment]
That would be understandable, but... it happened even when I was testing it on a fresh map, without any of the doors being constructed. Unless some appeared in ruins, but I don't think they do that.

**Comment by NoImageAvailable** [comment]
Would still be possible if the invisible doors are spawned on construction start. That said, this is just a theory and a code dive/asking the DE dev might shed more light on the issue.

**Comment by Maeyanie** [comment]
I didn't even place any doors. Literally all I did in the minimal test was spawn a new random map, dev mode in some grenades, and toss one.

There is an [entry on the DE github](https://github.com/jecrell/DoorsExpanded/issues/4) as well, which I updated with some info. I'll link this thread there too.

**Comment by Maeyanie** [comment]
As a thought, if this is a known, long-standing conflict, perhaps it should be put in the "known conflicts" list on the first post.

**Comment by JonnyNova** [comment]
Further fixed with: https://github.com/jecrell/DoorsExpanded/pull/20
