### ISSUE TITLE
Hunting boomalopes

### ISSUE THREAD

**Issue by seanandjay29** [NoImageAvailable/CombatExtended#623]
trying to finish off a downed boomalope with a shotgun (may be all guns) causes the pawn to freeze and not know how to kill it and gives error in debug menu

**Comment by seanandjay29** [comment]
[boomalope hunt error.txt](https://github.com/NoImageAvailable/CombatExtended/files/2776984/boomalope.hunt.error.txt)

**Comment by NoImageAvailable** [comment]
This is part of a wider issue in that hunters will maintain optimal range when the animal moves beyond it but not if it moves closer. 

This also means you could say, start hunting a Megatherium, get a point at optimal range and by the time you get there it has randomly wandered to the shooting location as well, meaning you're shooting point blank now (and getting mauled when it inevitably goes into revenge mode).

As vanilla has no support for finding cast positions within a certain range band (only max range) we'd need to implement a custom solution. As this is not an excessively gamebreaking issue and the solution would require a decent bit of work moving this into post-1.0 release territory.

**Comment by ImperialHouse200** [comment]
its called a megasloth, get it right

**Comment by General1337** [comment]
Issue has been fixed here: https://github.com/NoImageAvailable/CombatExtended/pull/665

**Comment by General1337** [comment]
Issue is fixed here: https://github.com/NoImageAvailable/CombatExtended/pull/665

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/2bf72dbac3eedff1a465f77e1c23c6a53fa0128f
