### ISSUE TITLE
Issue with loadouts

### ISSUE THREAD

**Issue by Brumes-Wolf** [NoImageAvailable/CombatExtended#628]
I found an Issue with loadouts, they don't save. after loading a save they all items in a loadout will reset to quantity 0. Pawns will then drop their stuff, I tested this with a new colony on both the Steam workshop and github version both have this problem. If extra info is wanted I will do my best to provide it.

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/191ceae17524dfee9fe6ba480cdbeb0930676610
