### ISSUE TITLE
HE Mortar Shells Performance Issues

### ISSUE THREAD

**Issue by N7Huntsman** [NoImageAvailable/CombatExtended#640]
There is a significant performance drop when mortars impact, even with nothing else going on on the map.

**Comment by NoImageAvailable** [comment]
You mean other than the performance drop that's always been happening when you try spawning 300 projectiles in a single tick?

**Comment by N7Huntsman** [comment]
No, I am talking about that one--the fragmentation system is neat, but it's a massive performance drop whenever anything heavy is fired (flak gun, mortar, RPGs and frag grenades to a lesser extent) and it needs to be addressed. The system and the visual effect are cool, but it's not worth turning the game into a slideshow when you use it for it's intended purpose of targeting crowds.

**Comment by NoImageAvailable** [comment]
It's not about visuals, it's about accurate cover calculations. So far nobody has been able to formulate a simplified algorithm that keeps this functionality, so it stays as is.
