### ISSUE TITLE
FSX doesn't work in chemfuel generators

### ISSUE THREAD

**Issue by daniellockard** [NoImageAvailable/CombatExtended#642]
FSX doesn't work in generators, when harvesting from Boomalopes,  is that intended?

**Comment by N7Huntsman** [comment]
FSX is a component for the manufacturer of explosives, not a fuel--think of it like nitroglycerin.

**Comment by daniellockard** [comment]
Okay, so basically this mod 100% removes 1 way of farming chemfuel.
