### ISSUE TITLE
Issue with Zombieland; Trying to shoot through walls when set to fight back

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#643]
https://cdn.discordapp.com/attachments/140890123741954049/539526250184572948/unknown.png

As posted in the discord

ModList; https://pastebin.com/JaxTzww1

Hugslib (its super long) https://gist.github.com/HugsLibRecordKeeper/75c6f4e97d7d143caba4d1d0108d15aa

**Comment by NoImageAvailable** [comment]
Should be fixed as part of #616
