### ISSUE TITLE
Trying to throw explosive trough a wall (?)

### ISSUE THREAD

**Issue by Valerate** [NoImageAvailable/CombatExtended#645]
https://cdn.discordapp.com/attachments/140890123741954049/539927982664581122/unknown.png

Unsure if unfortunate interaction with other mod

ModList; https://pastebin.com/JaxTzww1

Hugslib (its super long) https://gist.github.com/HugsLibRecordKeeper/75c6f4e97d7d143caba4d1d0108d15aa

**Comment by NoImageAvailable** [comment]
Pretty much impossible to reproduce at this point
