### ISSUE TITLE
Mounted turrets don't display weapon stats

### ISSUE THREAD

**Issue by adiep2501** [NoImageAvailable/CombatExtended#647]
For weapons that pawns carry, you can see the stats but you can't see the stats on mounted turrets. It's especially a problem with the turret pack when you try to compare turrets. I didn't realize turrets even had sway and spread until I looked at the patch files.

Not sure if you can even fix it since maybe the problem is that the base game doesn't display weapon stats for furniture.

**Comment by NoImageAvailable** [comment]
That's a vanilla issue.

**Comment by adiep2501** [comment]
Seems like my guess was correct. Should this issue be closed or left open as reference?

**Comment by Alicecomma** [comment]
This can only be done without Harmony patches by setting the StatDef of Caliber to "BasicsNonPawn". I'd argue it's worth it to put Caliber in this category just for allowing it to show up on turrets.

**Comment by NoImageAvailable** [comment]
I'd rather have the turret description copy it's weapon category from the gun. This affects more than just caliber.

**Comment by Alicecomma** [comment]
An alternative way to add the stat would be to add it to the Building category

**Comment by Alicecomma** [comment]
Suggestion to add a second stat (Building with showOnNonWorkTables) with the same worker, with the worker expanded to be capable of handling both turrets and guns.

I got the code for it ready to PR

**Comment by Alicecomma** [comment]
Merged in #765, turrets now display weapon stats
