### ISSUE TITLE
Mortar shells disappearing/failing to fire.

### ISSUE THREAD

**Issue by N7Huntsman** [NoImageAvailable/CombatExtended#651]
Odd issue where mortar shells fail to fire/disappear when fired at longer ranges, but will fire and impact at shorter ranges.

Reported via Steam, including video of issue: https://www.youtube.com/watch?v=1jDzJrgzpHA&feature=youtu.be

**Comment by NoImageAvailable** [comment]
Is there an error log attached?

**Comment by N7Huntsman** [comment]
I'm unable to reproduce the issue. I'll try to get a mod list and error log.

**Comment by Alicecomma** [comment]
I suspect the fired projectile speed is below a value physically possible to hit the specified location, cancelling the shot on spawn as it can not ever reach destination

**Comment by NoImageAvailable** [comment]
That'd be the old charges system. Still doesn't have a proper config error attached to it.

**Comment by NoImageAvailable** [comment]
Should hopefully be fixed with https://github.com/NoImageAvailable/CombatExtended/commit/842f8c7a2be5fb8ccc9c3e9355e453b42adb95d8
