### ISSUE TITLE
RunAndGun Mod Extension Issue.

### ISSUE THREAD

**Issue by N7Huntsman** [NoImageAvailable/CombatExtended#653]
Thrown on startup with only Hugs, CE, and Run and Gun loaded. 

'Could not find type named RunAndGun.DefModExtension_SettingDefaults from node Class="RunAndGun.DefModExtension_SettingDefaults'

Full log message: https://justpaste.it/1m7fb

**Comment by NoImageAvailable** [comment]
That's cause you need the as-of-yet unreleased version of RunAndGun. Roolo said he'll release it sometime today
