### ISSUE TITLE
No Ammo for alien race scenarios

### ISSUE THREAD

**Issue by rumblerina** [NoImageAvailable/CombatExtended#655]
CE Race patches don't include ammo for race-specific weapons in their respective starting scenarios (Orassans, Xenn). And maybe adding a fuel puddle to xenn burn cannon shots is a bit crazy...

**Comment by NoImageAvailable** [comment]
Race patches were submitted by @Superlagg they're not being maintained by the CE devs.

**Comment by Superlagg** [comment]
Sure thing, I'll fix it once I figure out how to patch the scenarios.

Thanks for the feedback! Yeah the burn cannon does need some work. If you have any suggestions, feel free to let me know.
