### ISSUE TITLE
Shotgun reload accidentally converts ammo types

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#659]
Weapons that load ammo one at a time, like the pump shotgun, will switch existing ammo from one type to another if the pawn is carrying multiple types and doesn't have enough for a full reload. For example, try this loadout on a pawn:

Shotgun (5 shells capacity)
4 Buck Shells
10 EMP Shells

Select Buck as the ammo type, reload, and when the pawn starts loading the 5th shell, the shotgun's ammo type will switch to EMP. If you then unload the shotgun, the inventory will show 14 EMP shells, so the 4 Buck shells were lost and replaced by EMP.

**Comment by Alicecomma** [comment]
Seems to be fixed entirely by the commit. It just shows the "out-of-ammo" mote a lot

**Comment by LockdownX7** [comment]
>shows the "out-of-ammo" mote a lot

In what situation? Should only be displayed once when the pawn runs out of ammo in the middle of a one-by-one reload.

**Comment by Alicecomma** [comment]
Yes, but normally the mote shows when the gun is completely out of ammo _and is now carried in the backpack_, not when the magazine has loaded fewer rounds than it can hold.

**Comment by LockdownX7** [comment]
On a second look, I have to agree.

I added that mote to make it clear to the player that the reload process was stopped due to an ammo type running out, but it does feel inconsistent with the other uses of the mote. Especially since the mote is firing in cases it really shouldn't, like when the number of rounds available exactly matches the magazine capacity. I'll start a new PR to nick that.
