### ISSUE TITLE
Replace TurretTopCE with turretDrawSize

### ISSUE THREAD

**Issue by Faryzal2020** [NoImageAvailable/CombatExtended#660]
I'm trying to rewrite my turrets mod with CE parameters and file structures. 
so currently in my mod (without CE), in the thingDef for the turret building, inside "building" tag theres a "turretTopDrawSize" parameter below the "turretGunDef" and "turretTopGraphicPath" that resizes the texture for the gun turret, it seems like the parameter doesn't work with CE?

Turret_Base.xml : https://pastebin.com/4JRqUvDp
Turret_6Pdr.xml : https://pastebin.com/cj2NA0uB

**Comment by NoImageAvailable** [comment]
CE implemented this functionality a long time ago by not downscaling larger turret top graphics, e.g. the flak turret uses a 256x256 sprite vs the other turrets' 128x128. Since there is now equivalent vanilla functionality the TurretTopCE class should be culled.

**Comment by Faryzal2020** [comment]
but this turret top texture is downscaled, its a 700x700 sprite
![image](https://user-images.githubusercontent.com/8612170/52240403-13d01700-2914-11e9-9bd7-20d3e7d95655.png)

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/628141b14af2f16eb9d4af3ce290fd13a503d6c1
