### ISSUE TITLE
Projectile Impact Calculations Performance

### ISSUE THREAD

**Issue by N7Huntsman** [NoImageAvailable/CombatExtended#661]
As discussed previously on the Discord, the collision/impact of fragmentation from grenades, mortars, etc. causes excessive stuttering and loss of framerate.

Issue opened for tracking purposes.

**Comment by NoImageAvailable** [comment]
As discussed on the Discord, has nothing to do with fragments, this affects all projectiles. Something making the impact calculations take vastly more CPU than previous versions.

**Comment by N7Huntsman** [comment]
That's what I was alluding to, at any rate. Obviously, with fragmentation creating projectiles a few hundred at a time, it's most evident with that.
