### ISSUE TITLE
Wearing clothes prevents most damage from surgery failures

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#666]
If a pawn is wearing anything at all while getting operated on, and the surgery fails, they won't receive any damage. Instead, the 'attack blocked' sound will be heard, and the pawn will survive even a catastrophic/ridiculous surgery failure unscathed.

EDIT: Not all damage. Sometimes one or two surgical cuts will make it through and injure the pawn, but it's rare. Might be fixable by setting surgical cuts to have very high armor penetration?

**Comment by MoneyAllDay** [comment]
[LockdownX7](/LockdownX7) if the surgical cuts have very high armor penetration won't it damage the armor tho?

**Comment by LockdownX7** [comment]
It might. Ideally, surgical cuts should skip the armor system entirely, but I don't know how feasible that is.

**Comment by NoImageAvailable** [comment]
1.0 changed surgery damage from surgical cut (which bypasses armor) to random non-bypassing types but does not define a proper AP value. Armor deflecting surgical failures happens in vanilla. Not gonna write transpiler patches to fix vanilla bugs.
