### ISSUE TITLE
Error with 6x24mm charged ion bullets while target wears a ballistic shield

### ISSUE THREAD

**Issue by AndrewZo** [NoImageAvailable/CombatExtended#667]
This causes bullets to freezes when they are should hit the target. So there is an error. 

```
Exception ticking Bullet_6x24mmCharged_Ion22382 (at (129, 0, 112)): System.NullReferenceException: Object reference not set to an instance of an object
at CombatExtended.ArmorUtilityCE.GetAfterArmorDamage (Verse.DamageInfo,Verse.Pawn,Verse.BodyPartRecord,bool&,bool&,bool&) <0x009ac>
at CombatExtended.Harmony.Harmony_DamageWorker_AddInjury_ApplyDamageToPart.ArmorReroute (Verse.Pawn,Verse.DamageInfo&,bool&,bool&) <0x000c9>
at (wrapper dynamic-method) Verse.DamageWorker_AddInjury.ApplyDamageToPart_Patch1 (object,Verse.DamageInfo,Verse.Pawn,Verse.DamageWorker/DamageResult) <0x00127>
at Verse.DamageWorker_AddInjury.ApplyToPawn (Verse.DamageInfo,Verse.Pawn) <0x0033e>
at Verse.DamageWorker_AddInjury.Apply (Verse.DamageInfo,Verse.Thing) <0x000be>
at Verse.Thing.TakeDamage (Verse.DamageInfo) <0x002dd>
at CombatExtended.BulletCE.Impact (Verse.Thing) <0x006c0>
at CombatExtended.ProjectileCE.TryCollideWith (Verse.Thing) <0x008c2>
at CombatExtended.ProjectileCE.CheckCellForCollision (Verse.IntVec3) <0x008d6>
at CombatExtended.ProjectileCE.CheckForCollisionBetween () <0x003af>
at CombatExtended.ProjectileCE.Tick () <0x001cd>
at Verse.TickList.Tick () <0x00487>

Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

**Comment by Psionix** [comment]
info for devs
armorCategory is null in
`                        // Apply secondary damage to shield
                        var props = dinfo.Weapon?.projectile as ProjectilePropertiesCE;
                        if (props != null && !props.secondaryDamage.NullOrEmpty())
                        {
                            foreach(SecondaryDamage sec in props.secondaryDamage)
                            {
                                if (shield.Destroyed) break;
                                var secDinfo = sec.GetDinfo();
                                var pen = originalDinfo.ArmorPenetrationInt; //GetPenetrationValue(originalDinfo);
                                var dmg = (float)secDinfo.Amount;
                                TryPenetrateArmor(secDinfo.Def, shield.GetStatValue(**secDinfo.Def.armorCategory.armorRatingStat**), ref pen, ref dmg, shield);
                            }
                        }`
`+		base	"EMP"	Verse.Def
+		Worker	{Verse.DamageWorker}	Verse.DamageWorker
		additionalHediffs	null	System.Collections.Generic.List`1[[Verse.DamageDefAdditionalHediff, Assembly-CSharp, Version=1.0.6955.24666, Culture=neutral, PublicKeyToken=null]]
		armorCategory	null	Verse.DamageArmorCategoryDef
		biteDamageMultiplier	1	System.Single
		bluntInnerHitChance	0	System.Single
+		bluntInnerHitDamageFractionToAdd	"0~0"	Verse.FloatRange
+		bluntInnerHitDamageFractionToConvert	"0~0"	Verse.FloatRange
		bluntStunChancePerDamagePctOfCorePartToBodyCurve	null	Verse.SimpleCurve
		bluntStunChancePerDamagePctOfCorePartToHeadCurve	null	Verse.SimpleCurve
		bluntStunDuration	1	System.Single
		buildingDamageFactor	1	System.Single
		canInterruptJobs	true	System.Boolean
		canUseDeflectMetalEffect	true	System.Boolean
+		combatLogRules	"Damage_EMP"	Verse.RulePackDef
		cutCleaveBonus	0	System.Single
		cutExtraTargetsCurve	null	Verse.SimpleCurve
		deathMessage	"{0} has been EMPed to death."	System.String
		defaultArmorPenetration	-1	System.Single
		defaultDamage	50	System.Int32
		defaultStoppingPower	0	System.Single
		execution	false	System.Boolean
		explosionAffectOutsidePartsOnly	true	System.Boolean
+		explosionCellMote	"Mote_BlastEMP"	Verse.ThingDef
+		explosionColorCenter	"RGBA(1.000, 1.000, 1.000, 1.000)"	UnityEngine.Color
+		explosionColorEdge	"RGBA(0.800, 0.800, 0.800, 0.800)"	UnityEngine.Color
		explosionHeatEnergyPerCell	0	System.Single
+		explosionInteriorMote	"Mote_ElectricalSpark"	Verse.ThingDef
		explosionSnowMeltAmount	0	System.Single
		harmAllLayersUntilOutside	false	System.Boolean
		harmsHealth	false	System.Boolean
		hasForcefulImpact	true	System.Boolean
		hediff	null	Verse.HediffDef
		hediffSkin	null	Verse.HediffDef
		hediffSolid	null	Verse.HediffDef
+		impactSoundType	"Electric"	Verse.Sound.ImpactSoundTypeDef
		isExplosive	false	System.Boolean
		isRanged	false	System.Boolean
		makesAnimalsFlee	false	System.Boolean
		makesBlood	false	System.Boolean
		minDamageToFragment	99999	System.Int32
+		overkillPctToDestroyPart	"0~0.7"	Verse.FloatRange
		plantDamageFactor	1	System.Single
		scratchSplitPercentage	0.5	System.Single
+		soundExplosion	"Explosion_EMP"	Verse.SoundDef
		stabChanceOfForcedInternal	0	System.Single
		stabPierceBonus	0	System.Single
+		workerClass	{Verse.DamageWorker}	System.Type
`

**Comment by NoImageAvailable** [comment]
EMP damage was missing armor data, fixed https://github.com/NoImageAvailable/CombatExtended/commit/443676d25e101eb7e1dfaa5ca45db6d51a4eac4d
