### ISSUE TITLE
Refactor aiming system

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#67]
Current aiming system code is based on lots of copy-paste from vanilla classes and ended up as a weird physics-/destination-based hybrid. To quote Alistaire "we should add a NotImplemented error for calling the vanilla system and create ProjectileCE virtuals for methods called with shotAngle, shotHeight, shotSpeed"

**Comment by Alicecomma** [comment]
Potentially fixed in https://github.com/NoImageAvailable/CombatExtended/commit/74cdc8a4cad2e6ff9a16529a20a60960dea09329 , please report findings.

Along with the other fixes, explosion fragments now travel way and way further. This change requires feedback.
