### ISSUE TITLE
Melee critical hits from sharp weapons do not bypass armor

### ISSUE THREAD

**Issue by jmhorjus** [NoImageAvailable/CombatExtended#670]
According to the readme, critical hits from sharp melee weapons are supposed to bypass all armor, but currently they do not.

Tested on most recent steam release (Feb 4) with two pawns with knives and power armor and no other mods (Core+HugsLib+CE+Mod Manager+Prepare Carefully).

**Comment by NoImageAvailable** [comment]
Outdated readme, updated
