### ISSUE TITLE
70mm mechanoid grenades shouldn't be like mortar shells

### ISSUE THREAD

**Issue by f0xhunt** [NoImageAvailable/CombatExtended#672]
I installed Mechanoids Extraordinaire and found that the grenade launcher hounds uses is extremely powerful. It produces a lot fragments and the explosion instantly kills most humans in the blast radius. There are so many fragments, hounds frequently down other mechs. Digging into the defs, I found that they are defined similarly to mortars with Fragment_Shell instead of Fragment_Grenade.

Mortars are balanced around the fact they are inaccurate, making the fragments sensible. But the launcher are more accurate and shoot faster, which makes them insane. They are more powerful than the inferno cannons because of the fragments.

**Comment by f0xhunt** [comment]
If it was up to me, I would probably make the mechanoid nade slightly better than 40X53mm and with the same number of fragments.

**Comment by f0xhunt** [comment]
Woops, I looked at the wrong numbers. The projectiles are the things that actually damage you. I am guessing the base is when the shells catch fire.

**Comment by f0xhunt** [comment]
https://github.com/f0xhunt/CombatExtended/commit/77bb28963fb57ef54a0cad20aec67aeae6c26b77

I tweaked the settings so it's more like 40x53mm.

**Comment by NoImageAvailable** [comment]
That patch was submitted by a third party and is not maintained by us.

**Comment by f0xhunt** [comment]
So I guess we shouldn't be fixing a problem in the main mod where the issue is sort of caused by it's usage in another mod.

**Comment by f0xhunt** [comment]
So to address the balance issue, I should modify the grenade launcher as oppose to the main mod?

**Comment by NoImageAvailable** [comment]
I would start by looking at where the whole 70mm auto grenade launcher (which really is a cannon more than anything) concept came from and adjust from there, because nerfing a 70mm shell into the ground goes against this mod's design principles.
