### ISSUE TITLE
Bug with new LOS system

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#675]
In the most recent dev build, there's a bug where adjacent pawns sometimes act as a LOS blocker despite not being anywhere near the line of fire. Distance and firing angle seem to play a large role in whether the bug occurs, so to reproduce it reliably, you need the following: An archer, carrying a great bow, a blocker, and the target, contained in an area with zero cover. Layout should be as follows: https://i.imgur.com/uAP65Si.png

To start, place Target on one of the blue squares on the right, then move Blocker so it is adjacent to Archer on left side, like so: https://i.imgur.com/F0pwwBH.png

 Now check if Archer has a line of sight to Target, for each of the 4 blue squares.

One of two things will happen:

1) You'll run into the bug in at least one of the blue squares, where there's no line of sight despite zero obstructions on the trajectory. Moving Blocker one tile away from Archer, restores line of sight, confirming it's blocking LOS despite not being in the line of fire.
2) LOS will be working as expected on all 4 blue squares. If this happens, you need to move Target to the red side, and switch Blocker from the left to the right side of Archer, at which point you should get the bug in at least one of the red squares.

Example of bug occuring on red: https://i.imgur.com/JEyClN4.png

**Comment by NoImageAvailable** [comment]
Potential fix https://github.com/NoImageAvailable/CombatExtended/commit/589b06399d660f23eea3f352f8020ec68ff695db, still reproducible?

**Comment by LockdownX7** [comment]
Fixed in  b5087ef.
