### ISSUE TITLE
Shooters leaning from cover on the wrong side

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#677]
Shooters get easily confused about which side of a wall they should be leaning from to hit their target. When they lean on the wrong side, they still act as if they have LoS from where they're leaning from, so they mag dump into the wall.

Example: https://streamable.com/j1b3z

**Comment by NoImageAvailable** [comment]
Cannot reproduce as of https://github.com/NoImageAvailable/CombatExtended/commit/589b06399d660f23eea3f352f8020ec68ff695db, is this still an issue?

**Comment by LockdownX7** [comment]
Confirmed fixed in 589b063.
