### ISSUE TITLE
Sniper Rifle balancing issues

### ISSUE THREAD

**Issue by CombinedAutism** [NoImageAvailable/CombatExtended#678]
Brought this up on the forum already, thought it might be worth posting it here as well:

Questionable usefulness of Sniper Rifles for multiple reasons:
1. High probability of bullet interception by any kind of flora. Effect increases with distance, naturally, making it especially detrimental to Snipers. 
2. Easily interrupted LOS by other enemies. Restarts Aiming process over and over again when facing bigger groups of enemies (also issue for aiming RPGs etc. into the middle of enemies).
3. Rather low damage per bullet for huge draw time and quite useless against Centipedes. The latter should at least be considered for Anti Material Rifle, Sabot Round does not have any practical use.

**Comment by LockdownX7** [comment]
1 and 2 have been fixed in the current dev build.

As for 3, they need to have significant lower DPS than other weapon types for balance's sake, to compensate for their long range. Do agree on sabot.

**Comment by CombinedAutism** [comment]
It seems to me that the enormous draw time in Aimed Shot mode (which, realistically, you will be using almost all the time) already makes sure of that. I think it wouldn't hurt to increase damage per bullet, though I am strictly referring to the Tac50 here as the highest caliber option. Also, the SVD seems to be the flat out better alternative to the M24, the latter only having a 36% sights advantage while being worse in every other stat ranged stat except armor pen and range, where it's a tie.

**Comment by NoImageAvailable** [comment]
As has been mentioned, 1. and 2. have already been addressed, 3. doesn't fit the design paradigm of ammo. Bullets do not magically fly harder just cause you put a scope on a gun.

**Comment by CombinedAutism** [comment]
What about the Sabot round? I suggest a substantial buff to its Armor Pen or just removing it.
