### ISSUE TITLE
Allow CombatExtended.PatchOperationFindMod to match any mod in a list

### ISSUE THREAD

**Issue by sumghai** [NoImageAvailable/CombatExtended#690]
RimWorld's stock `PatchOperationFindMod` class allows modders to specify a list of mods to be looked up, and returns true if _any_ of the mods are found.

I would like to suggest that `CombatExtended.PatchOperationFindMod` be modified to support a similar capability.

**Use case**

A third-party mod called Rimmu-Nation Clothing is distributed by its original author in two versions - a standard version with only selected items set as craftable, and an "All Craftable" version. Both versions of the mod have different `modName`s, but otherwise use the exact same `defName`s for all items, and are intended to have the same CE stats.

Rather than having separate and redundant folders for both versions of the RN Clothing mod in the `Combat Extended\Patches` directory, a modder should be able to specify the names of both mods in just one set of patch files.

**Useful Reference: RimWorld stock implementation of `PatchOperationFindMod`**

(Disregard the `match` \ `nomatch` behaviour)
```
public class PatchOperationFindMod : PatchOperation
{
	private List<string> mods;

	private PatchOperation match;

	private PatchOperation nomatch;

	protected override bool ApplyWorker(XmlDocument xml)
	{
		bool flag = false;
		for (int i = 0; i < this.mods.Count; i++)
		{
			if (ModLister.HasActiveModWithName(this.mods[i]))
			{
				flag = true;
				break;
			}
		}
		if (flag)
		{
			if (this.match != null)
			{
				return this.match.Apply(xml);
			}
		}
		else if (this.nomatch != null)
		{
			return this.nomatch.Apply(xml);
		}
		return true;
	}

	public override string ToString()
	{
		return string.Format("{0}({1})", base.ToString(), this.mods.ToCommaList(false));
	}
}
```

**Comment by NoImageAvailable** [comment]
PatchOperationFindMod is obsolete and should be replaced, not modified
