### ISSUE TITLE
Embrasures are really bugged for me

### ISSUE THREAD

**Issue by Droknar** [NoImageAvailable/CombatExtended#698]
While using embrasures I noticed that my pawns would not shoot at enemies even if I directly told them to. When I selected a pawn and hovered over the enemy to get target info it said no line of site. There clearly was LoS between the enemy and the embrasure my pawn was behind. So I started to look into it in debug. 

If I had embrasures running north and south as a wall the pawn would only begin to aim if the enemy was directly in line with the pawn, but would stop aiming when the enemy took a step north or south. Sometimes they could fire at around a 45 degree angle if the enemy moved north or south to reach that angle.

Next I tried embrasures at a diagonal angle running north east - south west and north west - south east, only the corners of the embrasures touching each other. Placed an enemy in between them and all my pawns began to shoot the enemy until the enemy would move south of the horizontal position of the pawn. I tried placing an enemy south of the pawns horizontal plane and they didn't fire until the enemy walked north of the horizontal plane of each pawn.

Next I tried embrasures in a similar diagonal fashion (NW-SE and NE-SW) and my pawns would be facing south. Not once did they even begin to aim. Any enemy south of their horizontal plane they could not see it. 

If you were to use a protractor on screen set on an embrasure, it seems my pawns can only shoot enemies through embrasures if they are between angles 0-180, even then they sometimes can't see the enemy in this range. 

Another issue with them when running embrasures east-west and connecting to a wall to enclose my pawns the last 2 embrasures on the west side, 80% of the time make it so my pawns can't see. If I move the pawn to to the third embrasure to the east they can see. Move them back to either 2 or 1 to the west and they cant see.  Making my pawn run around a bit then trying the 1 or 2 west side embrasure sometimes make it work but only for a bit.

I have 2 types of embrasures, ED Embrasures and the one that comes with this mod and both are bugged.  Without CE turned on ED Embrasures works fine, but not running CE sucks.

**Comment by NoImageAvailable** [comment]
ED embrasures are never going to work with CE

Can you provide a screenshot of your setup

**Comment by NoImageAvailable** [comment]
No reply, closing
