### ISSUE TITLE
Chain Shotgun missing burst mode

### ISSUE THREAD

**Issue by pwaffle** [NoImageAvailable/CombatExtended#699]
So, the chain shotgun (saiga 12k) doesnt have burst mode in it, and the description says it should.

If we take a look at the code here: https://github.com/NoImageAvailable/CombatExtended/blob/master/Patches/Core/ThingDefs_Misc/Weapons_Guns.xml#L282

we notice that something is wrong - it appears the firemodes section is missing, with only the closing tag left. git blame shows us that apparently this was like that for quite a while.

if we add the missing lines:
```
    <FireModes>
      <aimedBurstShotCount>3</aimedBurstShotCount>
      <aiUseBurstMode>TRUE</aiUseBurstMode>
      <aiAimMode>AimedShot</aiAimMode>
    </FireModes>
```
as well as `<burstShotCount>3</burstShotCount>` into the properties section above, the gun gets the full auto fire mode, and is much more terrifying. im kinda new to this rimworld xml business, so im unsure if the expected behaviour is to have the burst mode enabled, or to have the full auto fire mode enabled. but in any case, this might want to be looked at.

its either that, or the description for the gun is outdated, and should be changed to it doesnt show as burst fire, and also that closing tag cleaned up

**Comment by NoImageAvailable** [comment]
Saiga IRL is a semi-auto shotgun. Description is for vanilla. WAD
