### ISSUE TITLE
Incompatibility with Prepare Carefully

### ISSUE THREAD

**Issue by Nianor** [NoImageAvailable/CombatExtended#718]
Running this mod with Prepare Carefully seems to disable Prepare Carefully completely? If anyone has experience to the contrary, feel free to correct me, but that's been my experience and I saw someone else on the Prepare Carefully page describe the same problem.

**Comment by NoImageAvailable** [comment]
Works fine on my end

**Comment by Nianor** [comment]
I’ll do more testing and try to get more info. It worked when I disabled CE, but it’s possible that one of the other CE-related mods I was using was the actual source of the issue.
