### ISSUE TITLE
Errors when loading game

### ISSUE THREAD

**Issue by MilanDierick** [NoImageAvailable/CombatExtended#719]
Exception in SetupToils for pawn Stench driver=JobDriver_Reload (toilIndex=0) driver.job=(ReloadWeapon (Job_4240168) A=Thing_Human357684 B=Thing_Gun_BoltActionRifle404675) lastJobGiver=CombatExtended.JobGiver_CheckReload
System.NullReferenceException: Object reference not set to an instance of an object
at Verse.GenGrid.InBounds (Verse.IntVec3,Verse.Map) <0x00015>
at (wrapper dynamic-method) RimWorld.MoteMaker.ThrowText_Patch1 (UnityEngine.Vector3,Verse.Map,string,UnityEngine.Color,single) <0x000b9>
at RimWorld.MoteMaker.ThrowText (UnityEngine.Vector3,Verse.Map,string,single) <0x00083>
at CombatExtended.JobDriver_Reload/<MakeNewToils>d__23.MoveNext () <0x00c7f>
at Verse.AI.JobDriver.SetupToils () <0x00117>

Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:SetupToils()
Verse.AI.JobDriver:ExposeData()
Verse.PostLoadIniter:DoAllPostLoadInits()
Verse.ScribeLoader:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow(String)
Verse.Root_Play:<Start>m__0()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()

**Comment by NoImageAvailable** [comment]
What's the context for this?

**Comment by MilanDierick** [comment]
This error occurs when I start the game. I only have this mod running, and it is loaded After Core.

**Comment by NoImageAvailable** [comment]
By start the game, you mean load a colony? Did you start a new game after installing?

**Comment by MilanDierick** [comment]
No, I meant just launching the game.

**Comment by MilanDierick** [comment]
I have to say, that I dont experience Any issues during playing, I only See the error.

**Comment by NoImageAvailable** [comment]
This is not an error you can get on game launch

**Comment by LockdownX7** [comment]
He meant to say game _load_, not launch. To reproduce, have a colonist halfway through a reload, save the game, then load it.
