### ISSUE TITLE
Review combat-related mood penalties

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#72]
Need to review some mood penalties related to combat and its aftermath. For example if a prisoner bleeds out before medical care can be administered it will give a colony-wide -5 mood penalty, which is excessive.

**Comment by dvalroth** [comment]
I'd noticed this. I took a horrifically wounded raider prisoner and she died pretty much immediately and everyone got pissed that I allowed that to happen to an "innocent prisoner". I had thought that the vanilla system had been amended to give you a grace period to account for just that eventuality, but perhaps it was another mod that did it. The solution that I remember was to simply delay adding the "innocent" flag (or was it add a "guilty" flag?) until the prisoner was healthy and incarcerated.

**Comment by NoImageAvailable** [comment]
Solution might be to check the cause of death for external violence. So executing a prisoner by shooting him would proc the penalty, but a prisoner dying to blood loss, infection or hypothermia would not.

**Comment by NoImageAvailable** [comment]
In testing only the bleedout triggering the innocent prisoner died thought seems problematic and its easy enough to avoid after the first time. Its still an issue I'd like solved in the future but for now I think we can leave it as it is.
