### ISSUE TITLE
Toggling Fire At Will to off doesn't cancel explicit attack orders

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#722]
Fire At Will works as expected when colonists are automatically selecting targets: when the toggle is set to off, they stop aiming and stand down.

However, if the colonist has been given a manual order to attack a specific enemy, setting it to off merely resets the aiming progress, and they'll resume attacking immediately.

**Comment by NoImageAvailable** [comment]
Is this a vanilla thing?

**Comment by LockdownX7** [comment]
No, colonists don't even have a Fire At Will toggle in vanilla.

The only case where vanilla has a similar mechanic is with the mortar's Hold Fire toggle, which works correctly both in vanilla and with CE installed: when told to stop firing, mortars cancel any force-attack orders they may have. It's only colonists that have the bug.

**Comment by NoImageAvailable** [comment]
>colonists don't even have a Fire At Will toggle in vanilla 

Are we talking about the same thing? Because CE dropped it's own hold fire implementation when vanilla got one and that's the one we're using

**Comment by LockdownX7** [comment]
Ah, I must have gotten mixed up when testing this. You're right, this isn't related to CE at all, as the bug is reproduceable in vanilla.
