### ISSUE TITLE
Null exception when changing ammo setting

### ISSUE THREAD

**Issue by Askovan** [NoImageAvailable/CombatExtended#727]
I found a bug report with the same issue:

https://github.com/NoImageAvailable/CombatExtended/issues/218

So basically i started a new game as rich explorer with edited pawns and items (prep carefully). Upon landing the selected ammo was lying on the ground ready for pickup and everything worked fine. Went into settings a while after to check something and upon opening the CE settings the in the link described error occurred. Since then i cant drop ammo from inventory and no ammo drops from enemies. My gun still uses ammo but every time my pawn fires it no matter how many shots he reloads a complete mag of those bullets i cant drop. so the game acts as if ammo is disabled but the guns still use ammo when firing. The null exception message pops up every time i change the ammunition setting.

Hope its not just that i am too stupid and thanks in advance

**Comment by NoImageAvailable** [comment]
Changing ammo settings on a running game is not supported.

**Comment by Askovan** [comment]
I didn't change the ammo settings... i just opened the settings menu got an error and then i had the described error

**Comment by Askovan** [comment]
welp. Just realized i cant make nor spawn ANY ce ammo. Every ammotype of ce is disabled. including mortar shells.

**Comment by Askovan** [comment]
Ok i tested around a bit.
New game. i did not touch the ce setting after game start and same problem still applies. Ammo gets used by the gun but cant be dropped. I can spawn in mortar shells and the FSX and Pyro stuff. But no Ammunition otherwise. cant make any at the loading table and also can only make 90 mm shells at the machining table.

**Comment by Askovan** [comment]
Hmmm. The error always states <filename unkown>. Did i install it wrong or something?

**Comment by Askovan** [comment]
Ok sorry for bothering you. I fucked up and installed a ce compatibility patch for Misc. Robots and MAI and that thing bugged around. deactivated now it works. Thanks anyway and sorry again.

**Comment by Alicecomma** [comment]
The 90 mm shells being craftable, 81 mm (anti) and mechanoid showing up in the debug spawn menu with ammo disabled is fixed in #759 .
