### ISSUE TITLE
Turrets are broken

### ISSUE THREAD

**Issue by LockdownX7** [NoImageAvailable/CombatExtended#728]
Auto-turrets don't fire at all, getting stuck in an infinite aiming cycle.

Manned turrets fire, but exhibit odd behaviour. After firing the first burst in aimed shot, subsequent bursts sometimes only go through one aiming cycle, as if the turret were using snapshot instead of aimed shot.

Handheld weapons don't seem to be affected.

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/3bc9266ce7369cef86e7a74111ad2e0dab2b040a
