### ISSUE TITLE
Make Prometheum & FSX resources explosive

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#753]
Not-exactly suggested by Roll1D2 Gaming; he questioned whether Prometheum would self-ignite out in the open and explode.

Since Blazebulb self-ignites, it does make sense that Prometheum (its harvested thingDef) self-ignites to some capacity. While the containers of prometheum seem to be high-pressure tanks, possibly with a self-regulating pressure system to prevent high temperatures, it would make sense that a high enough temperature would at least cause the prometheum to explode into fire. Alternatively, when shooting the containers, it would make a lot of sense for the prometheum to leak out and self-ignite according to outside temperature, or if struck with AP-I or other flame-damage rounds to explode entirely into flames.

A similar argument could be made for FSX, which is harvested from boom-creatures. The visual packaging of these is even less protective, so shooting one of these resource piles or otherwise damaging them should really set off an explosion.

Prometheum:
- [ ] Make Prometheum self-ignite at sufficiently high temperatures (say 50 C - includes heatwaves - or 100 C?)
- [x] Make FilthPrometheum leak out of Prometheum when the stack is damaged
- [ ] Ignite Prometheum if the stack is damaged using AP-I or other flame damage weapons

FSX:
- [x] Explode FSX when damaged, much in the same way as damaging Boomalopes, Boomrats etc. works - or maybe even more viciously, because the resource is probably more pure

**Comment by NoImageAvailable** [comment]
>The visual packaging of these is even less protective

They are effectively pallet swaps.

Adding explosions to those resources has always been one of those nice-to-have things nobody ever implemented.

**Comment by Alicecomma** [comment]
Slapping an explosion comp on them does nothing, they don't explode upon death.

**Comment by Alicecomma** [comment]
Let us assume the full mass of both FSX and Prometheum is "explosive", then there's 0.5 kg of explosive in both cases. The lethal radius from 0.5 kg FSX can be obtained taking an R.E. of 1.6 (https://en.wikipedia.org/wiki/TNT_equivalent), e.g there's 0.8 kg TNT-equivalent. Assuming a 3.75 safety factor for lethal damage, the blast radius is 3.5 meters using:

r [m] = 3.75 * (kg_FSX * R.E._RDX)^(1/3) = 3.5 m

For Prometheum: Molotov contains 2 Prom. per 10 molotovs, so that's 0.1 kg Prom. per molotov. The explosion has (lethal?) radius 1.5 m, so the R.E. for prometheum can easily be calculated to be 0.64 using:

R.E._Prom = (r [m] / 3.75)^3 / kg_Prom = 0.64 [kg Prom/kg TNT]

Then, 0.5 kg prometheum should have a blast radius of 2.6 m.

**Comment by Alicecomma** [comment]
Some issues:

A frag grenade (0.05 kg FSX) explosion does 40 damage. Should pure FSX (0.5 kg, 10x) do 60 damage? That seems a lot for just a resource - but it also is the only logical reasoning.

A molotov cocktail (0.1 kg Prometheum) explosion does 20 damage. Should pure Prometheum (0.5 kg, 5x) do, say, 30 damage? This would immediately destroy the entire stack of Prometheum.

- Should explosions do less damage to the ammo stack?

**Comment by Alicecomma** [comment]
Majority of design goals implemented - closed for now, although it could be refined in the future.
