### ISSUE TITLE
Timed explosives suppresses pawns causing them to hunker down -- They should flee instead

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#758]
The problem is mainly that a suppressed pawn "without nearby cover" as determined by the methods handling that can only hunker down, and won't run from timed explosives. Furthermore, a hunkering pawn can not be controlled by the player to flee from the explosive.

There's some options:
- Improve the cover search so it will find cover more quickly/better based on the time of the timed explosive
- Prevent grenades from adding suppression, so pawns won't hunker down from them
- Prevent grenades from causing hunkering
- Add a new job "flee" or something which causes the pawn to run even without cover whenever there's a timed explosive landed close to them

There's probably more options. Requires at least some rewrite of the suppression system - probably nothing too major.

**Comment by NoImageAvailable** [comment]
Hunkering is the correct course of action, both IRL and in CE, to minimize effects of shrapnel. The only time fleeing makes any sense at all is if you're within the blast radius of the explosive.
