### ISSUE TITLE
Some guy has bullets floating on his base

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#763]
Modlist in pictures...

https://s17.directupload.net/images/190605/xgz6qux2.png
https://s17.directupload.net/images/190605/bry6hsmm.png
https://s17.directupload.net/images/190605/4hqadvtu.png

Pictures:

![](https://s17.directupload.net/images/190605/nq97o7qs.png)
![](https://s17.directupload.net/images/190605/vcm6fqm5.png)

Link:

https://steamcommunity.com/workshop/filedetails/discussion/1631756268/1850323802572522489/

(President Evil)

**Comment by NoImageAvailable** [comment]
Without an error log this report is worthless
