### ISSUE TITLE
Loadout default can't be _selected_, but it can be _changed_

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#773]
As shown:

https://www.youtube.com/watch?v=L_D2SEim3dY&t=12m43s

- The let's player has managed to rename and edit the default loadout (to "Rex LMG-Hammer"), because it can be edited whenever another loadout is removed (because then it selects the default loadout in the loadout editor).
- It's not possible to Select loadout for the default loadout.
- Creating a new loadout and deleting it does select the default loadout, even when none of the pawns have it selected. 

Perhaps:
- The default loadout should not be renamable
- The default loadout should be selectable in "Select loadout"

---

Another issue is that when you press the "edit loadout" icon (pencil icon) and create a new loadout, the pawn you clicked the pencil icon on doesn't get their loadout set to the new loadout.

**Comment by LockdownX7** [comment]
I assume the default 'Nothing' loadout is just a placeholder that pawns start with, and isn't meant to be edited at all. A simple fix is to make it so deleting the currently selected loadout reverts the window to the "No loadout selected" state, rather than try to select another one automatically.

**Comment by LockdownX7** [comment]
>Another issue is that when you press the "edit loadout" icon (pencil icon) and create a new loadout, the pawn you clicked the pencil icon on doesn't get their loadout set to the new loadout.

This behaviour is consistent with the edit buttons for outfits, food restrictions, and drug policies in vanilla. It's meant as a quick shortcut for editing the pawn's current loadout, not a means of reassigning them.
