### ISSUE TITLE
Centipedes (among others) can't be killed with Debug: Kill

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#80]
Somehow destroying a bunch of bodyparts doesn't kill them, this yields errors.

**Comment by NoImageAvailable** [comment]
Somewhat harmless on Centipedes but it does occur rarely on people in cryosleep. The bug exists in vanilla though, it is simply more exaggerated with the CE armor system

**Comment by NoImageAvailable** [comment]
Fixed https://github.com/NoImageAvailable/CombatExtended/commit/efcbd40f1733c3f722aec3a480f0ef545760560f

Damage from sources without pre-defined armor penetration values now defaults to infinite penetration.
