### ISSUE TITLE
Will Vanilla Armour/Apparel Expanded Patches be in the upcoming release?

### ISSUE THREAD

**Issue by sevvie** [NoImageAvailable/CombatExtended#806]
My current setup uses a local checkout of CE:FT with the aforementioned directories from the Patches dir on this repository's Development branch (I've been experimenting with large numbers of mods), and I've not seen any issues though I will admit I haven't tested thoroughly. Given your notice over on the CE:FT issues about the impending release, I was curious if those patches were ready for release, or if I'm putting my game in great danger.

**Comment by NoImageAvailable** [comment]
Issue tracker is not for questions, use the forum and/or Discord
