### ISSUE TITLE
Should make AI realize that black smoke is a damage source.

### ISSUE THREAD

**Issue by jinlan** [NoImageAvailable/CombatExtended#861]
First, an enemy pirate has ignited my wooden wall, then because I have put down the fire( from other side of the wall ), he just try to re-ignite my wall, while let black smoke damaging him. Finally he is killed by the black smoke.

So, I think, AI should avoid black smoke just like AI avoiding fire.

-----------------------------------------------------------------------------------------------
What about make black smoke make less damage if not indoor?

My version is : 99cc5a521fd4deee158c7e3995f0455520994343

**Comment by LockdownX7** [comment]
This shouldn't be as much of a problem in the current version, as smoke no longer targets pawns in adjacent cells.
