### ISSUE TITLE
Missing armor penetration values for some bullets

### ISSUE THREAD

**Issue by NickZiggy** [NoImageAvailable/CombatExtended#902]
Example from \Defs\Ammo\Shell\20x110mmHispano.xml :
> <ThingDef Class="CombatExtended.AmmoDef" ParentName="Base20x110mmHispanoBullet">
       <defName>Bullet_20x110mmHispano_FMJ</defName>
       <label>20mm Hispano bullet (FMJ)</label>
       <projectile Class="CombatExtended.ProjectilePropertiesCE">
          <damageAmountBase>85</damageAmountBase>
          <armorPenetrationBase>1.106</armorPenetrationBase>
       </projectile>
       </ThingDef>

armorPenetrationBase apparently isn't used anymore and shows 0 armor penetration in-game
Please fix your mod

**Comment by LockdownX7** [comment]
Non-default caliber stats are being reviewed, and will be added on next release as soon as approved.
