### ISSUE TITLE
Incompatability with Show Hair w/ Hats

### ISSUE THREAD

**Issue by Xedict** [NoImageAvailable/CombatExtended#919]
Combat Extended seems to be messing with how the Show Hair w/ Hats works. The functionality of the Show Hair mod seems borked with many hats, even those from other mods. I'm guessing this could be due to the recent change on multiple apparel layers on pawn heads. 

Any suggestions?

**Comment by Dyrewulfe** [comment]
You could give this a try: https://github.com/NoImageAvailable/DontShaveYourHead

It's a bit more robust, and NIA updated it for the CE changes, I believe.

**Comment by LockdownX7** [comment]
Fixed on Show Hair's side.
