### ISSUE TITLE
Spike Traps have extreme armor penetration

### ISSUE THREAD

**Issue by NickZiggy** [NoImageAvailable/CombatExtended#929]
They still use the old % based system. Even wooden ones instantly kill power armored pawns.
Maybe you should take some more time and pay attention every time you folks decide to needlessly overhaul every basic mechanic.

**Comment by Dyrewulfe** [comment]
Three things:

1. Known issue.

2. Doesn't have anything to do with "They still use the old % based system."

3. Most importantly, are you paying these folks bills or something? No? No one working on this project owes you a damn thing, man. And acting like an angry entitled punk doesn't help anyone with anything.
