### ISSUE TITLE
Issue with Rimsenal

### ISSUE THREAD

**Issue by furiousskeleton** [NoImageAvailable/CombatExtended#938]
With the new armour system, the armour from Rimsenal are extremely underpowered - to the point that they are weaker than standard clothing.

The Pioneer armour has an RHA rating of 0.7mm. On the other hand, the power amour has an RHA rating of 20mm. So there is a large discrepancy here.

**Comment by NoImageAvailable** [comment]
CE team doesn't handle third party patches
