### ISSUE TITLE
Reloading Bug - Nature Retreat

### ISSUE THREAD

**Issue by Justryan16** [NoImageAvailable/CombatExtended#944]
When a colonist enters the "Nature Retreat" mental break state they are unable to reload their weapons, this has happened to two of my colonists, with one losing an arm to a PISSED muffalo. 
![20191219171528_1](https://user-images.githubusercontent.com/59045233/71154002-482b9800-2286-11ea-92aa-e88ea26aadec.jpg)

(For info, the guy that lost the arm was Gee, Bishops brother, they are both depressed that their dad ((who crashlanded in a pod) died in bishops arms. like a second away from being healed))

**Comment by N7Huntsman** [comment]
This mental break is added by Psychology.
