### ISSUE TITLE
Rebalance ammo crafting costs

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#95]
Right now ammo costs are largely informal, as large quantities of ammo can be obtained at minimal cost. Cost differences between ammo types are virtually non-existent. FMJ ammo ends up being superfluous. Should look into changing crafting costs, with FMJ remaining as a cheap but suboptimal option, HP having significantly increased (about double?) steel cost and AP requiring Uranium as it is generally the best ammo type.

**Comment by NoImageAvailable** [comment]
According to BobDoleV the vanilla game uses the formula of 250 work amount = $1 market value, e.g.

> 10000/250=40
40/500=.08
SteelCost=12(2)=24
24/500=.048
Cost per bullet in terms of work and material cost = .128
for 556x45

As of right now this would more than double ammo cost for certain types. Need to consider rebalancing crafting times if we're going to bring work costs in line with vanilla. Also was suggested to make AP/HP ammo more specialized by rebalancing their damage numbers.

Another thing to consider is raider loadouts. If ammo prices go up, the cash injection from raids increases. Should look into potentially reducing raider ammo to 50-200 rounds, depending on weapon ammo consumption. 

Also need to consider removing ammo drops from Mechanoids, right now Centipedes are giant loot pinatas that drop huge amounts of cash in the form of ammo.

**Comment by Valerate** [comment]
What is your idea how ammo should be? Should It be scarce (like Fallout 4 on hardmore, you barely get any ammo, so you need to use weapons depending on what you have and not what you want to use) or something you just have free access too?
And did you have plans to "complicate" it by adding more ingredients (like gunpower, lead for tip etc)?

**Comment by NoImageAvailable** [comment]
For small arms like rifles, LMG's, etc. regular ammo should be fairly accessible to a non-tribal colony after the early game. Specialized ammo should still be available but at a noticeable cost increase, ideally pushing it into the mid-late game, when players can afford the luxury.

Heavier weapons such as rocket and grenade launchers should feature some scarcity to balance out their killing power. A thermobaric warhead that can take out most of a tribal raid in one good hit should be expensive to the point you don't want to use it unless the situation is desperate enough to warrant it. Deploying these weapons should be a cost/benefit-decision based on the scarcity of ammo and the size of the threat facing the player.

Regarding additional ingredients like gunpowder, my stance on that is if the only purpose of a resource is to be made into something else it shouldn't exist. I don't want crafting to turn into micromanagement hell where you have to keep track of a dozen different types of casings and primers, etc.

**Comment by NoImageAvailable** [comment]
A17 update introduces experimental new formulas for ammo stats and crafting times, needs playtesting.

**Comment by NoImageAvailable** [comment]
Tester feedback is generally positive on the new formulas.

**Comment by NoImageAvailable** [comment]
Re-opening due to repeated feedback that ammo costs are too low. Need to rule out loud minority effect and if needed revisit the previous idea about increasing steel/adding exotic ingredient costs.

**Comment by NoImageAvailable** [comment]
Idea came up in a Discord conversation:
- Implement primers as ingredient in ammo crafting
- Primers can be obtained in bulk from traders or by breaking down other ammo
- Crafting primers requires a component assembly bench and potentially rare resources like neutroamine.

This would solve a lot of the issues regarding ammo type availability, since you could convert looted/bought ammo into the types you need. You'd no longer run the risk of traders not carrying the exact ammo you need. At the same time it'd make ammo crafting much more limited as you can only buy so many primers.

**Comment by junkdeck** [comment]
+1 for more detailed ammunition crafting. Was kind of disappointed to see ammunition only requires steel.
Primers could either be bought from traders, acquired from disassembled ammunition or perhaps crafted from components? Easy "fix" could just be to require components when crafting ammunition, too.

It'd be kind of neat to also have to make shells, bullets and gunpowder, although that might introduce too much needless micro-management of resources.

**Comment by sauerkrau5** [comment]
Why not have universal components like shells and primers? Instead of micromanaging it could be simplified by having *make 500 small caliber casings* out of steel, and 500 small caliber primers from chemfuel. Then a gateway of plasteel and components to make high powered rounds like charge rifles. After crafting the basic components in bulk you could then allow smaller batches of finished ammo since the majority of resources and work is already done.

**Comment by Alicecomma** [comment]
"Primer" should be replaced by "Propellant", so your limiting factor would be gunpowder. That way you'd get more gunpowder from high power rounds and it'd take more gunpowder to craft them too, giving people a reason to craft 9x19 Para or even 22 LR (due to very low gunpowder requirement).

**Comment by jinlan** [comment]
I suggest emphasize "inefficiency" in bullets making. Even in far further, big factory should still be more efficient in mass production. Especially for bullets, which is one-time-use items that require high precision.

**Comment by cramer1592** [comment]
If ammos require a small amount of FSX, it would make ammos more valuable maybe. If there are other ways to obtain FSX other than boomalopes or caravans(ex: processing chemfuel?) it would be nice. Just a suggestion.

**Comment by NoImageAvailable** [comment]
Ammo costs rebalanced in 1.6, closing this until further feedback
