### ISSUE TITLE
Where to submit patches?

### ISSUE THREAD

**Issue by Whalefilmz** [NoImageAvailable/CombatExtended#951]
I'm still relatively new Github, I have a patch to test, have looked at, code checked, etc. Where/how do I submit it?

**Comment by N7Huntsman** [comment]
The onus to ensure it works as intended is really kind of on you as the patch author. Once you've got it working, you can create a PR with the patch from your fork's master branch to the CE's master branch. Someone will take a look at it, but this is more a last stage QA check than a check for basic functionality.

**Comment by Whalefilmz** [comment]
Thanks, I'm working on testing right now, wasn't sure what stage of the process this was. I think I answered my own questions I had off the top of my head, but if I get anymore do I ask them here? Or is there a better place?

**Comment by N7Huntsman** [comment]
You can join the discord, there's a dedicated channel for discussion regarding patches. https://discordapp.com/invite/SGQKESU

**Comment by Whalefilmz** [comment]
Thanks!
