### ISSUE TITLE
CE loaded after Gradient Hair with HAR causes duplicate XML nodes

### ISSUE THREAD

**Issue by MissPotato** [NoImageAvailable/CombatExtended#960]
Rimworld Version: 1.0.2408 64bit
CE Version: 1.0.1.82
Mods in order of load order: Core, Humanoid Alien Races 2.0, HugsLib, Orassans, Gradient Hair, Combat Extended
Log: https://gist.github.com/f03d79dc59f52b75410a9a7afe9566bc

I noticed this while I was setting up Fast Track but switched over to this version for testing. It seems that if I load Gradient Hair last the error goes away, but I'm concerned that it's just a bandaid fix and may cause issues in the future.

**Comment by LockdownX7** [comment]
The error is caused by CE adding a comps field to Orassans without checking if it already exists (which it will if GH loaded first). I'll fix this on CE's end, but for the time being it'll work fine if you load GH after CE.
