### ISSUE TITLE
Spike traps fully pierce AP

### ISSUE THREAD

**Issue by MissPotato** [NoImageAvailable/CombatExtended#966]
I have reduced the mod list to just CE and Core and spike traps are doing an absolute metric ton of damage to the point of one-shotting anything. At first, I thought it was just a side effect of the AP system and pawns generally being squisher until I was able to instantly kill a Centipede using a wooden spike! I have to admit, it feels pretty great instantly killing a Centipede lol

I did see the previous report of this issue but it was closed so I assume it's just cropped up again? 

Here is the error generated on springing of the trap: https://pastebin.com/mSyvqgY0

**Comment by NoImageAvailable** [comment]
Spike traps already removed in dev build
