### ISSUE TITLE
Escape pod pawns are not injured

### ISSUE THREAD

**Issue by HRBest** [NoImageAvailable/CombatExtended#99]
Escape pod pawns are not injured after their drop pod lands and leave the map immediately, leaving the player no time to capture.

Sorry if this was reported before, haven't found it in Issues
Enabled mods: Core, HubsLib, ModlistBackup, CE (3cf8402)

**Comment by NoImageAvailable** [comment]
Probably the same as https://github.com/NoImageAvailable/CombatExtended/issues/80 since the same functions are at work
